Automattic/woocommerce-services

assets/stylesheets/components/foldable-card/style.scss, assets/stylesheets/style.scss, client/components/shipping/packages/style.scss, client/views/shipping/style.scss
Getting rid of the tab/spacing issues in the stylesheets. They should all have a nice clean tab structure now. Coding standards FTW.
@jkudish or @jeffstieler for review.
=> Stylesheets: cleaning up the tab structure

client/components/save-form/index.js, client/components/shipping/packages/add-package-presets.js, client/components/shipping/packages/add-package.js, client/components/shipping/packages/index.js, client/components/shipping/packages/packages-list-item.js, client/components/shipping/packages/packages-list.js, client/components/wcc-settings-form/settings-item.js, client/state/form/packages/actions.js, client/state/form/packages/reducer.js, client/state/form/packages/test/actions.js, client/state/form/packages/test/reducer.js, client/state/form/reducer.js, client/state/settings/actions.js, client/state/settings/reducer.js, client/state/settings/test/actions.js, client/state/settings/test/reducer.js
Fixes #240.
To test:
* Click a package's name
* Verify that the modal pops up, says "Edit package" at the top, button says "apply changes"
* Change the package name
* Click "apply changes"
* Verify package name has changed in list
* Click "add package" (under packages list)
* Verify form is empty, says "Add package" at top, "package type" dropdown is present, button says "add package"
* Select a USPS preset from the "package type" dropdown
* Verify that form values are populated with data
* Hit ESC or click off the modal to dismiss it
* Click "add package" (under packages list)
* Verify all previous values are present
* Click "add package" (on modal)
* Verify package had been added to list
=> Hook up edit package link (redux)

CONTRIBUTING.md
=> Add PHPUnit testing instructions to CONTRIBUTING documentation.

client/components/shipping/packages/packages-list-item.js, client/components/shipping/packages/packages-list.js, client/components/shipping/packages/style.scss
=> Add special display for when there are zero packages

classes/class-wc-connect-shipping-method.php, tests/php/test_class-wc-connect-shipping-method.php
Fixes #251 
@allendav @nabsul @jeffstieler
=> Remove the Package validation error log, it only added noise to the logs

client/components/wcc-settings-form/settings-item.js, karma.conf.js, package.json, tasks/i18n.js
CI is not failing even when ESLint is givin errors. This is a fix for that.
=> Make the CI build fail on ESLint errors

woocommerce-connect-client.php
Fixes #423 
This issue should be the last thing merged to master before we cut the `release/alpha-v0.3` branch
=> Roll version to 0.3

.eslintrc.js, client/components/number-field/number-input.js, client/lib/utils/sanitize-html.js, client/settings/state/packages/reducer.js, client/settings/state/packages/test/reducer.js, client/settings/views/services/group.js, client/settings/views/wcc-settings-form/settings-group.js, client/shipping-label/views/index.js
Closes #490 
Closes #271 
This change includes:
- Adding require semicolons to eslint file
- running eslint --fix to add the semicolons that have been missing
- Reviewed and compared server and client files. Found a couple code style fixes in the file.
How to test:
- No functional changes have been made to the code
- Try the unit tests
- Make sure the plugin is still working as before
@allendav @jeffstieler @DanReyLop @robobot3000
=> Add require semicolon option to eslint file

assets/stylesheets/components/foldable-card/style.scss, assets/stylesheets/shipping-label.scss, assets/stylesheets/style.scss, classes/class-wc-connect-shipping-label.php, client/shipping-label/state/actions.js, client/shipping-label/views/steps/address/fields.js, client/shipping-label/views/steps/address/suggestion.js, client/shipping-label/views/steps/packages/index.js, client/shipping-label/views/steps/packages/list.js, client/shipping-label/views/steps/packages/style.scss
=> Packages step UI (readonly)

classes/class-wc-connect-api-client.php
None of the server endpoints are looking for bodies on GET requests, and it isn’t technically correct to send them.
Before this change, all GET requests made by the client throw: `PHP Warning:  http_build_query(): Parameter 1 expected to be Array or Object.  Incorrect value given in wp-includes/Requests/Transport/cURL.php on line 507`. This has been occurring since the first GET request was added.
Correcting this behavior has the side effect of fixing the JSON error that occurs during label status retrieval. See below:
=> Only add body data to POST and PUT requests.

assets/stylesheets/shipping-services.scss, client/settings/views/services/entry.js, client/settings/views/services/group.js
=> Fixed shipping method instance service styles

tasks/release.js
Fixes: https://github.com/Automattic/woocommerce-connect-client/issues/512
Little trash pickup changes:
- `Wocommerce` to `Woocommerce`
- `You good with that?` to `Sound good?`
- `OK` to `Okay`
=> Copy: Fixing a typo and updating copy

README.md, readme.txt, woocommerce-connect-client.php
Fixes #666 #680 #681 #685 in preparation for initial check-in into WordPress.org SVN
No code changed
=> Updated README.md, Contributors, version (0.9.1)

classes/class-wc-connect-service-settings-store.php, classes/class-wc-connect-shipping-method.php
Adds Automattic/woocommerce-connect-server#322
For flat rate services:
For multiple items ordered:
To test:
* place a new order
* view the order as an admin
=> Added packaging details to the shipping info

readme.txt, woocommerce-connect-client.php
Fixes #700 
No testing required.
=> Update plugin changelog, version for 0.9.3

webpack.config.js
Fixes #743 
To test:
* checkout this branch
* restart the webpack server
* open the shipping settings page and verify that it is usable
=> Resolving the react versions in the node_modules dir

classes/class-wc-connect-api-client.php, classes/class-wc-connect-shipping-method.php
Adds #684 
Test steps outlined in Automattic/woocommerce-connect-server#704
=> Sending a list of enabled preset boxes to the server

classes/class-wc-connect-shipping-label.php, client/shipping-label/state/actions.js, client/shipping-label/views/purchase/steps/packages/index.js
Adds #758 
To test:
* remove all the packages from the packaging manager
* place a new order
* verify that when you open the Labels modal, the packages section is automatically opened, and shows a message
=> Labels - Added a message when there are no packages configured

client/shipping-label/state/actions.js
Fixes #722 
To test:
* open an order shipping via one of the USPS delivery methods, with correct origin and destination addresses
* once the rates have been fetched and selected automatically, verify that the preview loads
* open an order shipping with non-WCC delivery methods, such as Free Shipping
* once the rates have been fetched, verify that the rates step expands, but the preview doesn't appear until a rate has been selected
=> Showing the label preview if all rates have been preselected

classes/class-wc-rest-connect-self-help-controller.php
=> Remove debugging error_log() call from Self Help REST Controller.

readme.txt
Update change log, WP version, WPCOM billing link.
=> Version 0.9.5

assets/stylesheets/shipping-services.scss, client/settings/views/services/group.js
=> Services - Moved the select all checkbox to the foldable card header

classes/class-wc-connect-help-view.php
Closes #806
Improve message when last shipping rate failed.
@kellychoffman
=> Recommend checking log messages if an error rate request failed

assets/stylesheets/banner.scss, classes/class-wc-connect-nux.php, woocommerce-connect-client.php
This manages the notices shown on specific pages as part of the NUX. I added an example labels notice.
The intention is for this class to also host other NUX-related PHP code.
=> Added a class for managing NUX notices

assets/stylesheets/banner.scss, woocommerce-connect-client.php
Fixes: https://github.com/Automattic/woocommerce-connect-client/issues/834
Before
After
=> TOS notice: adds friendlier copy, removes CfW reference, is dismissable

.gitignore, CONTRIBUTING.md, DEVELOPER.md, README.md, classes/class-wc-connect-api-client.php, classes/class-wc-connect-debug-tools.php, classes/class-wc-connect-error-notice.php, classes/class-wc-connect-help-view.php, classes/class-wc-connect-service-settings-store.php, classes/class-wc-connect-settings-pages.php, classes/class-wc-connect-shipping-method.php, readme.txt, tests/php/test_wc-connect-services-validator.php, woocommerce-services.php
This is pretty much a Search & Replace PR, no need to pay it much attention.
=> Changed everywhere user-facing text from "Connect for WooCommerce" to "WooCommerce Services"

client/components/info-tooltip/index.js
=> Fixed InfoTooltip PropTypes

woocommerce-services.php
Fixes #777 
The TOS notice is now only rendered if the current user is the owner of the jetpack token. I also rearranged the flow of TOS and notice dismissal checks to make the code more readable.
To Test: Unfortunately, you can't really test this in Jetpack's dev mode (in which case the TOS is always shown for any admin). You'll need to setup an internet-facing machine and really connect Jetpack.
- To reset the flow, simply delete the `wc_connect_tos_accepted` option from your database
- Try out the dismissal; it should disable the plugin and show a notice
- Try logging in as an admin that is not the jetpack token owner
- Try accepting the TOS and make sure the plugin gets enabled correctly
=> Only Jetpack owner accepts TOS

assets/stylesheets/style.scss, classes/class-wc-connect-help-view.php, classes/class-wc-connect-nux.php, classes/class-wc-rest-connect-services-controller.php, client/lib/initialize-state/index.js, client/settings/index.js, client/settings/state/actions.js, client/settings/state/reducer.js, client/settings/views/wcc-settings-form/index.js, client/settings/views/wcc-settings-form/nux-notice.js, woocommerce-services.php
Fixes #856 
Also removes the placeholder code for notices.
To test:
* open the service settings page
* verify that the notice appears
* dismiss the notice and refresh the page
* verify that the notice is no longer visible
CC @kellychoffman
=> Added service settings NUX notice

woocommerce-services.php
Fixes #887
Turns out, this is an already built-in WP functionality. By default it appends `?ver={WP_VERSION}` to all the JS/CSS, but you can specify a custom string. I've used the plugin version.
To test:
* Open any WCS page (Order screen, Self-help page, etc)
* Check in the Network Inspector that all WCS-related files were requested with `?ver=1.1.1` at the end
=> Change the bundles URLs on each new release to avoid cache issues

classes/class-wc-connect-error-notice.php
=> Fix error log dismiss 404 with relative URLs

package.json, readme.txt, woocommerce-services.php
Update readme, plugin file, and change log for version 1.3.0.
=> Version 1.3.0

client/shipping-label/views/tracking-link.js
There is no way to test it right now, but this is trivial enough.
Fixes #956
=> Added FedEx tracking URL template to the <TrackingLink> component

classes/class-wc-connect-service-schemas-store.php, classes/class-wc-connect-service-settings-store.php, classes/class-wc-connect-shipping-label.php, classes/class-wc-connect-shipping-method.php, classes/class-wc-rest-connect-shipping-label-controller.php, classes/class-wc-rest-connect-shipping-rates-controller.php
Fixes #891 
Requires the `update/support-more-carriers` branch in the server.
=> Remove "usps" hardcoding to support more carriers for label purchases

package.json, readme.txt, woocommerce-services.php
* https://github.com/Automattic/woocommerce-services/pull/989
=> Version 1.4.1

client/shipping-label/views/purchase/steps/rates/index.js, client/shipping-label/views/purchase/steps/rates/list.js
This PR:
- removed unnecessary props from `<ShippingRates />`
- removed boolean parameter from `renderRateNotice()`
- change `renderTitle` to `getTitle`
=> Update <ShippingRates />

classes/class-wc-connect-shipping-label.php, tests/php/bootstrap.php, tests/php/test_class-wc-connect-shipping-label.php
Add unit test coverage for https://github.com/Automattic/woocommerce-services/pull/1024.
=> Add test coverage for PR #1024.

classes/class-wc-rest-connect-tos-controller.php, woocommerce-services.php
Related to #1107
This adds a REST endpoint that accepts the TOS when called. Calypso will call it on initial store setup.
I tested it with Postman.
=> Added REST endpoint for accepting TOS

.travis.yml
See: https://docs.travis-ci.com/user/reference/overview/ and https://github.com/travis-ci/travis-ci/issues/2963
=> Update travis-ci config to use Ubuntu Precise machines for PHP 5.2 and 5.3.

client/api/request.js
Fixes #1090.
In researching options, I found the fix. 😛
=> Add support for plain permalinks.

classes/class-wc-connect-api-client.php, classes/class-wc-connect-stripe.php, classes/class-wc-rest-connect-stripe-account-controller.php
Fixes #1125 
<del>Note: Testing requires server PR 987 to be merged to 975 first.</del>
To test:
- See "old test instructions" in comment on 987
=> Stripe Connect: Add endpoint that fetches connected account details from server

classes/class-wc-connect-api-client.php, classes/class-wc-connect-stripe.php, classes/class-wc-rest-connect-stripe-deauthorize-controller.php, woocommerce-services.php
Fixes #1164 
Note: Testing requires server PR 985 to be merged to 975 first.
To test:
- See "old test instructions" in comment on 985
=> Stripe: Connect: Add deauthorize REST API endpoint

classes/class-wc-connect-taxjar-integration.php
Fixes: #1223.
See: https://github.com/taxjar/taxjar-woocommerce-plugin/pull/40
=> Bring TaxJar’s 3.2 compatibility fix into WCS automated tax module.

classes/class-wc-rest-connect-shipping-label-controller.php
It was being ignored by the server anyway.
=> Remove the "ship_date" parameter from the purchase label request

classes/class-wc-connect-taxjar-integration.php
Fixes #1227.
_Note: I'm not sure how much we need/want to review these changes since they come right from TaxJar._
To review - compare each commit with the linked diff.
=> Port TaxJar 3.2 compatibility changes

assets/stylesheets/style.scss, client/apps/settings/components/settings-form/settings-group.js, client/apps/shipping-label/style.scss, client/components/action-buttons/index.js
Fixes the busy animation of the button when purchasing a label
To test:
* attempt to purchase a label
* the button should be animated
=> Fixed the label purchase button busy indicator

classes/class-wc-rest-connect-account-settings-controller.php
Related PR: https://github.com/Automattic/wp-calypso/pull/19514
Changed the `label settings` endpoint logic so any admin user is allowed to update the settings.
If the user is not the `Jetpack master user`, then the payment setting won't be updated, but the rest of the settings will.
It also adds a flag to the `GET` endpoint (`can_edit_settings`) which will always be `true`. This is done so the Calypso UI can differentiate between versions of the endpoints:
* For previous versions, `can_edit_settings` will be `false`-y (`undefined`), so only the `Master` user will be able to update the settings.
* For versions that include the `can_edit_settings` flag in the `GET` response, it's safe to present the user with the `Settings` form, and only hide the "Payment" part of it if he's not the …
=> Allow changing label settings (except payment) to non-Master users

classes/class-wc-connect-taxjar-integration.php
See: https://github.com/taxjar/taxjar-woocommerce-plugin/blob/6b5f216/includes/class-wc-taxjar-integration.php
Includes:
* https://github.com/taxjar/taxjar-woocommerce-plugin/pull/32
* https://github.com/taxjar/taxjar-woocommerce-plugin/pull/35
* https://github.com/taxjar/taxjar-woocommerce-plugin/pull/43
* https://github.com/taxjar/taxjar-woocommerce-plugin/pull/47
* https://github.com/taxjar/taxjar-woocommerce-plugin/pull/55
=> Catch TaxJar integration up to latest master. (2017-12-29)

classes/class-wc-connect-shipping-method.php
The old format `usps:1:0` didn’t indicate the rate was from WCS, and isn’t uniquely identifiable for extensions like Conditional Shipping and Payments. The new format looks like: `wc_services_usps:1:pri_medium_flat_box_top`.
=> Use consistent naming for shipping rate ids used in cart.

classes/class-wc-connect-help-view.php, classes/class-wc-connect-logger.php, tests/php/test_woocommerce-connect-client.php, woocommerce-services.php
Separate log files by feature type - "taxes", "shipping", "payments", etc.
Display taxes, shipping, and generic logs on Status page.
=> Add feature separated logging

classes/class-wc-rest-connect-base-controller.php
Prompted by cache issues on the Pantheon hosting platform.
Employs Pantheon's recommended solution: https://pantheon.io/docs/cache-control/
To test:
* Load this code on Pantheon for most points 😛, but optionally hook in yourself like: https://github.com/pantheon-systems/WordPress/blob/master/wp-content/mu-plugins/pantheon/pantheon-page-cache.php#L278
* Verify that the `Cache-Control` header on all WCS API endpoints is `no-cache, must-revalidate, max-age=0`
=> Send a no-cache header for WCS REST API responses.

classes/class-wc-connect-taxjar-integration.php
Partially addresses the issue raised in #1367
With #1321, if automated taxes were already enabled, the plugin would not revert the options which could lead to confusion. Without #1321 the settings would only be reverted once after the automated taxes were enabled for the very first time.
To test:
* `git checkout 9db62961d280909e988b9357790e9e03f654fd21` (commit before #1321)
* change some settings on the tax page, such as set prices to include tax or calculate taxes  based on the store address
* enable automated taxes - if this is not a fresh install and automated taxes were enabled before, the settings should not revert
* if the settings reverted, just change them back to "wrong" values and save with a. taxes enabled
* `git checkout master`
* refresh the page - the controls should be …
=> Taxes - check and override tax settings if automated taxes are enabled

package.json, readme.txt, woocommerce-services.php
Updated the plugin version and changelog for 1.13.2 release
=> 1.13.2 - Updated the plugin version and changelog

npm-shrinkwrap.json, package.json
I've just made a smoke test of the shipping settings page, https://github.com/Automattic/wp-calypso/pull/25101 is solved.
The changes brought form Calypso are:
- https://github.com/Automattic/wp-calypso/pull/23658
- https://github.com/Automattic/wp-calypso/pull/24715
- https://github.com/Automattic/wp-calypso/pull/25101 (confirmed, it works)
=> Update Calypso dependency

assets/stylesheets/_components.scss, npm-shrinkwrap.json, package.json
Updates Calypso dependency version to include https://github.com/Automattic/woocommerce-services/issues/1326:
=> Update Calypso to 9d78dbb - bypass address verification.

classes/class-wc-rest-connect-account-settings-controller.php
Fixes #1208 
Test instructions in https://github.com/Automattic/wp-calypso/pull/25307
=> Add wpcom username of the master user to the label settings endpoint

npm-shrinkwrap.json, package.json, readme.txt
In this release:
* Add international destinations support to USPS label printing
* Fix bug with Shipping Label pointer dismissal when creating a label for the first time
* Fix z-index issue with purchased shipping label ellipsis menu components
* Prevent checkout with invalid ZIP code when using Automated Taxes
* Fix tax calculation with multiple line items sharing product tax class
* Display native tax tables for custom rates
* Add street-level accuracy for tax calculation
=> Release 1.16.0

assets/stylesheets/_colors.scss, assets/stylesheets/_components.scss, assets/stylesheets/style.scss, classes/class-wc-connect-stripe.php, classes/class-wc-rest-connect-stripe-account-controller.php, client/apps/stripe-connect-account/index.js, client/apps/stripe-connect-account/state/actions.js, client/apps/stripe-connect-account/style.scss, client/apps/stripe-connect-account/view-wrapper.js, client/main.js, woocommerce-services.php
Imports the connected account view from Calypso ([screenshot of original Calypso context](https://cloudup.com/c4X-8pqE1rT)). Changes contain some style tweaks to match appearance in Calypso as well as static design in p7bbVw-2dB-p2.
A page refresh is triggered after "Disconnect" so that the keys show up as cleared.
Example for a newly created account:
Implementation concern: in order to make the UI render here, I filtered the Stripe settings to add a title, the description for which was the container into which WooCommerce Services renders the React tree. This isn't ideal because:
- <s>We can't pass data since `data-args` is filtered out by `kses` so we have to fetch the account details on first render even if we're fetching them earlier (and a small change to `main.js` was necessary to …
=> Import connected account UI into Stripe settings

classes/class-wc-connect-nux.php
Don't show new users mentions of the "live rates" feature in the NUX/connection banner.
=> Remove “live rates” from NUX banner feature list.

package.json, readme.txt, woocommerce-services.php
=> Release 1.17.1

classes/class-wc-connect-error-notice.php
Fixes #1376.
This PR removes the display of the "An error occurred in WooCommerce Services" admin notice in the following scenarios (that I'm proposing are "unactionable"):
1. A request to a WCS endpoint (local to the store) fails (e.g. `/wc/v1/connect/*`)
1. A tax rate request fails
1. A shipping rate request fails
**To test:**
* Point your store to a locally running WCS server
* Keep the local server **off**
* Visit the cart page, with items in cart
* Verify that either the tax rate or shipping rates are unable to be fetched (or both)
* Verify that no admin notice appears in the dashboard
* Verify that the failures are still logged on the Status page
=> Don't show admin notice for "unactionable" events

npm-shrinkwrap.json, package.json
As @allendav mentioned in #1567, the webpack Dev Server package got a CORS fix in `3.1.11`. 
I have updated it, along with all other dependencies. Everything looks fine after a quick smoke test.
Fixes #1567
=> Updated the `webpack-dev-server` dependency

.travis.yml, npm-shrinkwrap.json, package.json, readme.txt, woocommerce-services.php
- add changelog
- update WP compatibility to 5.2
- test PHP5.2 with WP5.1 instead of latest
=> Update to version 1.21.0

classes/class-wc-connect-jetpack.php, classes/class-wc-connect-tracks.php
Fixes #1633 
To test:
* Install Jetpack 7.4 installed and test that no notices are given when connecting the site
* Install Jetpack 7.5 and test that no notices are given when connecting the site
=> Support namespaced Jetpack tracking methods

client/extensions/woocommerce/woocommerce-services/views/packages/index.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/index.js
=> Change 'Packages' to 'Packaging'

webpack.config.js, woocommerce-services.php
=> Change the way css is loaded on the admin

client/apps/shipping-label/view-wrapper-label.js
=> Fix props validation error

client/apps/shipping-label/view-wrapper-label.js
Fixes #1663 
Ensure string detects singular and plural when needed.
=> Add single form of string when needed closes #1663

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/purchase-button.js
Fixes #1679. 
Some explanation https://github.com/Automattic/woocommerce-services/issues/1679#issuecomment-535113933
=> These props are not really required

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/sidebar.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-reprint-modal.js
=> Remove redundant Paper size dropdown

client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/add-credit-card-button.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/index.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/purchase-button.js
=> Buy shipping labels button logic tweak

classes/class-wc-connect-api-client-live.php, classes/class-wc-connect-api-client.php, tests/php/class-wc-connect-api-client-local-test-mock.php, woocommerce-services.php
- Define constants:
```php
define( 'WOOCOMMERCE_SERVICES_LOCAL_TEST_MODE', true );
define( 'JETPACK_DEV_DEBUG', true )
```
=> [WiP] Adding hardcoded mock data for rates and credit card.

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-reprint-modal.js
=> Remove unnecessary prop

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/list.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/shipping-rate.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss
Fixes https://github.com/Automattic/woocommerce-connect-server/issues/1303.
=> Include labels for tracking and delivery days

classes/class-wc-rest-connect-account-settings-controller.php, classes/class-wc-rest-connect-shipping-label-controller.php, client/extensions/woocommerce/woocommerce-services/state/label-settings/actions.js, client/extensions/woocommerce/woocommerce-services/state/label-settings/reducer.js, client/extensions/woocommerce/woocommerce-services/state/label-settings/selectors.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js
=> Preselect last used package

client/main.js
Fixes #1741 
TEST:
* Click on "Create Shipping Label" or "Track Packages" button. Check and ensure JS console does not generate error shown in #1741
=> Set appElement for the modal to prevent accessability error fixes #1741

client/apps/shipping-label/style.scss, client/apps/shipping-label/view-wrapper-label.js, client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js
Closes #1740 
Test:
* Go to the order.
* At the top check and make sure the button loader is present before showing "Create Shipping Label" button.
* Also test the same scenario after adding a package to the order. This time make sure the button loader is present before the "Track Package" button.
=> Hide button until we can determine which button to show closes #1740

client/apps/shipping-settings/view-wrapper.js, client/extensions/woocommerce/app/settings/shipping/save-button.js, client/extensions/woocommerce/state/data-layer/ui/woocommerce-services/index.js, client/extensions/woocommerce/woocommerce-services/state/actions.js, client/extensions/woocommerce/woocommerce-services/views/packages/package-dialog.js
=> Remove validation from PackageDialog

.travis.yml, readme.txt, tests/php/test_class-wc-connect-api-client.php, tests/php/test_wc-connect-services-validator.php, woocommerce-services.php
Closes #1730
Tested WP 5.3 and WC 3.8. Found no compatibility issues. Although there seem to be other unrelated issues we will address separately.
=> Bump tested version.

classes/class-wc-connect-shipping-label.php, woocommerce-services.php
=> Display notices when base country/currency mismatches

client/extensions/woocommerce/app/order/order-activity-log/event.js, client/extensions/woocommerce/app/order/order-activity-log/events.js, client/extensions/woocommerce/app/order/order-activity-log/index.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-item.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/tracking-modal/index.js
=> Remove ellipsis from tracking modal

package.json
=> Run `test-client` together with `test`

classes/class-wc-connect-shipping-label.php
=> Change logic to how items are counted

client/extensions/woocommerce/woocommerce-services/views/packages/package-dialog.js
=> Set duration to 5 secs for the PackageDialog notices

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/choose-credit-card-button.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/index.js
=> Add logic for 'Choose credit card' button

client/apps/shipping-label/style.scss, client/apps/shipping-label/view-wrapper-label.js
=> Update CSS for the buttons

classes/class-wc-connect-shipping-label.php, woocommerce-services.php
Fixes #1820.
This reverts the fix for #1751.
=> Revert adding WC notices

readme.txt
Adding myself as contributor. Feel free to add yours before merging. OR just put your .org handle here and I will add it in for you.
=> Add contributor

changelog.txt, client/apps/shipping-label/style.scss, client/apps/shipping-label/view-wrapper-label.js
=> Add redo fulfillment button.

changelog.txt, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/item-info.js
=> Use url from backend

changelog.txt, client/apps/shipping-label/style.scss, client/apps/shipping-label/view-wrapper-label.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/index.js, readme.txt
Cherry picks all commits from the following PRs:
- #1824
- #1844
- #1821
=> Hotfix for 1.22.2

readme.txt
Similar to https://github.com/Automattic/woocommerce-services/pull/1824
Adding myself as contributor. Feel free to add yours before merging. OR just put your .org handle here and I will add it in for you.
=> Add to contributors list

classes/class-wc-connect-api-client.php, woocommerce-services.php
Implement a heartbeat test to offload the connect server.
=> Add api heartbeat test.

changelog.txt, tests/php/test_woocommerce-connect-client.php, woocommerce-services.php
Closes #1873
Pretty much what is says in the title.
To test:
Deactivate WooCommerce
look for the notice
=> Show admin notice when WooCommerce is not found.

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/index.js
=> Fix typo in add credit card link.

.travis.yml
=> Remove tabs which cause so much problems

.travis.yml, client/apps/shipping-label/test/view-wrapper-label.js
Let's see if it works
Closes #1921
=> Run JS unit tests in travis

changelog.txt, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-item.js
closes #1905
Should work for Fedex too. Cause we'll get there soon.
=> Add option to open schedule pickup page for each carrier

woocommerce-services.php
Some suggestions which is easier to show in a PR.
=> always use get_wcs_version and cache version data for performance

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/test/shipping-rate.js
delivery_days should be a number
=> Fix prop type warning when running tests

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/test/shipping-rate.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/sidebar.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/test/sidebar.js
=> Fix broken fulfill order checkbox in sidebar

assets/stylesheets/_fix-image-paths.scss, webpack.config.js
we must set the publicPath is webpack config on dev so css urls are correct.
Also fixes a problem where CC images are not showing.
=> Fix svg images not showing on dev

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/shipping-rate.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss
=> Add tooltip to UPS accounts to indicate price is an estimate

npm-shrinkwrap.json
Closes https://github.com/Automattic/woocommerce-services/issues/2058
Update the shrinkwrap file by running `npm run update-deps`
1. pull this branch
2. run `npm ci`
3. create an order
4. try to print a label
5. everything should still work.
=> Update shrinkwrap respect to latest package.json

npm-shrinkwrap.json, package.json, tests/e2e-tests/fixtures/create-shipping-label.json, tests/e2e-tests/fixtures/index.js, tests/e2e-tests/jest-puppeteer.config.js, tests/e2e-tests/mocks/index.js, tests/e2e-tests/specs/admin/refund-label.test.js, tests/e2e-tests/utils/index.js
=> Add e2e test for labels refund

client/extensions/woocommerce/components/extended-header/style.scss, client/extensions/woocommerce/woocommerce-services/components/carrier-icon/style.scss, client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/index.js, client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/settings.js, client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/style.scss, client/extensions/woocommerce/woocommerce-services/views/label-settings/index.js, client/extensions/woocommerce/woocommerce-services/views/packages/index.js
Copy and style tweaks focused in settings and the carrier account form.
=> Copy and text style tweaks

changelog.txt, readme.txt
Closes #2076 
I did a `git log 1.23.2..develop.| grep Merge` to find all the PR that we did not add. I combine all UPS related issues into 1 changelog.
=> Update change log

client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js, client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-item.js
Fixes #2089 
Purchase new label with this checked:
Check order note:
Also adds a pickup link for UPS:
=> Update order detail note for UPS

readme.txt
Closes #2118 
Update WP tested up to version to 5.5.
=> Update WordPress tested up to 5.5

changelog.txt, readme.txt
Update readme and changelog for 1.24.1 release.
=> Update readme and changelog for 1.24.1 release

changelog.txt, npm-shrinkwrap.json, package.json, readme.txt, woocommerce-services.php
The changes here were introduced into `master` as part of the release process. I'm going to go ahead and merge without approval since this is trivial.
=> Merge back after 1.24.2 release.

changelog.txt, lint-staged.config.js, npm-shrinkwrap.json, package.json
This PR is the first step towards enforcing linting rules more closer towards WooCommerce standards.  https://github.com/woocommerce/woocommerce. Another repo example is https://github.com/woocommerce/woocommerce-admin/. 
To do that, we would like to do something similar to what WooCommerce and WooCommerce Admin are doing. Leveraging `husky` and `lint-staged` to enforce checks with git hooks. This PR adds `pre-commit` and `pre-push` git hooks so that we lint per commit based on our `.eslintrc` file. And run `npm run test` before we `git push`. 
This involves installing `husky` and `lint-staged`.
1. Create a new branch or pull this branch
2. Make some changes, `git add` the changes
3. `git commit`, you should see the following:
- Current WooCommerce Services' `.eslintrc` is not exactly the …
=> Add husky lint-staged for pre commit hooks

changelog.txt, npm-shrinkwrap.json, package.json, readme.txt, woocommerce-services.php
Merging 1.25.2 release changes back into develop branch.
=> Merge 1.25.2 master back into develop

changelog.txt, npm-shrinkwrap.json, package.json, readme.txt, woocommerce-services.php
Merging 1.25.3 release changes back into develop branch.
=> Merge 1.25.3 master back into develop

readme.txt
=> fix: readme.txt typo

changelog.txt, npm-shrinkwrap.json, package.json, readme.txt, woocommerce-services.php
=> Merge 1.25.5 master back into develop

changelog.txt, woocommerce-services.php
Update WC version to prevent warnings.
=> chore: update WC version

changelog.txt, npm-shrinkwrap.json, package.json, readme.txt, woocommerce-services.php
Updating `develop` with `master` after 1.25.6 release.
=> Update 1.25.6 release changes into `develop`

changelog.txt
Updating before I merge `master` release changes.
=> Update changelog entries on `develop`

changelog.txt, npm-shrinkwrap.json, package.json, readme.txt, woocommerce-services.php
Updating `develop` with `master` after 1.25.7 release.
=> Update 1.25.7 release changes into `develop`

changelog.txt, client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/ups-settings-form.test.js, client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/ups-settings-form.js, npm-shrinkwrap.json
Even if the [UPS documentation states that the invoice number only has digits](https://www.ups.com/us/en/help-center/sri/exp-pdf3.page#:~:text=An%20invoice%20number%20is%20a,a%20shipment%20for%20billing%20purposes.), we have customers [with invoices containing letters and numbers](https://github.com/Automattic/woocommerce-shipping-issues/issues/184).
This PR changes the regex on the UPS invoice number to allow for letters and numbers.
Closes #2296 
* With a user that has the flag enabling the UPS beta and WooCommerce Shipping and Taxes.
* Go to WooCommerce > Settings > Shipping > WooCommerce Shipping.
* Click on Connect next to UPS
* Fill in the fields
* Check the checkbox `I have been issued an invoice from UPS within the past 90 days`
* Enter an invoice number with 9 or 13 length, …
=> Make UPS Invoice field accept numbers and letters.

client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/carriers-list.js
As discussed in team meeting (and later on Slack `CKNC7KACA-p1615912171010900`) changing the copy on the discount amounts.
https://d.pr/i/R5Lumv
I didn't think a changelog entry is needed, since the whole paragraph hasn't been released yet and it's just a copy change
=> chore: update carrier discount amounts

.github/workflows/js_tests.yml, .github/workflows/php_tests.yml
Use `pull_request` instead of `push` to trigger event. This change should allow:
pull_request: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push
push: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
1. GitHub Action to run on PR that's made from forked repo
2. GitHub Action should run every time a new commit is pushed to the PR.
Closes https://github.com/Automattic/woocommerce-services/issues/2395
Make sure pipeline runs.
=> Use pull_request to run github actions instead of push

changelog.txt, classes/class-wc-connect-api-client-live.php, classes/class-wc-connect-options.php, classes/class-wc-connect-service-schemas-store.php, classes/class-wc-connect-shipping-method.php, classes/class-wc-connect-taxjar-integration.php, npm-shrinkwrap.json, package.json, readme.txt, tests/php/classes/test-class-wc-rest-connect-shipping-label-controller.php, woocommerce-services.php
Merging 1.25.10 release changes back into develop branch.
=> Merge master 1.25.10 back into develop
