Automattic/woocommerce-services

assets/stylesheets/style.scss
client/components/shipping/packages/style.scss

Cleaning up the Add a Package modal.
Before:
Small screen:
Larger screen:
After:
@jkudish or @jeffstieler for review.

Modals: Clean up layout

---

.gitignore
package.json
tasks/release.js

This PR seeks to add a new `npm run release` task that can be used to package up the plugin for future releases. It performs the following steps:
* Clear out the `release` folder from previous task completions
* Runs `npm run dist` to compile the plugin's Javascript files for production 
* Create `release/woocommerce-connect` with a copy of the plugin's markdown files, php files and the compiled js
* Zip that folder up
This produces a final `release` folder (which is git ignored) with the plugin files as a folder and as a zip ready for distribution.
To test:
* Run `npm run release` -- verify that you get a warning about needing to `npm install`
* Run `npm install`
* Run `npm run release` -- at the prompt, type `no` or something else that's not `yes` -- verify that …

Add release npm task

---

classes/class-wc-connect-shipping-method.php
tests/php/test_class-wc-connect-shipping-method.php

Fixes #222.
Only Country, State, and Postcode are sent from the Cart page.
To test:
* Check out https://github.com/Automattic/woocommerce-connect-server/tree/fix/247-fetch-rates-without-city-or-address and start local server
* Add item to cart
* View cart
* Click "calculate shipping"
* Enter valid Country/State/Postcode combo
* Verify rates are displayed

City isn’t required to get a shipping quote.

---

client/components/shipping/packages/add-package.js

Fixes #285.
To test:
* Open "add package" dialog
* Enter values for name and dimensions
* Change package type from "Box" to "Envelope"
* Verify that your entered values remain

Don’t clear package name, weights, or dimensions when toggling package type.

---

classes/class-wc-connect-shipping-method.php
tests/php/test_class-wc-connect-shipping-method.php
tests/php/test_wc-connect-services-validator.php
tests/php/test_woocommerce-connect-client.php

Fixes #193.
To test:
* Add a new USPS shipping instance to a zone and do not enter any settings for it
* Add an item to cart and attempt a checkout (that would fall under the above zone)
* Verify that a "Service settings empty." warning is logged

Don't request rates if settings are empty.

---

client/components/shipping/packages/packages-list-item.js

Fixes: https://github.com/Automattic/woocommerce-connect-client/issues/308 and partially: https://github.com/Automattic/woocommerce-connect-client/issues/310
Adding an href to the package name link so it gets all the special link properties that it deserves.
Before:
After:

Package name: add href

---

assets/stylesheets/components/foldable-card/style.scss

Fixes: https://github.com/Automattic/woocommerce-connect-client/issues/309
Adds focus style on the chevron:
Accessibility ftw

Foldable card chevron: add focus style

---

classes/class-wc-connect-tracks.php
tests/php/mocks/jetpack.php
tests/php/test_woocommerce-connect-tracks.php
woocommerce-connect-client.php

This PR seeks to introduce integrations with the Automattic Tracks metrics system. Specifically it:
* Adds a new Tracks class, and integrates it into our plugin
* Uses Jetpack's existing tracks integration to record events
* Adds the first two events which track opting in and opting out of WooCommerce Connect (activating/deactivating the plugin -- we'll need to adjust that when we merge into WC Core, noted for #131)
* Adds phpunit tests accordinglt
To test:
* You'll need a site that is actually connected via Jetpack, no fakes (but localhost works as long as it was once connected)
* Run phpunit tests -- make sure they pass
* Deactivate the WooCommerce Connect plugin, verify that the following is added to your debug file:
`Tracked the following event: …

Add tracks integration

---

client/components/shipping/packages/packages-list-item.js

To test: Try editing an existing package. Before the fix it should scroll up, after it should not.
@kellychoffman @jkudish @allendav @jeffstieler

PreventDefault so that the click doesn't cause a scroll up on the page

---

classes/class-wc-connect-help-provider.php
tests/php/test_woocommerce-connect-client.php
woocommerce-connect-client.php

Ready for review
<del>Requires https://github.com/woothemes/woocommerce/pull/10874<del>
Completes the first item in https://github.com/Automattic/woocommerce-connect-client/issues/153#issuecomment-217036409
To test:
Navigate to wp-admin > WooCommerce > System Status
Verify you get a Connect tab now
Click on it
Verify you get the Health, Services, Debug and Support sections (currently empty - content comes in successive PRs)
cc @jkudish @nabsul @jeffstieler for review

Start building out the stateful status page

---

client/components/shipping/packages/style.scss

Clean up the packages UI. Fixes the rest of https://github.com/Automattic/woocommerce-connect-client/issues/310 ( I don't want to wait for Calypso and I think we should add an outline here)
Before:
After:
- Lots of alignment tweaks, including small screen
- Allows for up to 3 decimal point dimensions without breaking on to another line (large screen view)
- Changes to package type icon: alignment, color, stylesheet cleanup
- Correct cursor type
- Focus outline for removing a package

Packages: Clean up ui

---

client/components/wcc-settings-form/settings-item.js

This fixes #327 
To test: 
* make sure that required fields (title/origin) continue to show a validation error if left empty. 
* ensure no regressions are introduced
cc @allendav

Check that schema.required exists before using it

---

client/components/text-field/index.js

Fixes #328 
To test:
* Hack a local server to remove a description, e.g. /lib/shipping/usps/service-settings.js service_settings.properties.title.description
* Refresh the client, receiving the new schema
* Ensure the TextField renders (albeit without a description now)

Make description optional for TextFields

---

woocommerce-connect-client.php

This PR ensures that our daily event is cleared when the WC Connect plugin is de-activated. Fixes #337
To test:
* Easiest to do this with a site where you can access `wp-cli`
* Make sure WC Connect is activated and `WOOCOMMERCE_CONNECT_FREQUENT_FETCH` is NOT set
* Run `wp cron event list`, and verify that `wc_connect_fetch_service_schemas` is in the list of future events
* De-activate WC Connect
* Run `wp cron event list`, and verify that `wc_connect_fetch_service_schemas` is no longer in the list of future events
* Re-activate WC Connect
* Run `wp cron event list`, and verify that `wc_connect_fetch_service_schemas` is once again in the list of future events
cc @allendav @nabsul @jeffstieler

Clear event hook on plugin de-activation

---

assets/stylesheets/components/foldable-card/style.scss

Quick PR to fix the wrapping issues of the foldable card description on smaller screens. 
Before:
After:
@allendav for review

Foldable card description: fix line wrapping

---

classes/class-wc-connect-tracks.php
tests/php/test_class-wc-connect-shipping-method.php
tests/php/test_woocommerce-connect-client.php
tests/php/test_woocommerce-connect-tracks.php
woocommerce-connect-client.php

This PR seeks to:
* Add a function to check if a given shipping method (via it's `method_id`) is a WCC method
* Add hooks into WooCommerce's hooks for shipping method actions
(added/deleted/enabled/disabled -- see https://github.com/woothemes/woocommerce/pull/10891) and check if the shipping method the action occured on is a WCC method. If so, it then triggers another hook
that is WCC specific.
* Add tracks integration for shipping method actions (added/deleted/enabled/disabled) based on the hooks described above)
* Add several new tests and introduce some php testing improvements, specifically, this revises some test suite files to restrict their loading of WCC files, which serves multiple purposes:
1) speed things up (30s down to under 5s per test run)
2) avoid unexpected test side …

Add tracks integration for shipping method actions

---

client/components/shipping/packages/add-package-presets.js
client/components/shipping/packages/add-package.js

Not all shipping methods will have preset packages. This change makes it optional.
To test: 
- Edit the server by deleting the preset_boxes from the definitions. 
- Make sure the UI component properly only shows the box and envelope option
@jkudish @allendav @jeffstieler

Make package presets optional

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-shipping-method.php

* Add a new last_rate_request timestamp bumped whenever there's a shipping rate request (at most once an hour though to prevent too many writes)
* Send `0` as the fallback timestamp instead of `false`
Can only be merged after https://github.com/Automattic/woocommerce-connect-server/pull/266 is merged. See that PR for testing instructions
Fixes https://github.com/Automattic/woocommerce-connect-client/issues/216

Timestamp setting updates

---

assets/stylesheets/_components.scss
assets/stylesheets/style.scss
client/components/save-form/index.js
client/components/wcc-settings-form/index.js
client/components/wcc-settings-form/settings-group.js
client/lib/calypso-boot/index.js
client/lib/mixins/i18n/index.js
client/main.js
client/state/index.js
npm-shrinkwrap.json

This PR seeks to replace the existing inline save/error notices and add global notices instead. It re-uses the Calypso `GlobalNotices` component and the associated state tree (reducer/actions). In order to get that to work properly, this PR also introduces some changes to the i18n boot/mixin system so that it works with `this.translate` in Calypso components properly.
Success:
Error:
In addition, this PR upgrades Calypso and all its sub-dependencies to their latest versions, by upgrading our `npm-shrinkwrap.json`
To test:
* Option one is to just run `npm install`, in theory npm should do a good job of just upgrading what it needs to. Option two is to delete the `node_modules` folder and `npm cache clean && npm install`.
* Checkout this PR
* Ensure everything compiles as expected with `npm …

Add global notices

---

client/components/shipping/packages/add-package.js
client/state/form/packages/reducer.js
client/state/form/packages/test/reducer.js

Fixes #325 and #346.
To test:
_#325_
* Click "add package" to open modal
* Toggle package type to "envelope"
* Toggle package type back to "box"
* Fill all fields *except for outer dimensions*
* Click "add package" to save new package
* Click "save changes"
* Verify that no errors are returned for `outer_dimensions`
_#346_
* Click "add package" to open modal
* Choose a preset package
* Click "add package" to save new package
* Click "add package" to open modal again
* Verify that the default "box" is selected as type, all fields are empty an *not* read only

Fix "add package" modal state issues. 

---

package.json
webpack.config.js
webpack.test.config.js

This PR seeks to simplify the test webpack config so that it inherits from the main one instead and adds the only required change (node externals) by extending that base config. This helps us reduce duplication and make future maintenance easier.
In addition, this PR:
* Remove `npm run lint` from `npm test` command since webpack runs the linter already
* Remove nodeExternals require from base webpack config. It wasn't used.
To test:
* Make sure tests pass `npm run test`
* Make sure things compile correctly `npm start` and `npm run dist`
Fixes #278

Update webpack config

---

client/components/shipping/packages/add-package.js

closes #311 
Adds the dimension unit at the end of (LxWxH) in the add-package modal.
To test: Open the modal. 
@kellychoffman @allendav @jkudish @jeffstieler

Add unit measurements for the L x W x H label displayed in modal

---

client/components/shipping/services/entry.js
client/components/shipping/services/group.js

This provides a more natural experience to a user that might be typing a decimal number, or who accidentally enters a non-digit character.
Fixes #188.
**Note: test with a USPS instance, there is currently a bug with Canada Post showing errors on service fields.**
To test:
* Enter the value `a` into a service adjustment input
* Verify that the input is marked with an error icon, and the "save changes" button is disabled
* Clear the input
* Verify that the input is marked with an error icon, and the "save changes" button is disabled
* Enter `1`
* Verify that the input is **not** marked with an error icon, and the "save changes" button is **enabled**
* Enter `1.`
* Verify that the input is marked with an error icon, and the "save changes" button is disabled
* Enter `1.1`
* Verify that the …

Allow non-float values to be entered into service adjustment inputs.

---

client/components/wcc-settings-form/index.js
client/components/wcc-settings-form/settings-group.js
client/components/wcc-settings-form/settings-item.js

closes #361 
This change hides the packing method radio buttons when there are no boxes defined. The reason is that this parameter has no effect on settings unless there is at least one package defined in packages.
I also went ahead and did some cleanup to the React component:
- redux `connect()` is now only done once in index.js
- Update proptypes to properly reflect properties used by the subcomponents`
To Test:
1) Go to settings page (Canada Post or USPS)
2) Observer that the radio buttons are hidden if there are no packages defined
3) Try saving, refreshing the page, and cancelling a few actions
4) Make sure unit tests pass and no errors are thrown in the console.
Here are sample images of what you should see:

hide packing method when there are no packages

---

client/components/wcc-settings-form/index.js
client/lib/save-form/index.js
client/state/form/reducer.js
client/state/form/test/reducer.js

This overrides the calculated client errors with values from state (which are from the server).
This PR seeks to display errors returned from the server inline on the client form.
It changes the form state `error` property to `errors` and sets the value to the array returned by the server during validation failure.
The form component's error property now defaults to this `form.errors` state, falling back to any calculated client-side errors if none are found in state.
Upon interacting with the form and causing a `state.settings` update, the `form.errors` state is cleared, allowing client-side validation to take over.
To test:
- Use this testing branch of the server (forces "title" to error) https://github.com/Automattic/woocommerce-connect-server/tree/test/205-server-errors-on-client
- …

Show errors from the server inline.

---

woocommerce-connect-client.php

closes #261 
If settings any woo commerce settings are changed, we should re-fetch settings from the server. This is because the default values and settings will change if for example the units of measurements are changed.
To Test:
- Load this branch
- Enable logging
- Make sure your frequent fetch flag is NOT enabled
- Save your woocommerce settings (you don't need to change the settings)
- Observer that a `fetch_service_schemas_from_connect_server` event is logged in the logs
@allendav @jkudish @jeffstieler @DanReyLop

Add hook to update schemas when woocommerce settings are updated

---

assets/stylesheets/style.scss

Fixes: #363 
Before:
After:
To test, open the Add a package modal and resize your browser so the height is small. The action buttons should still display. 
The caveat here is that the height will be long if you have a tall browser. I think thats fine. I didn't want to restrict the height because some modals will be long, and this modal in particular has two different heights depending if the exterior dimensions are present.

Dialog card: Always display action buttons even on short screens

---

assets/stylesheets/shipping-services.scss
client/components/shipping/services/entry.js
client/components/shipping/services/group.js

closes #198 
This adds a "select-all" checkbox in the header of the service foldable card, like so:
To Test: Check out his branch and try some of the following scenarios:
- Check-all when none/some/all services are already checked
- Un-check-all
- Saving the form and making sure the check-all renders correctly upon initialization
@DanReyLop @jeffstieler @jkudish @allendav @kellychoffman

Add select all in services selection

---

assets/stylesheets/style.scss
client/components/shipping/packages/add-package-presets.js
client/components/shipping/packages/add-package.js
client/components/shipping/packages/input-filters.js
client/components/shipping/packages/modal-errors.js
client/components/shipping/packages/style.scss
client/components/wcc-settings-form/settings-item.js
client/lib/initialize-state/index.js
client/state/form/packages/actions.js
client/state/form/packages/reducer.js
client/state/form/packages/test/actions.js
client/state/form/packages/test/reducer.js

I've added validation to the add/edit packages modal. It does the following:
1) Check if name field is empty 
2) Check if box name already exists in the list of boxes
3) requires inner dimensions and checks the format
4) if outer dimensions are provided, checks the format
5) makes sure box and max weights are numbers and not empty
6) Auto-correct spacing around "x" in the dimensions definitions
To Test:
1) Open USPS or Canada Post settings
2) Make sure you have a few boxes entered
3) Try to add a new box
4) Make sure it follows all the rules above
5) Try editing an existing box
6) Make sure it follows the rules above
7) Make sure you're able to save data after making changes
8) Experiment with variations of spacing around the "x" in the dimensions. It should be auto-corrected. …

Add validation inside the add/edit packages Modal

---

assets/stylesheets/style.scss
classes/class-wc-connect-shipping-method.php

This PR seeks to add a fallback message that appears (via a css animation) on the shipping settings form if the form hasn't rendered within 3 seconds. The message prompts the user to visit
the debug page to find some troubleshooting steps.
The easiest way to test it is to apply the following diff to `client/main.js`:
```
diff --git a/client/main.js b/client/main.js
index daa853c..d2bc95f 100644
--- a/client/main.js
+++ b/client/main.js
@@ -27,7 +27,7 @@ let render = () => {
const WCCShippingSettings = require( 'views/shipping' );
ReactDOM.render(
<Provider store={ store }>
-                       <WCCShippingSettings
+                       <WCCShippingSetting
storeOptions={ storeOptions }
schema={ formSchema }
layout={ formLayout }
@@ -54,7 +54,7 @@ if ( module.hot ) {
try {
renderApp(); …
```

Add fallback message on shipping settings page

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-help-provider.php

Solves #336
When the site is a Jetpack staging site (```Jetpack::is_staging_site()``` returns ```true```), the requests sent to the WCC server will have a flag to prevent stats to be bumped for the site.
Also, a notice in the health page will be displayed.
I'm not sure how to test this, since I don't know how to put a site in "staging" mode, I just put a ```return true;``` at the start of ```Jetpack::is_staging_site()``` and check that the notice on the Health page is shown, and that all the requests that the client sends to the WCC server have ```settings.enable_stats = false```.
@jeffstieler @allendav @nabsul

Disable bumping stats when the site is a Jetpack staging site

---

client/components/wcc-settings-form/index.js
client/lib/save-form/index.js

This PR seeks to improve the catching of errors on the client. Specifically, it adds support for errors returned from the WP-API endpoint as strings, such as problems with communicating with
the server and other errors that are returned directly from that endpoint. This makes sure these errors do not produce a javascript warning and output the error as a notice.
To test:
* `npm start`
* Define `define( 'WOOCOMMERCE_CONNECT_SERVER_URL', ' https://fake.url' );` in your `wp-config.php`
* Attempt to save settings. Verify that you get the following (and no javascript errors):
Fixes #386
cc @allendav @nabsul @DanReyLop @jeffstieler

Improved error handling

---

package.json
webpack.production.config.js

Production builds weren't minifying the Javascript properly. It was because in the development webpack config it was specified that modules were contatenated using `eval` calls, and that couldn't be minified, since the entire modules were strings.
I've also cleaned-up the webpack production config file, it was way more complex than it needs to be, I'm not sure if it was an historical reason for that.
To test this, just run `npm run dist`, check that the JS is now less than 500KB, and try to use the client in "production" mode (without the Webpack dev server).
cc @allendav @nabsul @jkudish @jeffstieler

Enables Javascript minification in production builds

---

classes/class-wc-connect-service-settings-store.php
client/components/shipping/packages/style.scss

Closes #359 
This will provide the WooCommerce translation of dimension and weight units.
To Test:
- Switch your site language to French (not all languages have translations of the units, French does)
- See that the new unit names are displayed in the box packer settings of USPS and CanadaPost
@jeffstieler @allendav @jkudish @DanReyLop

Translate measurement units

---

client/components/shipping/services/entry.js
client/components/shipping/services/number-input.js

Fixes #381 
This is not an ideal solution. The input will only be validated when ```onBlur``` is fired, and the input value won't be reformatted, so the user can submit for example "04.10", the server will receive "4.1", but that change won't be reflected on the form until the user refreshes the page.
To test it, simply go to the USPS form, select one rate and type a value like "2.05" or "invalid123" into the "Adjustment" field.
To make this work flawlesly, the ```ShippingServiceEntry``` component (or a sub-component) would need to have state (and since our tree is fully stateless right now, that would be a bummer). Tell me if you want me to go that way, or if this solution is good enough.
@nabsul @jkudish @allendav @jeffstieler

Fix rate adjustment input fields so they let the user write floats like "2.05"

---

assets/stylesheets/shipping-services.scss
client/components/shipping/services/index.js
client/components/wcc-settings-form/settings-item.js

Allows the Services entire fieldset to have an error state as a whole (not only for sub-fields), and a ```validation_hint```.
Server-side PR: https://github.com/Automattic/woocommerce-connect-server/pull/301
How to test: You will to update your server to https://github.com/Automattic/woocommerce-connect-server/pull/301 , after that just go to configure a USPS provider and leave all the Services unchecked. After you submit the changes you should see an error in the Service fieldset.
cc/ @allendav @nabsul @jeffstieler 
cc/ @kellychoffman if you want to tweak the design for the error field

Added the possibility to display a validation error on the Services fieldset

---

assets/stylesheets/shipping-services.scss
client/components/shipping/services/index.js
client/components/wcc-settings-form/settings-item.js

Fixes #404 
To test this, just go to the settings page of USPS or Canada Post, you should see that now the Services component has a title and a description, like in this screenshot:
@allendav @nabsul @kellychoffman

Added the possibility to display a title and a description for the "Services" field

---

classes/class-wc-connect-shipping-method.php

Fixes #403 
To test, change
```
<div id="wc-connect-admin-container">
```
to
```
<div id="wc-connect-admin-ponies">
```
and
```
<span class="form-troubles" style="opacity: 0">
```
to
```
<span class="form-troubles" style="opacity: 1">
```
So you can see the message and click the link.

wp_kses the placeholder

---

client/components/wcc-settings-form/index.js
client/lib/initialize-state/index.js
client/state/selectors.js
npm-shrinkwrap.json
package.json

In my ongoing quest to move as much logic as possible from the components to the Redux tree, I've moved the calculation of the form errors to a selector.
I'm working on moving the `formSchema` and `formLayout` to the Redux tree, to have most (if not all) of the complex logic needed for a multi-step form encapsulated in the reducers. If you have any objection about that better say it as soon as possible :)
@allendav @nabsul @jeffstieler

Moved the form errors calculation to a selector

---

client/components/wcc-settings-form/index.js
client/main.js
client/state/index.js
client/state/settings/actions.js
client/views/shipping/index.js
npm-shrinkwrap.json
package.json

In my series of "move everything possible away from the components" PRs, this is the last one :)
Instead of having the Settings component configure the `saveForm` logic and attaching all the callbacks, it's now done in the "Redux backend", using redux-thunk.
In last week's Calypso meeting `redux-thunk` was discussed (and quickly dismissed) as an approoach to async actions such as this one. Let's see if it can work for our case :)
@nabsul @jeffstieler @allendav

Moved the save form logic to a Redux action, using redux-thunk

---

classes/class-wc-connect-help-provider.php
client/components/text/index.js

This is the last piece of #153 - it adds a pair of support links to the bottom of the self-help page.
I've gone ahead and opened a new issue ( #419 ) for when we can do something more magical with https://woothemes.com/my-account/create-a-ticket/
To test, open self-help (wp-admin > WooCommerce > System Status > WooCommerce Connect), scroll to the bottom and voila - support links :P

Add basic support links

---

client/components/wcc-settings-form/index.js
client/lib/initialize-state/index.js
client/state/selectors.js

Follow-up from #416 
As discussed, the Redux tree shouldn't have the form schema, so I rewrote the `getFormErrors` selector so it gets the schema from the component's `props` instead of from the state.
@jeffstieler

Removed form schema from the Redux state tree

---

tasks/release.js

Fixes #421 
To test:
Clear out the release subfolder if it exists
Run npm run release
Take the resulting zip and upload it via wp-admin > Plugins > Add New > Upload
Activate the plugin and, after activating it, navigate to wp-admin > Plugins again
Verify no required file missing errors occur

Add the i18n folder to the build list

---

client/components/shipping/packages/packages-list-item.js
npm-shrinkwrap.json

Fixes: https://github.com/Automattic/woocommerce-connect-client/issues/379
We were temporarily using an image icon for box packages. This updates to use an actual box. 
To test:
* npm cache clear
* rm -rf node_modules/
* npm install
* npm start
* Go to the instance page for a service instance and add a box. Make sure you get a box icon, e.g.:

Packages: Update box icon to `product` gridicon

---

classes/class-wc-connect-shipping-label.php
classes/class-wc-rest-connect-shipping-label-controller.php
client/components/wcc-settings-form/index.js
client/lib/save-form/index.js
client/main.js
client/state/form/actions.js
client/state/form/reducer.js
client/state/form/shipping-label/actions.js
client/state/selectors.js
woocommerce-connect-client.php

This PR builds on #428 , I've separated it into a new PR to ease the code review.
This PR includes logic to:
* Disable the "Next" button when the current form step has errors.
* Automatically advance the flow until a step with errors is reached.
* For auto-advance purposes, validate client-side, and then server-side only if the client-side validation succeded. Note that the server can say that there are errors, but if they are in future steps the form must auto-advance.
I've created a silly REST endpoint mock, it has these rules:
* It will fail an address if the address line 1 isn't `Hawk St`.
* It will always fail the `Packaging` step (because from that step onward, it's uncharted lands).
So you can just play with it. If you create an order with destination to `Hawk St`, you will be able …

Multi-step form auto-advancing logic and validation

---

client/components/shipping/packages/modal-errors.js
client/state/selectors.js

This makes each form validation to take about 1ms. Before, in my machine,
it took between 10 and 15ms.
Fixes #443 
Turns out, the **mayor** lag I was noticing was caused by React validating PropTypes, and so it doesn't happen in release builds. Still, trying to fix it I run across this optimisation (caching the `is-my-json-valid` validator).
@jeffstieler @allendav @nabsul

Improved the performance of form validation by caching the validator.

---

client/components/shipping/services/group.js

State value paths should be arrays, not strings.
Fixes #441.

Fix “select all” checkbox in service groups.

---

classes/class-wc-connect-shipping-label.php
client/components/country-dropdown/index.js
client/components/dropdown/index.js
client/components/indicators/index.js
client/components/number-field/index.js
client/components/radio-buttons/index.js
client/components/state-dropdown/index.js
client/components/text-area/index.js
client/components/text-field/index.js
client/components/text/index.js
client/components/toggle/index.js
client/components/wcc-settings-form/settings-group.js
client/components/wcc-settings-form/settings-item.js
client/main.js
client/views/shipping/index.js

Fixes #435
See #442 
This PR has the exact same code that #442, but the destination branch is `master`. Apparently you can't change the destination branch of an existing PR, so there you go, new one.
In this PR:
* Put the real, localized strings of the Address steps
* Implemented the country and state selectors
* Got the address form(s) ready for design
To test this, just go to a pending WooCommerce order with a physical product and click the "Create Label" button.
We have 3 different cases for the State selector:
* There are countries with States, and WooCommerce has a list of them. Example: US, Spain
* Some countries have states (or an equivalent concept) but WoCommerce doesn't have a list of them. In that case, a text field is displayed instead of a dropdown. Example: UK
* Some …

[Labels] Address form

---

classes/class-wc-connect-service-settings-store.php
classes/class-wc-connect-shipping-label.php
classes/class-wc-rest-connect-shipping-label-controller.php
woocommerce-connect-client.php

Fixes #434 
See #450 
This PR has the exact same code that #450, but the destination branch is `master`. Apparently you can't change the destination branch of an existing PR, so there you go, new one.
To test it:
* Open the label printing dialog.
* Input a complete origin address.
* Click the "Next" button.
* Reload the page and open the label printing dialog again.
The second time you open the label printing dialog, the Origin step should be pre-filled, and if it's "valid" for the server (remember, only `Hawk St` addresses are acceptable for now) it will auto-skip the step entirely.
Ideally, the merchant address should only be "remembered" if it was used to actually purchase a label, but since the integration between the merchant host and the WCC server isn't implemented yet, that's not …

Store the merchant address so it's prefilled the next times the label printing dialog is opened

---

.eslintrc.js
classes/class-wc-connect-api-client.php
classes/class-wc-connect-shipping-label.php
classes/class-wc-connect-shipping-method.php
client/components/indicators/index.js
client/components/order-packages/index.js
client/components/shopping-cart/index.js
client/components/state-dropdown/index.js
client/components/text/index.js
client/components/wcc-settings-form/settings-item.js
woocommerce-connect-client.php

Fixes #445 
Things to consider:
* The UI is very crude. I just made a few loops with plain `<ul>` and `<li>` tags.
* Since everything you see in the Packaging step is already valid, that step is skipped by default. So after the address steps you will appear in a (not implemented) Rates step. You can go back clicking the "Packages" link at the top. If we decide that the last step will have a summary of everything, I think this behaviour is fine. Anyway, we can change our minds later.
* If there is no information in the order `meta` about packaging (for example, if the user selected Free Shipping, or the order was placed using the code in the current `master` branch), then all the items will be packed individually (not a perfect fallback, but a fallback).
* All the relevant information …

[Labels] Packaging step

---

assets/stylesheets/style.scss
client/components/shipping/packages/style.scss
package.json
webpack.config.js

Fixes #468 
We had already installed `autoprefixer` as a dependency, but for some reason it wasn't integrated into the Webpack build :)
The easiest way to test is:
* Don't forget to do `npm install` and re-start the build script.
* Go to a Canada Post settings configuration page, and remove the amount in the "Fallback Rate" field.
* If the placeholder (`Rate amount`) appears in light gray, then autoprefixer is working.
* If the placeholder appears in darker gray, then it's not working.
This is because the `::placeholder` pseudo-class is not standarized even in modern browsers, so if the vendor-prefixed versions aren't generated, the styling for that pseudo-class (make it lighter gray) is ignored.
Good:
Bad:
@allendav @jeffstieler

Add autoprefixer to the Webpack build

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-shipping-label.php
client/components/dropdown/index.js
client/components/order-packages/index.js
client/components/shipping-rates/index.js
client/components/wcc-settings-form/settings-item.js
client/lib/save-form/index.js
client/lib/utils/coerce-values.js
client/state/form/actions.js
client/state/form/auto-advance.js
client/state/form/reducer.js
client/state/form/test/reducer.js
client/state/form/values/actions.js
client/state/form/values/reducer.js
client/state/selectors/errors.js
vendor/class-wp-rest-controller.php

Fixes #452 
As usual, crude UI and everything mocked in the server, but only 1 more step to go!
For the UI of that step, I did a simple loop over all the packages in the order, and for each one, show the package dimensions (as a way for the merchant to remember which package is the rate referring to) and a `<select>` with all available rates for each package (with the price alongside).
Since this step required a more "dynamic" communication between client and server, I've added 2 small things:
* Apart from returning `errors`, the server can now return an array of `field_options`. This assoc array will have the structure `"field.path" => "arbitrary data"`. That can be used to feed the client with dynamic options for a field (because the `formLayout` is immutable).
* There is a new kind of …

[Labels] Rates selection step

---

classes/class-wc-connect-shipping-label.php
classes/class-wc-connect-shipping-method.php

Fix for #478 
When labels fail to load the copy should read: "Shipping labels not loading? Visit the status page for troubleshooting steps."
When settings fail to load: "Settings not loading? Visit the status page for some troubleshooting steps."
CC @kellychoffman

Changed the message appearing when settings/labels fail to load

---

client/settings/views/packages/add-package-presets.js
client/settings/views/packages/packages-list-item.js
client/settings/views/packages/packages-list.js

Fixes #492 
I ran this regex: `^.+>[^><_=\{\}]+<.+$` in the client folder to find other potential offenders

Wrapped package texts in translate function

---

tasks/i18n.js
tasks/release.js

Small fix. With the change on Calypso i18n structure (extracting it to a new module) the i18n task stopped working. This change fixes that.
To test, just run `npm run i18n` and check that it doesn't :boom: and it generates a valid `i18n/strings.php` file.
@robobot3000 @allendav @nabsul

Fixed the i18n task

---

client/settings/views/packages/add-package.js

Fixes #484 
It's a bit of a tricky one and depends on the React/Redux practices. The React warning was caused by setting the `value` field to `undefined` on the form elements and then allowing the user to edit them. Now the setting to undefined/null happens all across the code in places such as reducer or preset packages. Rather than initialize default values there and set, for example, box weight to an empty string on the model, I assumed it's better to do it in the rendering step.
I'm happy to change it if necessary.

Package Settings - Assuming empty string if the value is undefined

---

classes/class-wc-connect-shipping-label.php
woocommerce-connect-client.php

Fixes #432
Hide the "Create Label" meta-box if we can't create a label for that order. The conditions are:
* The origin address (the WooCommerce "Base Location") must be in the US.
* The order shipping address must be in the US too.
* The order must contain at least one shippable product (if all the products are virtual/downloadable, a shipping label makes no sense).
To test, just create a bunch of orders and see if the "Create Label" meta-box is displayed. I've tried with an order with only downloadable products, an order for the UK, changing the WooCommerce Base Location to the UK, and in all those scenarios the meta-box must **not** appear.
@robobot3000 @allendav @nabsul @jeffstieler

Display the "Create Label" meta-box only for qualifying orders

---

classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-shipping-label-controller.php
client/shipping-label/state/actions.js

Fixes #504
Use the real selected payment method ID in the Purchase Label request, instead of a hardcoded one.
There's no real way to test it, since the Purchase Label request doesn't actually work.
@nabsul @jeffstieler @robobot3000 @allendav

Use the real selected payment method ID in the Purchase Label request

---

karma.conf.js
webpack.config.js

Fixes #518 and #517 
To check if it works:
Webpack source maps change:
* Add a breakpoint to mapped JS source in a browser
* Verify that it is being hit
Console logging
* add `console.log` or any other console statement to a unit test
* run `npm-test` from terminal
* verify that the message has been logged to the terminal

Changed source maps method and added console logging to the JS unit tests

---

woocommerce-connect-client.php

Fixes #526 
Updated a changed function name and `rootView` in `woocommerce-connect-client.php` when rendering the service settings pages.
To verify:
* check that the service settings page renders correctly

Fixed rendering of the service settings pages

---

classes/class-wc-connect-help-view.php

Fixed URL to use docs.woocommerce.com instead of the old docs.woothemes.com

Fix doc URL

---

client/main.js

This fixes an issue where trying to reload and navigate away from the payment settings page produces an "are you sure" dialog regardless of whether any changes have been made or not.

Fixed payment settings reload dialog

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-shipping-method.php
classes/class-wc-rest-connect-shipping-rates-controller.php
woocommerce-connect-client.php

Fixes #513.
To test:
* Use a REST client to make a `POST` request to `/wc-api/v1/connect/shipping-rates`
* Sample data below
```javascript
{
"origin": {
"address": "2100 Park Ave",
"address_2": "Unit 684212",
"country": "US",
"city": "Park City",
"postcode": "84068",
"state": "UT"
},
"destination": {
"address": "1003 1st St",
"address_2": "",
"country": "US",
"city": "Snohomish",
"postcode": "98290",
"state": "WA"
},
"carrier": "usps",
"packages": [
{
"id": "box_1",
"template": "medium_flat_box_top",
"weight": 5
},
{
"id": "box_2",
"weight": 3,
"length": 10,
"width": 10,
"height": 10
}
]
}
```

Add REST controller for retrieving shipping rates from Connect.

---

assets/stylesheets/shipping-label.scss
client/shipping-label/views/steps/address/suggestion.js

When an address is normalized and the user must choose between the old and the normalized address, the fields that were changed are now highlighted.
Screenshot:
@kellychoffman @nabsul @robobot3000 @allendav @jeffstieler

Added blue highlight to the changed fields of an address suggestion

---

assets/stylesheets/shipping-label.scss
client/shipping-label/state/selectors/errors.js

Fixes #530
To test, just input an address with all the required fields, but a totally fake street name.
After you try to validate the address, the step should be marked as "Error", and the `Address` field should have an error that says "This address was not recognized".
@kellychoffman @allendav @nabsul @jeffstieler

Added an error to the "address" field if USPS couldn't validate an address

---

classes/class-wc-connect-shipping-label.php
classes/class-wc-rest-connect-shipping-rates-controller.php
client/shipping-label/index.js
client/shipping-label/state/actions.js
client/shipping-label/state/reducer.js
client/shipping-label/state/selectors/errors.js
client/shipping-label/views/purchase/steps/packages/index.js
client/shipping-label/views/purchase/steps/packages/list.js
client/shipping-label/views/purchase/steps/rates/list.js

This fixes an issue @kellychoffman had today testing the labels flow using a manually created order.
It also addresses the use case where an order does *not* have a rate from WCC during checkout.
To test:
* Ensure that the label flow works for orders made from the storefront
* Create a new order from the admin (or use one already existing)
* Ensure that the label flow still works for that "manual" order

Fix shipping rates without package data

---

client/packages/state/reducer.js
client/packages/state/test/reducer.js

During the Connectathon someone found this bug on the packages settings page:
- open the package dialog (either for edit or add new)
- show the outer dimensions field
- close the dialog by clicking the cancel button
- reopen the dialog as described in 1.
- the outer dimensions field will remain open, and there is no way to hide it
This PR fixes it.

Packages - fixed the outer dimensions field remaining open after dismissing the modal

---

classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-address-normalization-controller.php
classes/class-wc-rest-connect-packages-controller.php
classes/class-wc-rest-connect-self-help-controller.php
classes/class-wc-rest-connect-services-controller.php
classes/class-wc-rest-connect-shipping-label-controller.php
classes/class-wc-rest-connect-shipping-label-image-controller.php
classes/class-wc-rest-connect-shipping-label-refund-controller.php
classes/class-wc-rest-connect-shipping-label-status-controller.php
classes/class-wc-rest-connect-shipping-rates-controller.php
client/shipping-label/state/actions.js
client/shipping-label/state/normalize-address.js
woocommerce-connect-client.php

Fixes #556
The default behaviour (in Chrome) when a Promise is rejected and there is no `.catch` handler is to log the error in the console. So by removing the `.catch(noop)` the errors will be logged.
@allendav @nabsul @robobot3000 @jeffstieler

Remove .catch(noop) to make errors in Promises be logged in the console

---

client/shipping-label/views/refund/index.js

Change the wording of the Refund Label dialog so it's clear that the refund will take more than 14 days
Fixes #559 
@allendav @jeffstieler @robobot3000 @nabsul

Change the wording of the Refund Label dialog so it's clear that the refund will take more than 14 days

---

client/account-settings/state/actions.js
client/lib/save-form/index.js
client/lib/utils/parse-json.js
client/packages/state/actions.js

Fixes #554 
When the result of an AJAX call fails in the PHP side, the returned error page won't be valid JSON, so the error shown to the user was the quite obscure `Syntax error: < ...`. This can happen even if PHP prints a `NOTICE` before actually printing the JSON.
I wrapped all the places where the result of an AJAX request is parsed and if it fails, show a more legible generic error (and log the whole thing in the console).
@allendav @nabsul @robobot3000 @jeffstieler

Change the obscure "Syntax Error <" notice to something more readable when the JSON response is malformed

---

classes/class-wc-rest-connect-shipping-label-controller.php
client/shipping-label/views/tracking-link.js

To test:
* Purchase a label via Edit Order screen, or go to an order that already has a label
* Verify that the tracking code still appears and is linked

Label tracking code comes back in its own property now, not “provider label id”.

---

classes/class-wc-rest-connect-shipping-label-controller.php

Tracking information is returned in the `tracking_id` property during label purchase, not `tracking`.

Fix tracking code response property.

---

classes/class-wc-rest-connect-shipping-label-refund-controller.php

The settings store label metadata update is reused, and expects `label_id` as a property. This should be temporary as we rework the handler to use all response data.

Fix handling of label refund response.

---

CONTRIBUTING.md
DEVELOPER.md
README.md
classes/class-wc-connect-api-client.php
classes/class-wc-connect-debug-tools.php
classes/class-wc-connect-help-view.php
classes/class-wc-connect-service-settings-store.php
classes/class-wc-connect-settings-pages.php
classes/class-wc-connect-shipping-method.php
tests/php/test_wc-connect-services-validator.php
woocommerce-connect-client.php

Fixes: https://github.com/Automattic/woocommerce-connect-client/issues/592 in which we update this to its rightful name!
Server change: https://github.com/Automattic/woocommerce-connect-server/pull/558

Naming: Find 'WooCommerce Connect', replace with 'Connect for WooCommerce'

---

assets/stylesheets/components/foldable-card/style.scss
assets/stylesheets/shipping-label.scss
assets/stylesheets/style.scss
client/shipping-label/views/purchase/steps/address/suggestion.js

Fixes: https://github.com/Automattic/woocommerce-connect-client/issues/599
- Suggested address: uses a notice for clarity
- Foldable card header: even out the padding, reducing overall height
- Selects: fix height so its the same size as <input>

Shipping labels: clean up card header, selects, and notices

---

client/components/dropdown/index.js
client/components/number-field/index.js
client/components/text-area/index.js
client/components/text-field/index.js
client/packages/views/modal-errors.js

This fixes a warning that appeared in development. Calypso's `<FormTextInput>` requires a boolean `isError` prop, and we were passing whatever, trusting the Javascript "true-ish" and "false-ish" values.
This `propType` enforcement was implemented recently, so this started emitting the warning when we updated our `wp-calypso` dependency.
To test, go to the Purchase Label Dialog, delete some required field (for example, `City`), and check that the console doesn't emit an error.
@allendav @nabsul @robobot3000 @jeffstieler

Make sure all Calypso components with an "isError" prop are invoked with an actual boolean

---

classes/class-wc-connect-shipping-label.php

With some recent refactor, when you create an order from scratch, the destination address is completely empty. That means even the country, which defaults to the first one alphabetically (Aland Islands), and the country selector is disabled. Since we don't support shipping to wherever that is, this is a bug :)
To test:
* Create an empty order with a shippable item.
* Go to the Print Label Dialog.
* Notice that the (disabled) destination country selector has `United States (US)` selected.
@nabsul @allendav @jeffstieler @robobot3000

The destination country for a manual order defaults to the country of origin instead of being blank

---

client/components/text-area/index.js

Fixes #630
The `isError` prop was being passed to the Calypso `<FormTextarea>` component, but since it was always `undefined`, it was being ignored (yay, Javascript!). With a recent fix that made all the `isError` props be `Boolean`, this warning slipped through.
To test:
* Go to the Self-Help page.
* Check there are no errors on the console and the Log textarea shows fine.
@allendav @jeffstieler @robobot3000 @nabsul

Remove the "isError" prop for FormTextarea, since it isn't supported

---

classes/class-wc-connect-api-client.php

Fixes #609
This renames the endpoint to something that is more syntactically correct. `/label/{label-id}/image` is more correct than `/label/image/{label-id}`.
To test:
- Test with: https://github.com/Automattic/woocommerce-connect-server/pull/579
- Try to buy a label, make sure you can print and reprint the cached label image
@allendav @jeffstieler @DanReyLop @robobot3000

Rename /shipping/label/image/{id} to /shipping/label/{id}/image

---

client/shipping-label/state/actions.js

Fixes the server's issue Automattic/woocommerce-connect-server#582 by handling the `box_id` field in the same way as the other unwanted fields.
CC @nabsul

Omitting the box_id field when purchasing a label

---

client/main.js
webpack.config.js

Fixes #634 
This issue is caused by a pre-condition check in `babel-polyfill` ([here](https://github.com/babel/babel/blob/de975b9660014a4533c90190b297352495636530/packages/babel-polyfill/src/index.js#L4)). Since the polyfill modifies the global scope (needed for adding methods to built-in types like `Array`, `Object`, etc), it has a check to make sure that it's loaded only once. Since virtually all React-based apps use babel + polyfill, that means 2 React apps can't coexist in the same page, at least without the work-around in this PR.
The risk of this PR is that the polyfill that runs first may be a different version that the one bundled in our app, so we would not be in total control of our environment, but that's always a risk when we develop for a platform like WordPress :)
To test:
* …

Only load the Babel polyfill if there hasn't already been loaded

---

client/settings/views/wcc-settings-form/settings-item.js

Allow layout schema to provide `Text` component body.
This avoids having to add non-settings to the form schema, which is how the Self Help page `Text` component is currently rendered.

Allow layout schema to provide Text component body.

---

client/account-settings/views/index.js

Mark the payment method selection form as “pristine” after a successful save.
To test:
* Select payment method under account settings
* Click save, wait for success
* Verify that you aren't prompted when trying to leave the page

Fix leave/stay prompt after account settings save

---

client/shipping-label/state/actions.js
webpack.config.js

Related server issue: https://github.com/Automattic/woocommerce-connect-server/issues/507
When the available rates are fetched in the Purchase Label UI, the client stores the `Shipment ID` for each rate received from the server. That `Shipment ID` is sent back to the server in the `Purchase Label` request.
To fully test this, the server branch `add/correct-order-label-purchase` will be needed too. To test, purchase a Label and check (in the Chrome DevTools) that in the request sent to the server each package has, apart from the selected `service_id`, a `shipment_id` of the form `shp_123456789`.
@nabsul @jeffstieler @allendav @robobot3000

Send the shipment ID for each package when requesting a label purchase

---

readme.txt
woocommerce-connect-client.php

Fixes #663
To test:
Ensure the terms of service link in the opt-in banner links to https://woocommerce.com/terms-conditions/

Update TOS URL

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-service-settings-store.php

Closes #651 
This PR includes code to create and store a GUID as a store option, and send that GUID with all API requests to the server. This is needed to collect anonymized stats on the server side.
To test:
- Test with pending server PR 607 if it's not merged yet.
- Open up the settings page or anything that requires communication with the server
- Check that there is now a `wc_connect_store_guid` field in the database
- Check that the field is sent with API requests
- Check that if the option is deleted, it is automatically regenerated
- Check that the field is not regenerated if it already exists
@allendav @jeffstieler @DanReyLop @robobot3000

Generate anonymous UUID

---

assets/stylesheets/style.scss
classes/class-wc-connect-shipping-label.php
client/lib/utils/get-box-dimensions.js
client/shipping-label/index.js
client/shipping-label/state/actions.js
client/shipping-label/state/reducer.js
client/shipping-label/state/selectors/errors.js
client/shipping-label/state/test/reducer.js
client/shipping-label/views/purchase/index.js
client/shipping-label/views/purchase/steps/packages/add-item.js
client/shipping-label/views/purchase/steps/packages/get-package-descriptions.js
client/shipping-label/views/purchase/steps/packages/index.js
client/shipping-label/views/purchase/steps/packages/item-info.js
client/shipping-label/views/purchase/steps/packages/list.js
client/shipping-label/views/purchase/steps/packages/move-item.js
client/shipping-label/views/purchase/steps/packages/package-info.js
client/shipping-label/views/purchase/steps/packages/style.scss
client/shipping-label/views/purchase/steps/packages/unpacked.js
client/shipping-label/views/purchase/steps/rates/index.js
client/shipping-label/views/purchase/steps/rates/list.js

Adds #568 #569 #570 
Adds editable packing solution:
Left to do:
CC @allendav @kellychoffman @DanReyLop

Editable packaging solution

---

woocommerce-connect-client.php

Minor: changed the translation domain from `woocommerce` to `connectforwoocommerce`

Fixed the translation domain on the TOS notice

---

client/components/text/index.js
woocommerce-connect-client.php

Allow admin scripts to enqueue even if no schemas are available since only shipping method instance admin views require schemas.
To test:
* kill your local server so that the client cannot get schemas from it
* delete the wc_connect_services option
* go to wp-admin > WooCommerce > System Status > Connect for WooCommerce
* verify you are able to see self-help and that you are able to toggle debug logging on and off
Fixes #613

Allow scripts to enqueue even if no schemas are available

---

client/shipping-label/state/actions.js

With one of the Packaging PRs, the state tree structure changes, so `form.packages.values` doesn't exist anymore, and to iterate on the selected packages we must use `form.packages.selelcted` instead. This was broken during a rebase (or maybe a merge).
@nabsul

Fix label Preview

---

client/shipping-label/state/actions.js

Closes #667
This change is needed to support the new handling of rates on the server side.
It adds new fields to the label purchase request: rate_id and carrier_id
To test:
- Buy a label against server PR 615
@allendav @jeffstieler  @DanReyLop @robobot3000

Add support for rate_id and carrier_id fields

---

classes/class-wc-connect-service-schemas-store.php
classes/class-wc-connect-service-settings-store.php
classes/class-wc-connect-settings-pages.php
classes/class-wc-connect-shipping-method.php
classes/class-wc-rest-connect-packages-controller.php
client/packages/index.js
client/packages/state/actions.js
client/packages/state/reducer.js
client/packages/state/test/reducer.js
client/packages/views/add-package.js
client/packages/views/index.js
client/packages/views/packages-list-item.js
client/packages/views/packages-list.js
client/packages/views/style.scss
client/settings/index.js
client/settings/views/index.js
client/settings/views/services/group.js
client/settings/views/services/index.js
client/settings/views/wcc-settings-form/index.js
client/settings/views/wcc-settings-form/settings-group.js
client/settings/views/wcc-settings-form/settings-item.js
woocommerce-connect-client.php

Adds #670 
Should be tested with `add/centralized-flat-rates` checked out on the server-side.
To test:
- Check that you can see the predefined packages in the Packaging Manager:
- Check that disabling the packages hides the corresponding services from the shipping instance settings:
- Check that no flat rates are returned to the customers when flat rate packages are disabled in the packaging manager

Added UI for managing flat rate packages

---

classes/class-wc-connect-tracks.php
woocommerce-connect-client.php

Fixes #688 
To test:
* Install and activate WooCommerce and WooCommerce Connect
* Install, activate and connect Jetpack
* Make sure WP_DEBUG is enabled
* Tail the admin error log
* Deactivate and activate Connect for WooCommerce and make sure deactivation/activation succeeds and  no errors display on the screen.
* The following may be logged from time to time - this is normal
* `jetpack_data_class_not_found Unable to send request to Connect for WooCommerce server. Jetpack_Data was not found. (fetch_service_schemas_from_connect_server)`
* `Error. jetpack_tracks_record_event is not defined.`
* Repeat without Jetpack activated
* Repeat without WooCommerce activated
* Repeat without neither Jetpack nor WooCommerce activated

During activation and deactivation, test for dependencies before using them

---

assets/stylesheets/shipping-label.scss
classes/class-wc-connect-api-client.php
classes/class-wc-rest-connect-address-normalization-controller.php
client/lib/utils/phone-format.js
client/shipping-label/index.js
client/shipping-label/state/selectors/errors.js
client/shipping-label/views/purchase/steps/address/fields.js
npm-shrinkwrap.json
package.json
webpack.config.js
woocommerce-connect-client.php

Fixes https://github.com/Automattic/woocommerce-connect-client/issues/574
You need to test it with the `add/phone_address` branch in the server.
**Background:**
EasyPost uses internally different APIs for ["regular" mail](https://www.usps.com/business/web-tools-apis/delivery-confirmation-domestic-shipping-label-api.htm) and for ["Priority Express" mail](https://www.usps.com/business/web-tools-apis/priority-mail-express-api.htm).
The normal API doesn't require the parameter `FromPhone` or `ToPhone`, but the Express API does (10-digit number, without punctuation). The solution is to add a `Phone number` field to the `Origin address` and `Destination address` form. This will make the phone field mandatory even for services that don't require it, but it's the simplest solution.
**Changes:**
* …

Add a "Phone Number" field to both the origin and destination address in the Labels UI

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-service-schemas-store.php
classes/class-wc-connect-shipping-label.php
classes/class-wc-rest-connect-shipping-rates-controller.php
client/shipping-label/index.js
client/shipping-label/state/actions.js
client/shipping-label/state/reducer.js
client/shipping-label/views/purchase/steps/packages/index.js
client/shipping-label/views/purchase/steps/packages/package-info.js
woocommerce-connect-client.php

Adds #671
Test with https://github.com/Automattic/woocommerce-connect-server/pull/625 
To test:
* open the label print UI
* verify that the flat rate packages appear in the packaging editor
* at the moment all flat rate packages are shown, regardless of what has been enabled/disabled in the packaging manager
* select one or more flat rate packages
* verify that the prices that appear are for flat rate deliveries
* check that purchasing a label works

Add flat rate packages to labels

---

classes/class-wc-connect-help-view.php

Fixes #709
To test:
Open the status page and verify that there are no errors about required props logged in the console.
CC @nabsul

Status page - fixed React errors

---

classes/class-wc-connect-help-view.php

Found this while testing the plugin on one of my live sites. I didn't have Jetpack and there was no clear indication that I needed to. I was linked to the Status page and saw this error:
> Please connect Jetpack to WordPress.com
It doesn't make much sense to someone who doesn't have Jetpack (or maybe hasn't heard of it). I updated the message to say: 
> Jetpack is not connected to WordPress.com. Make sure the Jetpack plugin is installed, activated, and connected.

Status page: Make the Jetpack error more clear

---

classes/class-wc-connect-api-client.php

As surfaced in this discussion: https://github.com/Automattic/woocommerce-connect-client/pull/693#discussion_r87910303
We need to raise the configured REST request timeout (from merchant host to WCC server) because 20 seconds is too low for complex operations like multiple label purchasing. The problem is, the default PHP timeout (for a whole PHP script execution) is 30 seconds in my machine (I assume I don't have a very exotic configuration), and that can be too low too, so we need to at least try to increase the PHP timeout.
@jeffstieler said: I'm not sure we want to mess with PHP timeout
My reponse:
The `set_time_limit()` option only affects the current request. What happened is that I put the "request timeout" to 60 seconds, but since the default PHP timeout (in my machine) was 30 …

Put a higher remote request timeout (1 minute) in the server, disable default PHP script timeout.

---

assets/stylesheets/shipping-label.scss
assets/stylesheets/style.scss
client/components/action-buttons/index.js
client/shipping-label/views/purchase/index.js

Fixes #603 
When the Purchase Label form is submitting, instead of just disabling the "Purchase" button, change its text and show a progress indicator (a Spinner).
Screenshot:
To test, just go purchase a Label.
The only doubt I have about this one is maybe using `Buying...` instead of `Purchasing...`, since the original button label is `Buy & Print N Labels`.
@nabsul @allendav @jeffstieler @robobot3000

Added an spinner to the "Purchase" button while the request is being processed

---

readme.txt

Fixes #707 
No real way to test this until this is pushed to WordPress.org in the next tag, but you can compare against the WooCommerce repo's readme.txt and ensure the case matches

Fix casing on automattic and woothemes contributors

---

client/components/modal/index.js

I've noticed this error while reviewing another PR.
Calypso uses `closest-component@0.1.4` ( https://github.com/Automattic/wp-calypso/blob/master/package.json#L40 ), and `woocommerce-connect-client` uses `1.0`. Webpack shenanigans means that when our code requires `component-closest`, sometimes `v0.1.4` is required, and sometimes `v1.0`, which has a backwards-incompatible change. Hence, when `v0.1.4` was included, our logic to close a dialog when the user clicks outside of it was not working correctly and the dialog didn't close.
I've modified the code so it works the same way in both versions of `component-closest`, so now when you click outside a dialog it should **always** close.
Since this bug was non-deterministic, there is no reliable way to test it.

Fix clicking outside a dialog not closing it sometimes.

---

client/settings/views/services/entry.js
client/settings/views/services/group.js

Fixes #715 
I fixed this by still showing the flat rate services when the corresponding flat rate package has been disabled, but instead marking them as disabled as well:
The disabled rows have a `title` attribute that reads: `You can manage this service after enabling the corresponding package in the Packaging Manager`
CC @allendav to approve this change. I can always revert back to the simple fix for the service count
CC @jeffstieler

Fixed the incorrect service counts when predefined packages are disabled

---

client/packages/views/style.scss
client/settings/views/wcc-settings-form/settings-item.js

Fixes: https://github.com/Automattic/woocommerce-connect-client/issues/725
Quick trash pickup because I kept having an unnecessary amount of tabs at the end of a UX testing session. 
To test, go to the Packaging section on the USPS shipping method and click the Packaging manager link. It doesn't open in a new tab anymore. 
Also, the icons on the Type column are now vertically aligned in the the Custom packages section on the Packaging Manager page.

Packaging manager link: remove target="_blank"

---

client/shipping-label/views/refund/index.js

Fixes #721 
Now that all our dates are timestamps (numbers) until they are displayed to the user, it's safe (and required) to change all React PropTypes regarding dates from `string` to `number`. I could only find one, in the Refund Dialog view.
To test:
* Make sure your `woocommerce-connect-server` is in the latest version of `master`.
* Purchase a label (or go to an order with an already purchased label).
* Check that in the console, it doesn't appear an eror like `Failed prop type: invalid prop 'created' of type 'number' supplied to RefundDialog, expected 'string'`.
@nabsul @allendav @jeffstieler @robobot3000

Changed date prop from string to number (timestamp)

---

classes/class-wc-connect-service-settings-store.php
classes/class-wc-rest-connect-address-normalization-controller.php
classes/class-wc-rest-connect-shipping-label-controller.php
client/shipping-label/state/normalize-address.js
client/shipping-label/state/reducer.js

Fixes #600 
This PR is totally backwards and forwards-compatible, but you won't be able to test it properly without the `update/auto-accept-address-normalization` branch on the server.
When sending an address to normalize to the server, if the response has the `is_trivial_normalization` property set to `true`, then the normalized address will be automatically accepted without user intervention. As its name indicates, that flag will be set when the changes made by the address normalizator were trivial, such as adding the `+4` portion to a ZIP code, or changing capitalization, or changing `street` to `st` for example.
To test:
* Go purchase a label.
* Make sure the origin address is normalized (the step has the green checkmark icon).
* Make *only* trivial changes, such as:
* Change some …

Logic to auto-accept address normalizations if the response has a special flag

---

classes/class-wc-connect-api-client.php

Closes #724 
Something fishy is going on in the WooCommerce product object. the function objects `get_length()`, `get_width()`, `get_height()`are returning an empty string when the value of the dimension is "0". This doesn't seem to happen if the value is "0".
To mitigate this issue I'm forcing whatever these functions return into a float using `floatval()`. I thought about putting some error checking and logging in place for this situation, but decided to just go with the simplest solution.
I've submitted a report to WooCommerce Core:
https://github.com/woocommerce/woocommerce/issues/12455
To test:
- Try setting a product dimension to "0" from some non-zero value (this seems to be important)
- Add that product to the cart and try requesting shipping rates for that product
- Observe that …

"0" and "0.0" dimensions are treated differently for shipping rate requests

---

assets/stylesheets/style.scss
classes/class-wc-connect-settings-pages.php

Fixes #536 
Fixes #733 
To test:
* Install changes on a real site (dev sites with fake Jetpack connections won't cut it)
* Make sure the site's Jetpack is connected
* Make sure you are logged in as the site's primary user
* Go to wp-admin > WooCommerce > Settings > Connect for WooCommerce
* Verify you are able to see payment methods as before
* Login as another administrator
* Go to wp-admin > WooCommerce > Settings > Connect for WooCommerce
* Verify you are prompted to have the primary user manage payments for you
* Disconnect the Jetpack
* Go to wp-admin > WooCommerce > Settings > Connect for WooCommerce
* Verify you are prompted to connect your Jetpack
Looks like this:

Only allow the primary user to make payment method changes

---

classes/class-wc-connect-settings-pages.php

Fixes #745 
To test:
- on a site with WP_DEBUG enabled and an active Jetpack connection, log in as the primary user and navigate to wp-admin > WooCommerce > Settings > Connect for WooCommerce > Account Settings
- make sure you can see your payment methods you have saved
- make sure no error is displayed
- log out
- log in as another user with admin privledge or at least store management privledge and navigate to wp-admin > WooCommerce > Settings > Connect for WooCommerce > Account Settings
- make sure you cannot see payment methods
- make sure no error is displayed

Fix incorrect handling of get_master_user response

---

client/shipping-label/state/actions.js
i18n/strings.php

Changed the copy on the refund request success message.
Before:
`The refund request has been sent correctly`
After:
`The refund request has been sent successfully.`

Refund success message: Change 'correctly' to 'successfully'

---

classes/class-wc-connect-shipping-label.php

Fixes #751
To test, complete an order for a shippable item with free shipping as the shipping method.  Make sure you do not get a "packages" error in the labels ui. Make sure you are prompted to select from various shipping options, e.g.:
cc @robobot3000  or @DanReyLop for review since you're most familiar with this part of the code

Add id and box_id when preparing labels from a free shipping order

---

assets/stylesheets/style.scss
classes/class-wc-connect-settings-pages.php

Fixes #748 
To test, try browsing payment methods on a dev mode site and a non dev mode site
Adds a note below the container to warn you if you are in dev mode, since the only payment methods you can see then are based on local server configuration, e.g.:

Allow payment methods to be managed in jetpack dev mode

---

classes/class-wc-connect-api-client.php

Before, if you tried to get rates (from the checkout) for an item without weight, you got this error:
```wcc_server_error_response Error: The Connect for WooCommerce server returned: Bad Request child "contents" fails because ["contents" must be an array] ( 400 ) (calculate_shipping)```
The PHP side detects that an item doesn't have weight and "throws" a WP_Error instead of the serialized packages. The problem is, that WP_Error was being **sent** to the server instead of just failing early.
To test:
* Create a product with dimensions, but without weight.
* Configure a Connect USPS shipping method.
* Purchase that item, and try to get shipping rates for it.
* You shouldn't get any rate, that hasn't changed. But, in the debug log, instead of seeing the cryptic error above, you should see a …

Make the PHP fail a rates request in the checkout if an item doesn't have weight

---

client/shipping-label/state/reducer.js

Fixes #783 
To test:
* place an order
* open the order in the admin panel and open the labels UI and then the packaging section
* using the "move item" button next to one of the items, move it to the original packaging
* try to request rates

Fixed the missing id when shipping items individually

---

woocommerce-connect-client.php

FIxes #799
To test:
* open the order page
* verify that the label box appears above the order notes

Moved the labels metabox above order notes

---

woocommerce-connect-client.php

Closes #798 
To Test:
- Use an installation with a custom table prefix
- See the error with master (see screen shot in issue)
- See there is no error with this fix

Use wordpress table prefix for shipping zone query

---

classes/class-wc-rest-connect-shipping-label-controller.php
client/shipping-label/state/actions.js
client/shipping-label/state/reducer.js
client/shipping-label/views/index.js
client/shipping-label/views/purchase/index.js

Fixes #771 
To test:
* Go purchase a label.
* While the purchase button is in the "Purchasing..." style, note that you can't close the dialog or click the button.
* Note that the button keeps being in that state until the PDF print dialog appears.

	Make the label UI submit button keep being disabled while the PDF is being downloaded

---

classes/class-wc-connect-api-client.php
classes/class-wc-rest-connect-shipping-label-status-controller.php
client/shipping-label/state/actions.js

Fixes #789
To test:
* purchase a new label in the client, do not request a refund on it
* in the server database, add a new row for that label's refund in `wcc_shipping_label_refund`
* alternatively use the support tools to refund a label
* refresh the order page
* verify that the refund status has been updated

Always fetching the label refund status

---

classes/class-wc-rest-connect-shipping-label-controller.php
classes/class-wc-rest-connect-shipping-rates-controller.php

When to store the origin address to be reused on the Purchase Label flow?
* Old-old way: As soon as the origin address is normalized. The problem with that is that, if we store the normalized version of the address, the merchant will see *that* address the next time, even if he decided to use the un-normalized one.
* Old way: When a label purchase request is made. Which means that, if the user has problems retrieving rates, he will have to input his address again the next time he tries.
* New-awesome way: Store the address when a label rates request is made. This is the best of both worlds.

Store the origin address then label rates are requested, instead of when a purchase is made

---

classes/class-wc-connect-shipping-label.php
classes/class-wc-connect-shipping-method.php

Fixes #807
Automattic/woocommerce-connect-server#748 will be useful during testing
To test:
* Configure the fallback rate in the shipping settings
* Stop the server (to trigger a request error)
* Verify that you can get the fallback rate at the checkout
* Check that you still get the fallback rate if the server is running, not returning an error, but also not returning any rates
* Place an order and check that everything is ok on the admin order page

Added fallback rates to the client-side

---

client/shipping-label/views/refund/index.js

closes #788
The logic for showing the refund dialog shows or hides all dialogs, resulting in the last one rendered showing on top of the rest.
To Test:
- Make a purchase with multiple packages
- Buy labels, preferably with different prices to easily distinguish them
- On master, open the refund dialog for each one. Only one of the two prices will show.
- In this branch, that should be fixed
@jeffstieler @DanReyLop @robobot3000 @v18

Clicking refund shows the wrong dialog box

---

assets/stylesheets/shipping-services.scss
client/components/info-tooltip/index.js
client/settings/views/services/group.js

Fixes #822 
Added a tooltip to explain the merchant what the "Price adjustment" ptions are.
To test, just go to a shipping instance configuration, open a service group and hover over the `(i)` icon. In mobile, it works by clicking on it.
Screenshot:
I think it's fine, even a longer text would be perfectly fine.

Add tooltip to explain what adjustments are

---

assets/stylesheets/shipping-services.scss
assets/stylesheets/style.scss

Make the State <select> the same size as its surrounding fields

---

classes/class-wc-connect-error-notice.php
classes/class-wc-connect-help-view.php
classes/class-wc-connect-logger.php
classes/class-wc-connect-payment-methods-store.php
classes/class-wc-connect-service-schemas-store.php
classes/class-wc-connect-service-settings-store.php
classes/class-wc-connect-shipping-method.php
classes/class-wc-connect-tracks.php
classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-address-normalization-controller.php
classes/class-wc-rest-connect-self-help-controller.php
classes/class-wc-rest-connect-services-controller.php
classes/class-wc-rest-connect-shipping-label-controller.php
classes/class-wc-rest-connect-shipping-label-refund-controller.php
classes/class-wc-rest-connect-shipping-label-status-controller.php
classes/class-wc-rest-connect-shipping-labels-preview-controller.php
classes/class-wc-rest-connect-shipping-labels-print-controller.php
classes/class-wc-rest-connect-shipping-rates-controller.php
tests/php/test_class-wc-connect-shipping-method.php
tests/php/test_woocommerce-connect-tracks.php
woocommerce-connect-client.php

Closes #794
Closes #793
Closes #791
Closes #821
- Add debug vs error messages in logger (errors are logged even if the debug switch is disabled)
- When an error is logged, trigger a dismissable notice in the admin page to review logs
- Log shipping rates issues as errors instead of debug messages
To Test:
- Try to get shipping rates at checkout with an item that doesn't have dimensions
- Go to the admin panel
- Observe the admin notice
- Click the link to go to the Connect status page
- Click the dismiss button to make the message go away

Notify admin when cart has items with no dimensions

---

client/account-settings/views/index.js
client/packages/views/index.js
client/settings/state/values/actions.js

Fixes #837
Changed all the success notices to show for 5 seconds, like in Calypso. Except for the "Label purchased" notice which is permanent.
All the error notices permanent (but dismissable). Before, there were some of them that lasted 7 seconds. Since they dissapear when the user navigates to another page anyway, it's unlikely that errors will "pile up", even if the user doesn't dismiss them.

Changed all the success notices durations to make them more consistent

---

assets/stylesheets/shipping-label.scss
assets/stylesheets/style.scss
client/components/info-tooltip/index.js
client/components/info-tooltip/style.scss
client/shipping-label/views/index.js

Added a dotted underline to the "Label #N" title on the labels list, to make it clearer that there is a tooltip there.
Right now, `text-decoration` is only well supported in Firefox (see [support table](http://caniuse.com/#feat=text-decoration)). In other browsers, it will just display a solid black line, not a dotted dark-gray line.
The other option is using a `border-bottom: 1px dotted $gray-dark;`, but that feels too hacky. @kellychoffman what do you think?

Added a dotted underline to the "Label #N" title on the labels list, to make it clearer that there is a tooltip

---

classes/class-wc-connect-service-settings-store.php
client/shipping-label/index.js
client/shipping-label/state/actions.js
client/shipping-label/state/reducer.js
client/shipping-label/state/selectors/errors.js
client/shipping-label/state/test/reducer.js

Fixes #813 
To avoid the overwhelming "everything is red!!!1!" experience when the merchant opens the Purchase Label dialog without an stored Origin address, I've tweaked the validation logic to only kick in when a particular field is edited.
To test:
* Remove the origin address from your settings. That's the `wc_connect_origin_address` option. You can just also go to `classes/class-wc-connect-service-settings-store.php`, function `get_origin_address()`, put this in at the start: `update_option( 'wc_connect_origin_address', array() );` and reload the Order page once.
* Go print a label. You should see the "Origin address" step expanded but no visible errors.
* Once you edit a field such as the ZIP code, you see the error (if any) on that field, but not on the rest.
* You can click the …

When origin address is empty, don't immediately validate its fields

---

classes/class-wc-connect-settings-pages.php
client/settings/views/wcc-settings-form/settings-item.js
client/shipping-label/views/purchase/steps/packages/index.js

Closes #823
The package manager and shipping label payment methods are now moved under the shipping tab in woocommerce settings.
To Test:
- Go to the shipping tab
- Try to go to the old "Connect for WooCommerce" tab
@kellychoffman

Move Connect tabs under shipping settings

---

classes/class-wc-connect-help-view.php
classes/class-wc-connect-shipping-label.php
client/packages/views/index.js
client/packages/views/packages-list.js
client/packages/views/style.scss
client/settings/index.js
client/settings/views/index.js
client/settings/views/services/entry.js
client/settings/views/services/group.js
client/settings/views/services/index.js
client/settings/views/wcc-settings-form/index.js
client/settings/views/wcc-settings-form/settings-group.js
client/settings/views/wcc-settings-form/settings-item.js
client/shipping-label/views/purchase/steps/packages/package-info.js
woocommerce-services.php

Fixes #818
This does the following things:
* removes the flat rate packages from the packaging manager screen
* the flat rate services are always enabled
* when enabling a flat rate service the corresponding package is treated as enabled automatically
To test:
* checkout the server branch at Automattic/woocommerce-connect-server#750
* verify that it's possible to enable flat rate services
* request rates and verify that the flat rates are coming back
* place an order and verify that the flat rate packages are still visible in the packaging manager

Flat rate services - checkboxes always enabled

---

client/lib/initialize-state/index.js
client/main.js
client/settings/state/actions.js
client/settings/state/reducer.js
client/settings/state/selectors/errors.js
client/settings/state/test/reducer.js
client/settings/state/values/actions.js

Fixes #795.
To test:
* Add a new USPS shipping zone instance
* Verify that the initial form load (with empty origin zip) does not have an error
* Alter the "name" field
* Verify the "origin" has not been validated
* Save the form
* Verify that "origin" has an error (from server)
* Refresh the page - *do not save*
* Enter a single character into "origin"
* Verify that "origin" has an error (from client)

Only validate (instance) form fields that have been changed

---

classes/class-wc-connect-nux.php
client/admin-pointers.js
client/test/mock-jquery.js
karma.conf.js
webpack.config.js
woocommerce-services.php

This PR adds a pointer to the shipping zone page. The pointer is dismissible, and multiple pointers can eventually be shown on the same page in sequence, and on other pages.
The pointer does not point up from the '+' button like this:
Instead, it looks like this:
cc @kellychoffman  ^
The reason is because the zones are added via js in WC, and I didn't see a way to hook in after they're added to avoid a race condition which would potentially make our pointers not show up at all.
Should we add styles that will match the pointers to our admin notices?

Add shipping zone pointer

---

README.md
classes/class-wc-connect-help-view.php
classes/class-wc-connect-logger.php
readme.txt

Some occurences were missed in the previous PR ( https://github.com/Automattic/woocommerce-services/pull/844#discussion_r97836123 )
We would still need to rename our hooks, filters and class names and `wp_options` entries, but that's a rabbit hole with much much lower priority.

Rename all the user-facing strings from our old branding (connect for woocommerce) to the new branding (woocommerce services)

---

woocommerce-services.php

Fixes #849.
To test:
* Verify that you don't have `wc_connect_tos_accepted` in your `wp_options`
* Click "connect" on the TOS notice
* Verify that you are redirected to the WooCommerce > Shipping settings page

Redirect users to the shipping settings screen after accepting the TOS.

---

assets/stylesheets/shipping-label.scss
classes/class-wc-connect-shipping-label.php
client/shipping-label/index.js
client/shipping-label/views/index.js
woocommerce-services.php

Fixes #549.
To test:
* With a credit card selected for payment - go to an order detail page
* Verify that an info notice shows the last 4 digits of the card selected for labels
* Verify that the "manage cards" link goes to the correct settings page
* With **no** credit card selected for payment - go to an order detail page
* Verify that an info notice states that you need to select a card to print labels
* Verify that the "add card" link goes to the correct settings page 
* Verify that no "create label" button is shown

Don't allow merchants to enter label dialog before selecting a payment method

---

classes/class-wc-connect-settings-pages.php

Rename the "shipping label" tab to "shipping labels" to be more consistent with the plural forms used in the rest of the tabs in shipping settings

Rename the "shipping label" tab to "shipping labels"

---

CONTRIBUTING.md
README.md
readme.txt

Apart from some references to our software being `BETA`, our docs had some outdated stuff in them, like suggesting that in the future this will be part of WooCommerce Core, or talking about Canada Post rates in future tense. Fixed that.

Remove BETA references from all our codebase, updated some aspects of README and CONTRIBUTING

---

woocommerce-services.php

Fixes the issue _"When the user opts in and is redirected to shipping, the new methods are not yet loaded"_.
**Problem**: Fetching the service schemas were scheduled for the `admin_init` action. Our general plugin initialization code happens in the `woocommerce_init` action, which is before. In that initialization code, it's checked if the schemas exist and only attach some hooks if they do. So, just after installing the plugin, those hooks won't be attached _on the first page load_.
**Solution**: Move the schema fetching to _before_ the hooks are attached. This is the simplest solution and the one I implemented.
**Alternative solution** (not implemented): All our code is pretty defensive about schemas not being there. We could just omit the `if($schemas){` conditional entirely ([line …

Fetch service schemas before attaching admin hooks

---

classes/class-wc-connect-service-settings-store.php

The internal WooCommerce session cache that caches shipping rates wasn't being busted when one of our shipping methods config was being updated. This lead to an annoying bug (most noticeable when testing) when the changes made to the shipping method didn't appear to work.
Looking at the WooCommerce codebase, this cache-busting is done pretty much whenever anything shipping-zone-related is done, we just needed to add it to our own methods.
To reproduce:
* Get an USPS shipping method working.
* Buy something on the store.
* On the checkout, note that you will receive some USPS rates.
* In another tab, go to the USPS method config and make some changes. For example, add an obvious `adjustment` to one of the returned services.
* In the checkout, delete the last number of the ZIP code and type …

Bust the shipping rates session cache every time the settings of a shipping method change

---

client/shipping-label/views/index.js

Fixes #772 
To test:
* verify that the labels are numbered 1-N in the labels history, where 1 is the oldest label

Labels history - numbering labels 1-N instead of using their IDs

---

woocommerce-services.php

Closes #665
I also added the TOS update on plugin deactivation, so that if the plugin is deactivated and activated again, the TOS notice will always show.
To test:
* you will need to have the plugin activated and enable debugging on the System Status page
* enable WP_DEBUG (I also enabled logging to file, as I couldn't get the events to show in the html)
* enable the plugin
* verify that `Tracked the following event: woocommerceconnect_opted_in` is not logged yet, and that the TOS notice appears
* accept the TOS
* verify that the event has been tracked now

Tracking the "opt in" event only after the TOS has been accepted

---

assets/stylesheets/shipping-services.scss
assets/stylesheets/style.scss
client/components/bulk-checkbox/index.js
client/components/indeterminate-checkbox/index.js
client/packages/state/actions.js
client/packages/state/reducer.js
client/packages/views/index.js
client/settings/views/services/group.js

Added indeterminate checkboxes for when only a subset of service/package checkboxes is selected:
To test:
* navigate to the service settings or package manager
* verify that everything works fine (selecting all through the main checkbox, selecting only a few boxes, selecting all the boxes manually)
* also check the console for any React errors
* check that the settings save as expected
CC @jeffstieler @kellychoffman

Added indeterminate checkboxes

---

classes/class-wc-connect-help-view.php

Fixes #872.
To test:
* Go to WooCommerce > System Status > WooCommerce Services
* Verify the "support docs" link goes to https://docs.woocommerce.com/document/woocommerce-services/, not the FAQ page

Point support docs link to the new document URL.

---

woocommerce-services.php

Restore tracks event when users accept the Terms of Services.
This was errantly removed in https://github.com/Automattic/woocommerce-services/commit/8612b81cfe02967316e1b8f5b8c33cb6386a0325

Restore tracks event when users accept the Terms of Services.

---

client/shipping-label/state/actions.js

This is a fix for https://github.com/Automattic/woocommerce-connect-server/issues/775, which was thought to be a server side issue.
To test:
* Manually create an order with a product that has invalid or missing weight/dimensions info, but with a destination address that will automatically pass normalization
* Open create label dialog
* Verify that the Packaging step is open with errors, and rates are not requested
* Reopen the Destination step, click "use this address"
* Verify that the Packaging step is open with errors, and rates are not requested
* Reopen the Destination step, enter in an address that will trigger a non-trivial normalization result
* Click "use this address"
* Verify that the Packaging step is open with errors, and rates are not requested

Prevent label rates requests when packaging data is errant

---

client/lib/save-form/index.js
client/main.js

Our plugin was completely broken on IE11 and Edge. This is what was happening:
`require()` statements are executed **after** `import` statements, even if they are before in the file. That means that the Polyfill wasn't executed until all the `import`ed JS modules were parsed and executed. This broke IE11 pretty bad. The solution is to include the polyfill using a regular `import`. This will break if there is another React-based plugin in the same page, but for now it's an acceptable tradeoff. It will be fixed when we start using `babel-preset-env` (spiking on it this week).
Also, MS Edge breaks if `fetch()` is called with a request with `body === null`, for some reason. I've changed it to include the `body` property only when there is actually a body.

Fix IE11 and MS Edge errors

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-error-notice.php
classes/class-wc-connect-help-view.php
classes/class-wc-connect-logger.php
classes/class-wc-connect-nux.php
classes/class-wc-connect-options.php
classes/class-wc-connect-payment-methods-store.php
classes/class-wc-connect-service-schemas-store.php
classes/class-wc-connect-service-settings-store.php
classes/class-wc-connect-shipping-method.php
woocommerce-services.php

Adds #776 
Removing the plugin will delete all of the directory contents, including local git repo and node_modules. This happens even if you use symlinks. Obvious, but worth pointing out.
Best checkout this repo separately into a fresh WP/WooCommerce installation, run `npm dist`, update some settings, then delete the plugin and verify that all of the options are gone as well.

Cleaning up plugin options on uninstall

---

classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-address-normalization-controller.php
classes/class-wc-rest-connect-packages-controller.php
classes/class-wc-rest-connect-self-help-controller.php
classes/class-wc-rest-connect-services-controller.php
classes/class-wc-rest-connect-shipping-label-controller.php
classes/class-wc-rest-connect-shipping-rates-controller.php
client/account-settings/state/actions.js
client/lib/save-form/index.js
client/packages/state/actions.js
woocommerce-services.php

Include the encountered JSON error in the response when service settings update fails.
See: https://wordpress.org/support/topic/shipping-zones-not-being-accepted/
Initially this started with just adding the numeric JSON decoding error to the response, but after finding the WP REST API classes builtin handling of JSON errors, it switched to a refactoring of our REST API usage.
This PR seeks to add the `Content-Type: application/json` header to WP REST API requests (in order to invoke the built in handling), and remove the manual `json_decode()`ing of those request bodies.
To test:
* Send bad JSON to any WP REST API endpoint added by WCS
* Verify that an error is returned
* Verify that the error and request info is logged
* Verify that all existing functionality works in the /wp-admin/ …

Include JSON parse error in service settings update repsonse

---

classes/class-wc-connect-nux.php

Fixes an error where nux notice would render after page refresh, even if it was dismissed.

Fixed the nux notice dismissal on the settings page

---

assets/stylesheets/_colors.scss
assets/stylesheets/_components.scss
assets/stylesheets/shipping-label.scss
assets/stylesheets/style.scss
client/components/bulk-checkbox/index.js
client/components/field-error/index.js
client/components/indicators/index.js
client/components/info-tooltip/index.js
client/lib/calypso-boot/index.js
client/packages/views/index.js
client/packages/views/packages-list-item.js
client/packages/views/packages-list.js
client/settings/views/services/entry.js
client/settings/views/services/group.js
client/settings/views/wcc-settings-form/nux-notice.js
client/shipping-label/state/actions.js
client/shipping-label/state/test/actions.js
client/shipping-label/views/index.js
client/shipping-label/views/purchase/step-container/index.js
client/shipping-label/views/purchase/steps/packages/item-info.js
client/shipping-label/views/purchase/steps/packages/list.js
client/shipping-label/views/purchase/steps/packages/package-info.js
npm-shrinkwrap.json
package.json

Fixes #870
Before, the origin and destination fields would not open until the normalization was finished:
Now, they'll both open if there are still things for the user to do, i.e. there are errors, or we're ignoring validation:
The unit tests are not complete. They are missing the cases where:
1. There are errors for either origin or destination address - this is because mocking `getFormErrors` was taking too long. I think the best way forward is to add it as a param to `openPrintingFlow`
2. The fields should _not_ open - this is because the toggle action will still be dispatched in `expandStepAfterAction` on line 202. This happens because the `getState` function will not actually return the new state with the `expanded` props. Thinking on the best way around this. Ideas welcome.
In the …

Show origin and destination fields if they're not normalized on open print flow

---

classes/class-wc-rest-connect-services-controller.php

Fixes a problem where the settings would get converted to an `array` instead of `object` when passed to the PHP backend (side effect of the changes from #883)
The code expects this to be an object in multiple places, especially in `WC_Connect_Shipping_Method`. One of the side effects is that the shipping method title will always be default on the shipping settings screen.
To test:
* create a new shipping method, set a custom title, save
* verify that everything works as expected (rates fetch and shipping settings page)

Converting service settings to an object on save to the database

---

classes/class-wc-connect-service-settings-store.php
woocommerce-services.php

Fix bug where settings were retrieved from a different option key than they were saved to.
Revert 7fea6f705877158de92b8580c2573adac62691e6 and use the id provide in the services schema to build WCS server request.
To test:
* On `master`
* Change some values in a USPS shipping method instance, click save
* Refresh page
* Verify that the _old_ values reappear
* On `fix/shipping-method-instance-settings-retrieval-bug`
* Change some values in a USPS shipping method instance, click save
* Refresh page
* Verify that the *new* values reappear

Fix shipping method instance settings retrieval bug.

---

classes/class-wc-connect-nux.php

To test:
* remove `wc_connect_nux_notices` from the `wp_usermeta` table
* open shipping settings and dismiss the nux notice
* refresh
* verify the notice is gone for good

Fixed nux notice dismissal on the service settings page

---

assets/stylesheets/style.scss

Fixes #906
CSS `initial` value for properties isn't supported in IE. I've changed the `initial` usages for the default values (`0` for `min-width` and `none` for `max-width`), that's exactly equivalent but works in IE :)
To test:
* Open the Purchase Label UI in IE11 in a wide monitor.
* See that the steps take the whole available horizontal space.

Fix Purchase Label Dialog cards not resizing to fill the width of the dialog on IE11

---

classes/class-wc-connect-shipping-method.php

Fixes: #895 
Remove calc_tax field from tax rates so that tax rates can be optionally calculated for shipping rates
To Test:
- Configure WooCommerce to add tax to shipping rates.
- Notice that in master taxes are not added, but they are in this rate
- Test that other tax configurations still work as expected
Thanks to @mikejolley for quickly pointing out the solution to this problem

Allow calculation of tax rates on shipping rates

---

client/shipping-label/index.js

Apply same “ignore validation” logic to the destination shipping address during label creation.
For manual orders that may not have a shipping address yet, don’t scare the merchant with a “wall of red”.
To test:
* Edit an order to remove the shipping address, or manually create an order
* Click "create label"
* Verify that the destination step opens, but does not show errors until interacted with

Labels: Don't initially show red error highlights for missing destination address.

---

classes/class-wc-connect-shipping-label.php

Fixes #796.
Use consistent formatting for product names in shipping label packaging step.
Product variations were using a different mechanism for name retrieval that included markup.
To test:
* Manually create an order with a product variation (so it doesn't have packaging data from WCS)
* Click "create label", go to packages step
* Verify that the product name does not contain HTML (or the price)

Product variation names in a package have escaped HTML in their name

---

woocommerce-services.php

Fixes #896
I didn't change the URL of the terms of service so that we don't need to worry about redirects. Let me know if you disagree.

Use 'WooCommerce Services' in TOS NUX notice

---

classes/class-wc-rest-connect-account-settings-controller.php

This was errantly changed from PUT to POST in 8e60ee01d5c9f2742b75939fbcb6774483dfb31a.
To test:
* Verify that saving account settings does not work on `master`
* Verify that saving account settings works as expected
Side note: perhaps we should consider restoring the use of the `WP_REST_Server` class constants instead of using string literals for our method definitions. (E.g. `WP_REST_Server::READABLE` instead of `'GET'`)
Doing so isn't called out as a best practice in the [REST documentation](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/), but is shown in some example code.

Fix HTTP method for account settings endpoint.

---

classes/class-wc-rest-connect-packages-controller.php

The initial refactor of the packages REST controller missed the variable that was renamed. See 8e60ee01d5c9f2742b75939fbcb6774483dfb31a.
To test:
* Try saving packages with the code on `master`
* Verify that it fails
* Save packages
* Verify success

Fix typo in property name.

---

classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-self-help-controller.php
classes/class-wc-rest-connect-services-controller.php
client/account-settings/state/actions.js
client/lib/save-form/index.js
client/packages/state/actions.js

Fixes #930
Well, this was easier than expected. `mod_security` most common set of rules, OWASP rules, block by default `PUT` and `DELETE` requests to the server. [Here it is the default rule](https://github.com/SpiderLabs/owasp-modsecurity-crs/blob/v3.0/master/crs-setup.conf.example#L329).
I've changed all our REST endpoints that use `PUT` to use `POST` instead. We can't afford the luxury of REST semantics purity if it's gonna break in the wild wide world of web hosting configurations.
To test:
* Install `mod_security` with the `OWASP` set of rules. I've pointed to some instructions in #930, ping me if you get stuck.
* Try to update the USPS config. Without this PR, it should give an instantaneous `Unexpected Server Error`. With this PR, it should work.
This one is particularly difficult …

Use only GET and POST HTTP methods to play nice with mod_security most common rules

---

classes/class-wc-connect-shipping-method.php

When looking at Automattic/woocommerce-connect-server#857 I noticed the following issue:
* use Canada Post instance
* try to request rates for a product with one of the dimensions set to 0 and weight set correctly
* server returns HTTP 200 with body like `{"rates":[{"id":"canada_post","instance":9,"error":"Error: Weight, length, width and height must be greater than zero but were: 0.45, 29.2, 0, 1.9"}]}`
* see no rates on the checkout page (or a fallback rate if configured)
* there's no `An error occurred in WooCommerce Services` notice in the admin panel
* nothing logged on the service status page
This PR fixes the issue. If the server returns HTTP 200 with errors for any individual instance (currently we always request one instance anyway), they will be logged and presented to the …

Logging individual rates instance errors

---

classes/class-wc-connect-service-settings-store.php
classes/class-wc-connect-shipping-label.php
woocommerce-services.php

This fixes the following error:
1. on an order page, open the label modal
2. wait until the address is normalized and rates are requested
3. refresh the page
4. scroll down and see the following fields: 
To test:
* follow the steps 1-3 from above
* the field should be hidden now
Backwards compatibility:
I prefixed the key with `_`, which should hide it automatically. I also added the unprefixed key to the hidden keys filter. Because of the former reopening old orders will trigger the normalization again, but it will only happen once and then the plugin will start using the prefixed key.

Hide the wc_connect_destination_normalized post meta key

---

package.json
readme.txt
woocommerce-services.php

Update plugin version to 1.3.2 and add change log entries
* Hide destination address normalized order meta
* Log rate retrieval failures as errors with admin notice

Version 1.3.2

---

classes/class-wc-connect-help-view.php
woocommerce-services.php

Fixes #941 and #972 
* Added link to https://woocommerce.com/my-account/create-a-ticket/ to the plugins page, showing under our plugin
* Replaced "report a bug" link on the System Status page with "open a support ticket" linking to https://woocommerce.com/my-account/create-a-ticket/ as well

Added support to the plugin actions links

---

client/shipping-label/state/reducer.js

Addresses a part of #976 
To test:
* use Firefox or similar browser
* purchase a label
* verify that clicking "Cancel" closes the modal
* reopening the modal should still show the "Print" button and allow to print the labels

Fixed cancel button behaviour when the label is ready to print

---

classes/class-wc-connect-shipping-label.php

Fixes #979 
To test:
* Example military address:
```
UNIT 2050 BOX 4190
APO AP 96278
```
* the orders placed with this address should not show the labels metabox
* for orders with any other address the Armed Forces "states" shouldn't be listed in the state dropdown in the labels modal

Filtering out military addresses from label purchases

---

client/shipping-label/state/actions.js
client/shipping-label/state/reducer.js
client/shipping-label/state/test/reducer.js

Fixes #944 
To test:
* purchase a label
* without refreshing the page, open the label modal again
* the rates should be re-requested
* purchase the label again
* verify there are no errors in the server log (there should be an error about repurchasing a shipment id in other branches)
This also fixes the flow in some of the browsers (such as Firefox):
* purchase a label, the button should change to "Print"
* it should now be possible to close the modal, and the button should still be "Print" on reopening (before it wouldn't be possible to close the modal)
* clicking print should close the modal and open a new tab with the label ready to print
* reopening the modal should trigger a new rates request and allow to repurchase a label, as outlined in the steps above

Fixed label repurchasing without page refresh

---

classes/class-wc-connect-shipping-method.php

Before:
* Predefined packages options (i.e which packages are enabled) were being stored with `usps` / `canada_post` as a key.
* For a checkout rates request, predefined packages options for the given method (`wc_services_usps` / `wc_services_canada_post`) were being fetched instead. Obviously, that always produced an empty list.
Fix: Use the `usps/canada_post` ID to fetch the predefined packages options from the user settings.
To test:
* Check that USPS predefined packages didn't work at all in `master`.
* Ccheck that now they work.

Fix retrieving predefine package definitions from the user's preferences

---

client/shipping-label/views/purchase/index.js

Fixes #976 
To test:
* on firefox open the label modal
* the purchase button label should be "Buy"
* purchase a label
* cancel button should disappear and the button label should change to "Print"
The resetting of available rates after closing will be handled in #974

Changing the purchase button label depending on browser pdf support

---

classes/class-wc-connect-compatibility-wc26.php
classes/class-wc-connect-compatibility-wc30.php
classes/class-wc-connect-compatibility.php
classes/class-wc-connect-shipping-label.php
classes/class-wc-rest-connect-shipping-label-controller.php
client/shipping-label/views/purchase/steps/packages/item-info.js
tests/php/test_woocommerce-services-compatibility.php

Fixes #982 
To test:
* As a user, buy a product, and checkout using WCS-provided rates.
* As an admin, delete said product entirely (not just "Trash").
* Go to the `Edit Order` page, try to buy a label.
You can also try purchasing / deleting a variation instead of a whole product, it's the same case.
In `master`: The item won't have a name in the `Packages` step, and after correctly purchasing a label for it, the PHP server will crash. That means that the merchant loses money and doesn't get a label.
With this PR: The item will have a (non-clickable) name in the `Packages` step, it will be `#123 - [Deleted product]`. The label purchase can get through without any problem. After that, in the `Labels` list, hovering over the label ID you will be able to see the same "name" in the package …

Don't break when printing a label for a non-existent product or variation

---

client/shipping-label/views/index.js

A small naming change to be consistent with the name we use to export and import the component.

Rename PurchaseLabelDialog to PrintLabelDialog

---

client/components/field-error/index.js

This change allows a user to specify an error type as a prop passed to `< FieldError />`.  The default error type is left as `input-validation`. The type is used to add the right CSS class.

Add custom error type to FieldError

---

client/components/number-field/number-input.js

React.createClass will be deprecated in React 16. This change updated `<NumberInput />` to use a js class instead.
Check that `<NumberField />` and `<NumberInput /`> are working as intended in these cases:
*in client/settings/views/services/entry.js* 
and *client/settings/views/wcc-settings-form/settings-item.js*
1. Go to WooCommerce (sidebar) > Settings (sidebar) > Shipping (top tab)
2. Click on a  WCS Shipping Method (link)
3. In the Rates section, open the Services to see the price adjustments
4. See the fallback rate
In *client/shipping-label/views/purchase/steps/packages/package-info.js*
1. Go to an order package and open the printing modal
2. Add a package - see the total weight input

Update NumberInput to use a JS class

---

classes/class-wc-connect-shipping-label.php

Fixes #1004 
WC_Connect_Shipping_Label::get_packaging_from_shipping_method() should always return an array.

Fix: PHP Error when order has no packing information 

---

assets/stylesheets/shipping-label.scss
assets/stylesheets/style.scss
client/shipping-label/state/reducer.js
client/shipping-label/state/selectors/errors.js
client/shipping-label/state/selectors/test/errors.js
client/shipping-label/views/purchase/steps/rates/list.js
client/shipping-label/views/purchase/steps/rates/test/list.js
karma.conf.js

- check rates prop exists before using it in the shipping-label reducer
- add server errors to `getRatesErrors` selector
- if there's an error sent from the server for a package's rates, show a `FieldError`
- add Enzyme tests for `<ShippingRates />`
Check out the [counterpart PR on the server](https://github.com/Automattic/woocommerce-connect-server/pull/802). Use the testing instructions there to simulate different responses to see the errors show up on the rates step. You can trigger a re-fresh of the rates by re-saving your packages on the modal :)
When there are no rates, only errors:
Where there is both a rate and an error (we don't currently support sending down both. if there are errors and rates we'll send only the rates - but there is good stylin' in just in case that situation …

Show errors in rate step

---

client/lib/calypso-boot/index.js

#1017 introduced a bug where setting the site language to anything other than Spanish or French would crash JS rendering and the following error would be logged in the console:
```
Uncaught TypeError: Cannot set property 'localeSlug' of undefined
```
This PR fixes it.
To test:
* load any of the WCS pages in English

Fixed a crash when booting calypso with non-existent locale JSON

---

classes/class-wc-connect-shipping-label.php

Orders with no packaging metadata had package ID collisions, which caused order items to be missing from the purchase label dialog.
To test:
* Manually create an order ("Add order") with two different products that will require shipping
* Verify that only one product shows in the Packages step of the label flow
* Check out this branch, refresh order
* Verify that both products show as in "original packaging" in the Packages step

Fix missing order items in purchase label dialog

---

client/shipping-label/views/purchase/steps/packages/add-item.js

Fixes #1025 
To test:
* open the labels modal
* remove an item from a package
* click "Add item" in a package
* confirm that the removed item is listed correctly

Labels - Fixed rendering of "Saved for later" items when adding to a package

---

woocommerce-services.php

Fixes #1020 
Fixes #1021 
Adds more checks to `can_accept_tos()` that resolve several issues:
- Check that `Jetpack_Data` class exists before attempting to access it
- Account for the possibility of `Jetpack_Data::get_access_token()` returning a non-object
- Allow any admin to accept TOS if in Jetpack Dev Mode
To Test:
- Start out with a fresh unconfigured install of Jetpack and WooCommerce Services
- Deactivate Jetpack (in master this will cause a crash, in this PR it won't)
- Activate Jetpack and set it to dev mode with `define('JETPACK_DEV_DEBUG', true);`
- Observer that TOS now appears
@jeffstieler @DanReyLop @marcinbot @v18

Fix issues in `can_accept_tos()`

---

classes/class-wc-connect-nux.php
classes/class-wc-connect-options.php
tests/php/test_class_wc-connect-nux.php

These are the scenarios that need to be handled:
<table class="table table-bordered table-hover table-condensed">
<tbody><tr>
<td>Install type</td>
<td>JP cxned</td>
<td>TOS accepted</td>
<td>First banner</td>
<td>After cxn banner</td>
<td>After TOS banner</td>
</tr>
<tr>
<td>New </td>
<td>No</td>
<td>No</td>
<td>Original before</td>
<td>Original after</td>
<td>N/A</td>
</tr>
<tr>
<td>New </td>
<td>Yes</td>
<td>No</td>
<td>TOS (new)</td>
<td>N/A</td>
<td>Original after</td>
</tr>
<tr>
<td>Update</td>
<td>No</td>
<td>No</td>
<td>Original before</td>
<td>Original after</td>
<td>N/A</td>
</tr>
<tr>
<td>Update</td>
<td>Yes</td>
<td>No</td>
<td>TOS (new)</td>
<td>N/A</td>
<td>Original after</td>
</tr>
<tr>
<td>Update</td>
<td>No</td>
<td>Yes</td>
<td>Original before</td>
<td>Original …

Update NUX flow logic for all scenarios

---

assets/stylesheets/style.scss
classes/class-wc-connect-nux.php
classes/class-wc-connect-shipping-label.php
client/admin-pointers.js
client/shipping-label/index.js
client/shipping-label/views/index.js
woocommerce-services.php

This PR adds a pointer that highlights the shipping labels metabox. Details of features implemented:
- Added a new pointer to the labels metabox
- Added divs, css and jQuery for dimming everything but the metabox and pointer on the orders page
- Metabox now displays different text depending on if the user has any payment methods
- Added a numPaymentMethods field to redux init data for the above feature
- Implemented MySQL query to detect if the store has already created labels and therefore doesn't need to see the pointer.
Other questions:
- Did I add the CSS in the right place?
- I felt that a direct `show()` was abrupt so I faded the dimming in and out. @olaolusoga ?
To Test:
- For the user you're testing, make sure you've deleted `dismissed_wp_pointers` from usermeta
- Either have a …

Add order page pointer to shipping labels

---

classes/class-wc-connect-nux.php

Fixes #1043 
- Fixes broken HTML from a bad rebase
- Adds a missing period at the end of a sentence. 
To Test:
- On a fully setup site, The message should pop up you simply deactivate the Jetpack plugin

Fix broken TOS links

---

classes/class-wc-connect-nux.php
client/admin-pointers.js

Fixes #1047 
No, you can't pass a string to a WordPress hook. It must be a function.

dimmer div not rendered correctly

---

classes/class-wc-connect-nux.php

Fixes #1045 
This will help avoid checking the database in the future.

Add labels metabox to the dismissed pointers list if the user is not new

---

classes/class-wc-connect-nux.php
woocommerce-services.php

This makes sure we don't do things like enabling our features or talk to the server until the TOS has been accepted.
To Test:
- If you have TOS accepted already you can either disconnect jetpack or remove dev mode and plugin features like the labels metabox should disappear.

disable plugin features if no tos

---

client/print-test-label/index.js

Fixes #1003.
Add expected method `getStateKey()` to label test print route class.
The lack of this method caused an error preventing the test label help section from rendering.
To test:
* Verify the test label print control renders on the self help page, and functions properly

Fix test label printing on self help page

---

classes/class-wc-connect-nux.php

This PR updates the text of the JITM banners as discussed. I had to remove the use of `esc_html()` from the `show_nux_banner()` in order to embeded links in the text.
To Test:
- Review the text changes according to the google doc.
- If you want to see it live, you'll need to trigger all of the banners.

Update JITM Copy to Latest Version

---

classes/class-wc-connect-nux.php
classes/class-wc-connect-tracks.php
tests/php/test_woocommerce-connect-tracks.php
woocommerce-services.php

Fixes #1057.
This PR seeks to reestablish tracking of TOS acceptance. In addition to that goal, it:
* Adds an optional "source" parameter to the `opted_in()` helper method
* Attaches shipping method related tracks hooks explicitly, rather than on instantiation
* Tracks TOS accept from "TOS only" banner and "connect" banner separately

Fix tracking of TOS acceptance

---

classes/class-wc-connect-nux.php
tests/php/test_class_wc-connect-nux.php

Fixes #1058.
To test:
* Make sure TOS isn't accepted
* Log in with Jetpack master user
* Verify TOS banner displays
* Log in with different user (with `manage_woocommerce`, `install_plugins`, `activate_plugins` caps)
* Verify no TOS banner
* `define( 'JETPACK_DEV_DEBUG', true );`
* Verify TOS banner displays

Restrict TOS acceptance to Jetpack master user

---

classes/class-wc-connect-nux.php

Fixed #1068
Steps to repro:
To see the bug: 
1. Start with `q2-nux`
2. Remove the `tos_accepted` option
3. Deactivate Jetpack
4. See before banner
5. Go to the Jetpack admin page and connect to Jetpack the Jetpack process, not the WCS process
6. See the after-connection banner and `tos_accepted` set to true (if it wasn't before)
To see the fix:
1. Checkout this branch
2. Remove the `tos_accepted` option
3. Deactivate Jetpack
4. See before banner
5. Go to the Jetpack admin page and connect to Jetpack the Jetpack process, not the WCS process
6. See the TOS banner when you get back
Other tests: make sure that the usual connection process works:
1. TOS-only banner should work
2. Before + after connection banner should work as usual

Show TOS-only banner if connect button not clicked

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-taxjar-integration.php
tests/php/test_woocommerce-connect-client.php
woocommerce-services.php

Fixes #1035.
**Note: this changes the WCS init hook from `woocommerce_init` to `before_woocommerce_init` in order to augment the TaxJar integration**
To test:
* Set up a local server with `add/taxjar-api-proxy` checked out
* Set values for `woocommerce_store_city` and `woocommerce_store_postcode` in `wp_options` table
* Enable tax calculation
* Install and activate the TaxJar plugin
* Verify that taxes are shown at checkout / in cart

Proxy TaxJar requests through the WCS Server

---

classes/class-wc-connect-payment-methods-store.php

Never select a credit card before user interaction, and only auto-update cards when they change if one had been previously selected.
Fixes #1073.
To test:
* Start with a new WCS install, or clear out your stored payment method ID setting
* Verify that on Settings > Shipping > Labels, no CC is checked
* After saving a CC, set the setting ID to `0` in the database
* Verify that on Settings > Shipping > Labels, the first CC is checked

Better label payment method UX

---

client/shipping-label/views/index.js

Fix for https://github.com/Automattic/woocommerce-services/issues/1080.
Before:
After:
Expanded i18n string can now support RTL and verb-final languages (thanks @jeffstieler).

Add proper spacing to label "purchased" text by translating whole phrase

---

classes/class-wc-connect-shipping-label.php
tests/php/test_class-wc-connect-shipping-label.php

Fixes #1075.
This is specifically meant to handle a WC 3.1.0 bug, but adds general resilience to shipping labels.
To test:
* Check out with a WCS-provided live rate using WC 3.1.0
- OR -
* Edit an existing order item metadata `wc_connect_packages` to be `a:1:{i:0;N;}`
* Go to order details page
* Verify that no PHP warnings are displayed / in error log
* Verify that label dialog can be opened

Handle corrupted or empty packaging metadata.

---

client/shipping-label/state/actions.js
client/shipping-label/views/purchase/steps/packages/get-package-descriptions.js
client/shipping-label/views/tracking-link.js
npm-shrinkwrap.json
package.json

As a part of bringing WCS in line with Calypso we want to revise the non-dev dependencies we use. This will allow to bring our components over to Calypso more easily.
`sprintf` was a low hanging fruit and can be replaced either by built-in JS methods or `i18n-calypso` methods.
To test:
* verify that the labels load
* tracking links should be of a correct format
* label refund can be requested
* package names are shown correctly in the label modal (package list on the left in the packages step, and package names above the price dropdown in the rates step)

Removed sprintf-js from the list of dependencies

---

classes/class-wc-connect-service-settings-store.php

This PR shouldn't affect any of the plugin's UI.
The `enabled` flag will be used in Calypso to control whether to show the label settings and potentially the label controls on the order page
To test:
* verify that you can open and save the label settings (payment method, paper size)

Added enabled flag to the account/label payments settings

---

client/shipping-label/state/actions.js
client/shipping-label/state/reducer.js
client/shipping-label/state/test/reducer.js

Fixes: #1016.
This PR seeks to avoid accidental clicks of the "buy" button after a label has successfully been purchased, but before the modal dismisses.
It also adds some tests for the `PURCHASE_LABEL_RESPONSE` reducer.
To test:
* Throttle network connection (see issue comments)
* Buy label in native PDF supporting browser (Safari or Chrome)
* Verify that there is no opportunity to click the "buy" button again
* Verify that non-native PDF supporting browsers still work for purchasing label (Firefox)
* Verify that tests pass

Persist “purchasing…” button until label modal is dismissed.

---

assets/stylesheets/shipping-label.scss
client/shipping-label/views/index.js

Currently, label data is available on first render of the shipping label view, but none is being displayed until all of the labels' data is individually updated from the server. `statusUpdated` is the property being checked for, referring to the refund status as I understand.
Under the general assumption that the cached data will tend to be up to date, and the specific assumption that a carrier refund completion is the only unexceptional case where it could be out of date — let me know if either of these is unfounded — I've replaced showing a spinner with rendering the labels straight away, with the exception of the refund status value of "pending".

Render shipping label list ahead of refund status update

---

assets/stylesheets/style.scss
classes/class-wc-connect-settings-pages.php
client/components/checkbox/style.scss
client/packages/state/reducer.js
client/packages/state/test/reducer.js
client/packages/views/add-package.js
client/packages/views/packages-list.js
client/packages/views/style.scss

- Slightly increase maximum width of `.wcc-root` to match Calypso form width
- Change 'Shipping Labels' to 'Shipping labels' for consistency
- Increase margin above packages and labels settings forms
- Add margin to form section header in Packages settings
- Improve alignment and wrapping of 'Custom packages' table headers (should fix https://github.com/Automattic/woocommerce-services/issues/936)
Before | After
-- | --
- Improve alignment of checkboxes to text
- Avoid 'Edit package' dialog flickering to 'Add a package' dialog upon closing
Before:
After:

Appearance and alignment tweaks in WC Settings

---

client/shipping-label/state/actions.js
client/shipping-label/state/reducer.js
client/shipping-label/state/test/reducer.js
client/shipping-label/views/purchase/steps/packages/add-item.js
client/shipping-label/views/purchase/steps/packages/index.js
client/shipping-label/views/purchase/steps/packages/move-item.js

Fixes: https://github.com/Automattic/woocommerce-services/issues/1033
Allows adding one _or more_ items to a package at once by using checkbox controls instead of radio buttons.
Before:
After:
Also disables the primary action button (for this dialog and the "Move" dialog) if no selection is made, indicating that no consequential action has been selected.

Enhance "Add Item" dialog by allowing multiple items to be checked

---

client/shipping-label/state/reducer.js
client/shipping-label/state/test/reducer.js

Avoids floating point arithmetic artifacts (such as `9.879999999999999`) being stored and displayed in the Total Weight value when moving items around in the shipping label dialog.
Before:
After:

Maintain fixed precision of weight values when moving items among packages

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-help-view.php
classes/class-wc-connect-jetpack.php
classes/class-wc-connect-nux.php
classes/class-wc-connect-settings-pages.php
classes/class-wc-rest-connect-account-settings-controller.php
woocommerce-services.php

This is part of the work on automattic/wp-calypso#16958
I made the following changes in this PR:
* moved all Jetpack utils to a single static class `WC_Connect_Jetpack`
* in `class-wc-rest-connect-account-settings-controller.php` I perform the same checks as when the account settings page is rendered to verify if the current user is a master user and if they can manage payments
To test:
* everything should work as before, especially on the accounts page
* in dev mode, Jetpack will not return a master user
* I tested the API changes by uploading the updated version of the plugin to my AT site. I got the following in the response when logged in as non-master: `"can_manage_payments":false,"master_user_name":"botmarcin","master_user_login":"botmarcin"`, which is as expected

Checking the Jetpack master user in account settings REST endpoint

---

client/apps/shipping-label/components/label-purchase-modal/rates-step/list.js
client/apps/shipping-label/components/label-refund-modal/index.js
client/apps/shipping-label/state/selectors/rates.js

Likely patches https://github.com/Automattic/woocommerce-services/issues/1078 superficially, though there may well be a more substantial fix available upon understanding why `refundable_amount` might be something other than a `Number` since it is likely indicative of a broader failure case.
Don't know how to reproduce the issue at this point. I identified the suspect primarily because it's the only piece of code in the repository fitting the reported pattern (i.e. `variable.toFixed(2)`). Can either ship this patch or modify the PR with a different solution based on feedback.

Cast refundable_amount to address "toFixed is not a function" bug

---

classes/class-wc-rest-connect-shipping-label-print-controller.php
client/lib/pdf-label-utils/index.js

Fixes #1111 
This was caused by the label IDs and their captions being passed as arrays in GET string. Some plugins try to call `kses` on all query params. With Jetpack, this could produce a warning if one of the params has been already converted to an array.
To test:
* check that a single label can be printed
* check that multiple labels can be printed
* optional
* Activate the `shortcode embeds` module at `/wp-admin/admin.php?page=jetpack_modules`
* Install an offending plugin (see slack channel for details p1501775680572853-slack-hydra )
* verify that everything still prints
@melindahelt @v18

PDF printing - Fixed a conflict with plugins that try to pass arrays to kses

---

woocommerce-services.php

Fixes #1101 
The removed line is a duplicate of a line that is hit after TOS has been accepted. I checked and `load_admin_dependencies()` didn't contain anything that would be necessary before the TOS.
To test:
* ensure the `tos_accepted` option is set to false in the database by editing `wc_connect_options` in `wp_options`
* the NUX notice should show
* verify that the WC Services menu entries are not visible on the shipping settings and status pages

Not loading admin dependencies before TOS has been accepted

---

client/apps/account-settings/view.js
client/apps/shipping-label/components/label-refund-modal/index.js

Fixes https://github.com/Automattic/woocommerce-services/issues/1118 by generalizing the post-"save" notifications beyond "payment method", which is no longer the only available setting.
After changing "Paper size" to "Legal" and saving:

Generalize save notifications for shipping label settings

---

classes/class-wc-connect-shipping-label.php
classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-shipping-label-controller.php
classes/class-wc-rest-connect-tos-controller.php
client/api/index.js
client/api/request.js
client/api/url.js
client/apps/print-test-label/state/actions.js
client/apps/shipping-label/components/label-refund-modal/index.js
client/apps/shipping-label/index.js
client/apps/shipping-label/state/actions.js
client/apps/shipping-label/state/get-rates.js
client/apps/shipping-label/state/normalize-address.js
client/apps/shipping-label/state/reducer.js
client/apps/shipping-label/view.js
client/components/query-labels/index.js
client/lib/initialize-labels-state/index.js
client/lib/pdf-label-utils/index.js
woocommerce-services.php

Fixes #1103
This is a prerequisite to start moving the label modal component to Calypso. I also cleaned up some of the code in the last two commits.
To test:
* everything should work correctly:
* address normalization
* label rates request
* label purchase and print
* label refund
* to test the dynamic fetch, replace `$payload = $this->get_label_payload( $order );` with `$payload = array()` in `class-wc-connect-shipping-label.php`
* a spinner should appear while the data is being requested
* everything should work once the data has been loaded

Label Modal - using the api module instead of saveForm

---

client/apps/shipping-label/state/reducer.js
client/apps/shipping-label/state/test/reducer.js

Fixes https://github.com/Automattic/woocommerce-services/issues/1071. If you modify the weight and then change the package type, it'll keep (or adjust, depending on box weights) the weight you entered.

Take into account current package weight when setting package type

---

classes/class-wc-rest-connect-shipping-label-preview-controller.php
client/api/url.js
client/lib/pdf-label-utils/index.js

This is blocking the 1.7 release 😬 
https://github.com/Automattic/woocommerce-services/pull/1121 broke printing test labels from the WC status page.
This PR restores test label printing and updates the label preview controller to work with CSV captions introduced in https://github.com/Automattic/woocommerce-services/pull/1112.
To test:
* Verify that the test label print works
* Verify that reprinting a purchased label still works

Fix test label printing

---

classes/class-wc-connect-service-settings-store.php
classes/class-wc-rest-connect-shipping-label-controller.php
classes/class-wc-rest-connect-shipping-label-status-controller.php
client/apps/shipping-label/state/actions.js
client/apps/shipping-label/style.scss
client/apps/shipping-label/view.js

Fixes #1120 
To test:
* Checkout the server PR: Automattic/woocommerce-connect-server#959
* Purchase a single label
* Purchase multiple labels
* Hack the server by throwing an error at any step in `lib/shipping/handler.js` and verify that the errors are handled properly in the client
* ~~If the page is refreshed during the purchase or after an error, this should show in the label history~~ (will be handled in #1135)

Support for async label purchases

---

classes/class-wc-connect-shipping-label.php

Fixes https://github.com/Automattic/woocommerce-services/issues/1142 by adding the `enabled` flag to the shipping label payload. Also returns no other data if not `enabled`.

Adjust the label payload to respect whether shipping labels are enabled

---

client/components/error-notice/index.js

Small change fixing a React console warning.
To test:
1. Go to Edit Order page
2. Open label purchase modal
3. Open dev console
4. Use an address that'll show a suggested change
5. See error
6. Check out this branch, follow steps 1-4 and see no error

Fix typo in prop type for ErrorNotice

---

client/apps/shipping-label/components/label-item/index.js
client/apps/shipping-label/components/label-purchase-modal/address-step/fields.js
client/apps/shipping-label/components/label-purchase-modal/address-step/index.js
client/apps/shipping-label/components/label-purchase-modal/index.js
client/apps/shipping-label/components/label-purchase-modal/packages-step/add-item.js
client/apps/shipping-label/components/label-purchase-modal/packages-step/index.js
client/apps/shipping-label/components/label-purchase-modal/packages-step/item-info.js
client/apps/shipping-label/components/label-purchase-modal/packages-step/list.js
client/apps/shipping-label/components/label-purchase-modal/packages-step/move-item.js
client/apps/shipping-label/components/label-purchase-modal/packages-step/package-info.js
client/apps/shipping-label/components/label-purchase-modal/packages-step/style.scss
client/apps/shipping-label/components/label-purchase-modal/rates-step/index.js
client/apps/shipping-label/components/label-purchase-modal/sidebar.js
client/apps/shipping-label/components/label-refund-modal/index.js
client/apps/shipping-label/components/label-reprint-modal/index.js
client/apps/shipping-label/style.scss
client/apps/shipping-label/view.js

Encapsulates `shipping-label/view` code that pertains to a single label item into a `LabelItem` component, and connects subcomponents to the state tree instead of passing everything as props from the top-level container.
cc @v18

Refactor shipping label code to use child containers

---

client/apps/shipping-label/components/label-reprint-modal/index.js

Makes sure to render only a single Reprint dialog at a time. Multiple dialogs are harmless but result in opaque overlay:
Before | After
-- | --

Avoid rendering a Reprint dialog for each label

---

client/apps/account-settings/components/label-settings/index.js

Fixes https://github.com/Automattic/woocommerce-services/issues/1116 by adjusting existing description for credit card label settings so that the reason for it is harder to miss.

Re-word description for credit card settings to emphasize purpose

---

client/apps/shipping-label/components/label-purchase-modal/address-step/index.js
client/apps/shipping-label/components/label-purchase-modal/packages-step/package-info.js
client/apps/shipping-label/view.js

Fixed some problems that were missed in #1144 
To test:
* the order page should show no react warnings on load
* the label modal should show no react warnings
* everything in the modal should render and work properly (esp. package weight change)

Fixed React warnings on the label print page

---

classes/class-wc-connect-shipping-label.php

Fix variable name typo.
This prevented order detail pages from loading when the order contained a deleted product.
cc: @WillBrubaker

Fix: deleted product results in fatal error.

---

classes/class-wc-connect-help-view.php
client/api/url.js
client/apps/settings/state/actions.js
client/apps/settings/state/values/actions.js
woocommerce-services.php

Refactor shipping settings form URL generation to be a generic settings form URL method.
This allows for separate handling of other forms that use the SettingsForm components, like the Status page debug toggle.
To test:
* Verify that shipping method form saving works
* Verify that toggling debug on Status page works

Fix debug toggle on Status page.

---

classes/class-wc-connect-options.php
classes/class-wc-connect-taxjar-integration.php
woocommerce-services.php

This PR seeks to:
* Remove the dependence on a separate TaxJar plugin
* Only integrate sales tax calculation - order syncing and nexus functionality is not required
To test:
* Ensure your store is in a supported country ([#](https://developers.taxjar.com/api/reference/#countries))
* Go to WooCommerce > Settings > Tax and enable "Automated taxes"
* Verify that any previously configured tax rates have been exported to CSV (uploads dir)
* Verify that taxes are calculated in cart (behavior will vary based on store location)
* Verify that taxes are calculated for manually created orders in the dashboard
cc: @allendav

Update TaxJar proxy to full integration

---

woocommerce-services.php

Creates a stripe account if user opts for it in WooCommerce setup wizard.
To test:
- Set `WOOCOMMERCE_CONNECT_SERVER_URL` to WCS staging server URL: `https://api-staging.woocommerce.com/` (p90Yrv-e4-p2 "Zip, upload and activate this plugin to your test site")
- In the Payments step (using WooCommerce 3.2.0 RC 2 — `/wp-admin/admin.php?page=wc-setup&step=payment`), check "Create an account for me using this email:" and continue to the next page
- In WooCommerce -> Settings -> Stripe, verify that test keys are filled in
- If not, verify that WooCommerce Stripe Gateway plugin is active, and refresh (any) page
Questions:
- How to handle "account already exists for email" error, ahead of oauth key retrieval implementation?
- How to handle other errors?
- If email is empty, should it use WP user …

Create stripe account based on Setup Wizard choices

---

woocommerce-services.php

Fixes #1176.
To test: _(on an already-connected test site)_
* Set `tos_accepted` option to `0`
* Verify that TOS banner shows (Plugins page, WooCommerce pages)
* Set `woocommerce_setup_jetpack_opted_in` option to `1`, Refresh
* Verify that TOS banner doesn't display, and `tos_accepted` option has been set to `1`

Migrate Jetpack TOS acceptance that occurs in the core setup wizard.

---

classes/class-wc-connect-taxjar-integration.php

In the Extras step of the WooCommerce setup wizard, the automated taxes choice wasn't being honored because the wizard [sets `woocommerce_setup_automated_taxes` option to "1"](https://github.com/woocommerce/woocommerce/blob/1831d7ec37ea53ed865de335aa706eada71de030/includes/admin/class-wc-admin-setup-wizard.php#L1379) instead of "yes". This change loosens the condition.
To test, go through wizard and select "Automated taxes" in the Extras step. After completing the wizard, ensure that automated taxes are enabled (`/wp-admin/admin.php?page=wc-settings&tab=tax`, top setting).

Check for truth of "automated taxes" option (set by wizard) rather than specific value

---

woocommerce-services.php

To test:
* With Jetpack connected
* On `master`, ensure that you have `create_account`, `enabled` and `email` set in `woocommerce_stripe_settings` (use a **new** email for this)
* Enable WCS (or just refresh an admin page)
* Verify that an error is logged that the account already exists
* Ensure the `woocommerce_stripe_settings` values (again, **new** email)
* Enable WCS (or just refresh an admin page)
* Verify that no existing account error is logged, and that Stripe has API keys

Fix duplicate initializations of setup wizard choices (payment + settings).

---

classes/class-wc-connect-jetpack.php
woocommerce-services.php

Because the "Ecommerce" section of the [WP.com TOS](https://en.wordpress.com/tos/) covers the functionality of this plugin, we can check if the site is an Atomic site as a condition for auto-accepting the TOS and proceeding.
To test, a) install/activate on Atomic site (use `npm run release` and upload ZIP) and verify plugin is functional without any TOS prompt, and b) activate on non-atomic site and verify that TOS prompt still shows up once Jetpack is activated (outside of WC wizard), and plugin doesn't work until TOS accepted, as before.
Note: `jetpack_is_atomic_site` appears to be somewhat of an undocumented function intended for internal use — it was actually [renamed](https://github.com/Automattic/jetpack/pull/7729) from `jetpack_is_automated_transfer_site` in Jetpack 5.4 — is there …

Add TOS bypass for Atomic sites

---

classes/class-wc-connect-help-view.php
client/apps/settings/components/settings-form/settings-item.js

Modify status indicator schema to fit with refactored object schema handling in 012abb8050fbe0c6fc59338f9756f2502cf72dcd.
This is to be considered temporary - eventually we’ll remove the data-driven aspects of the status page.
To test:
* Verify that the self help (status) page renders as expected

Modify status indicator schema to fit with refactored object schema handling

---

classes/class-wc-rest-connect-shipping-label-print-controller.php

If the `conect/label/print` request has a POST parameter `"json": true`, instead of spitting the raw PDF, the endpoint will return a regular json, like this:
```js
{
"mimeType": "application/pdf",
"b64Content": "...THE....BINARY....PDF....CONTENT.....ENCODED...IN...BASE64...."
}
```
Printing from `WP-Admin` shouldn't be affected by this, this change is only for requests coming from `wp-calypso` (which will have the `json` flag set to `true`).

Return the PDF in JSON format (base64-encoded) if the "json" parameter is set

---

client/lib/utils/pdf-support.js

Mobile Safari and Chrome are smart enough to determine that `window.open` originated from a user click and is opening the pdf in a new browser tab.
Tested and working on:
- iPhone 6S (iOS 9.0, Mobile Safari)
- iPad Air 2 (iOS 8.0, Mobile Safari)
- iPad Air 2 (iOS 11, Mobile Safari)
- iPad Air 2 (iOS 11, Chrome)

🐛 Fix label printing on iOS [#1166]

---

classes/class-wc-connect-nux.php

Fixes #1188.
This PR seeks to restore the TOS-only banner (with new verbiage) that doesn't redirect to WPCOM.
It also adds the "should display" logic to the TOS-only banner, so it doesn't display on every admin screen. (The idea being that will help with "nag" complaints)
To test:
* Ensure a connected Jetpack
* Either remove the WCS plugin (and options), or set `wc_connect_options.tos_accepted` to `0`
* Verify that on NUX banner pages (plugins, WC pages) the TOS-only banner shows
* Verify that clicking "connect" dismisses the banner and sets `wc_connect_options.tos_accepted` to `1` and doesn't send you to WPCOM

Fix TOS-only banner - remove connection flow

---

woocommerce-services.php

Fixes: https://github.com/Automattic/woocommerce-services/issues/1193
Avoids fatal error when shipping method is unavailable due to mismatch between country and currency, by adapting to the server's recently introduced mapping by _currency_ (rather than _country_ as initially established in https://github.com/Automattic/woocommerce-services/pull/1165.)
Also hardens `add_method_to_shipping_zone` by making sure the method and method instance exist before proceeding to configure them.
To test, set country to US or CA but currency to something other than USD or CAD — confirm that the wizard is completed without WCS-derived fatal error.

Map currency instead of country to shipping method in post-Wizard config init

---

client/apps/shipping-label/view.js

The payment method is null when it hasn't been entered yet, so it should not be a required prop.
Fixes this error:

Make paymentMethod not required for labels view

---

classes/class-wc-connect-service-settings-store.php

Fixes #1079
Fixes an issue raised by @kellychoffman in https://github.com/Automattic/wp-calypso/pull/18281#issuecomment-332969186
When no labels have been printed before and WC version is 3.1.1 or newer, the address supplied in the WC settings should be used.
To test:
* Delete `wc_connect_origin_address` option from the `wp_options` table in your DB
* Ensure that you're using WC v>3.1.1 and that an address was supplied
* Load an order page and verify that the labels origin address is the same as the address in WC settings

Using WC store address as default when printing labels

---

classes/class-wc-rest-connect-stripe-account-controller.php
classes/class-wc-rest-connect-stripe-deauthorize-controller.php
classes/class-wc-rest-connect-stripe-oauth-connect-controller.php
classes/class-wc-rest-connect-stripe-oauth-init-controller.php

Fixes #1203 
To Test:
* Install this branch as a plugin on a pressable site or other site that returns HTML for 500s
* Install the stripe connect test bench
* Navigate to https://{DOMAIN}/wp-admin/admin.php?page=wc-status&tab=sctbs
* Click each of the buttons and ensure JSON is returned even for errors (i.e. not HTML), e.g.
```
{"code":"wcc_server_error_response","message":"Error: The WooCommerce Services server returned: Bad Request Account already exists for the provided email. ( 400 )","data":{"status":400}}
```

Do not allow default 500 to be returned by stripe rest api endpoints

---

woocommerce-services.php

Should address https://github.com/Automattic/woocommerce-services/issues/1194 in the typical case, by skipping the wizard config initialization functions in requests that are made subsequent to the initial (i.e. primary) request.
Testing the broader effect is tricky since the multiple requests reported in https://github.com/Automattic/woocommerce-services/issues/1194 are not reliably reproducible, but the condition passing only once per page load can be verified by logging inside the `if` statement.

Limit wizard config init calls to user-initiated requests only

---

client/apps/shipping-label/style.scss
client/apps/shipping-label/view-wrapper.js

This PR:
- hides the two options in the label purchase flow modal sidebar
- sets them to false
cc @DanReyLop @marcinbot

Do now allow emailing or marking order as complete

---

client/lib/utils/coerce-values.js
client/lib/utils/test/coerce-values.js

Steps to repro:
Go to WooCommerce > Settings > Shipping zones > [one of your shipping zones] > Edit when there have been no USPS services selected for the zone.
You'll see this:
This is the error:
> TypeError: Cannot convert undefined or null to object
> Object.keys( value )
It happens in https://github.com/Automattic/woocommerce-services/blob/master/client/lib/utils/coerce-values.js#L65 when the `value` argument of `coerceValue()` is equal to null.
I added a test to explain what I mean & to prevent regression.

Avoid coercing null to object in coerceFormValues

---

classes/class-wc-connect-jetpack.php

This PR allows us to auto-authenticate users going through the Jetpack connection flow with these two changes:
1. New 'from' GET parameter value so that Calypso can decide when a user can be auto-authorized when connecting to Jetpack.
2. The Jetpack connection banner to show a new URL describing the data that Jetpack collects when it's connected.
Here's a video showing what it looks like:
https://cloudup.com/cpZ-fOFL7yV
Background info: p7bbVw-1Rl-p2
1. Install Jetpack on your site, and deactivate it
2. In the file `class.jetpack.php`, find the function `build_connect_url` and add this line to it right above `return $raw ? $url : esc_url( $url );`:  `$url = add_query_arg( 'calypso_env', 'development', $url );`
3. Check out the branch `update/wcs-jp-flow` in Calypso - …

Allow auto-authorizing Jetpack connections

---

classes/class-wc-connect-stripe.php
woocommerce-services.php

~Adds [metadata](https://stripe.com/docs/api#metadata) (key: `connect`, value: `1`) to~ Removes User-Agent from Stripe requests from accounts created via WCS after WooCommerce setup wizard opt-in (discussion in p7bbVw-1Rh-p2)
Requires WooCommerce Stripe Payment Gateway 4.0.0 ([latest](https://github.com/woocommerce/woocommerce-gateway-stripe/tree/4.0.0)) but shouldn't break without it — tested by logging request data in the Stripe plugin's [API class](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/e0ac1c3c28e8718810e5c2ffd0ae84d411e415a4/includes/class-wc-stripe-api.php#L101).

Add metadata to distinguish Stripe referral vs. connect requests

---

classes/class-wc-connect-shipping-label.php
npm-shrinkwrap.json
woocommerce-services.php

Fixes #1129
According to #846 no customs forms are needed for these regions, so we should be able to print labels for them as usual.
To test:
* place an order with an address from Puerto Rico or Virgin Islands (US)
* on the order page, the label metabox should appear
* you should be able to purchase and print a label just like for mainland states
Note:
* the address validation can be a bit picky when it comes to the addresses from there but it does work

Added support for labels to PR and VI

---

client/apps/shipping-label/view-wrapper.js

To test:
* on `master`, pull up an order with no labels created
* verify that `No activity yet` is displayed in the labels metabox
* check out `fix/remove-empty-activity-log`
* refresh order
* verify that the `No activity` text is *not* displayed
* open an order with a label
* verify that the order events are displayed

Labels metabox: Only render ActivityLog component if there are order events.

---

client/api/index.js
client/api/request.js

Error introduced in 653853a1ba548627eb23314156ada418964212ed.
To test:
* Saving shipping method instance fails on `master`
* Toggling "debug" fails on `master`
* Verify this branch fixes

Fix non-Calypso-sourced component usage of request.js.

---

woocommerce-services.php

Fixes #1241
Even when Jetpack isn't installed, the admin_enqueue_scripts function is run, so we can't assume that the `JETPACK__VERSION` constant is available. Since it's only used to put a cache-bustin querystring on the `noticons.css` URL, it's safe to replace with a dummy value if Jetpack is not available.
To test:
* Make sure `WP_DEBUG` is `TRUE`.
* Disable or uninstall Jetpack.
* Check that there's no `Undefined constant JETPACK__VERSION` PHP warning after visiting any WP-Admin page.

Fix "undefined JETPACK__VERSION" warning

---

classes/class-wc-connect-nux.php
client/admin-pointers.js

Fixes typo in code: `wcSevicesAdminPointers` -> `wcServicesAdminPointers`. Not quite user-facing, but it does appear in the page source.

Fix code typo: wcSevicesAdminPointers

---

client/api/request.js

Fixes #1260
The bug was introduced in `1.9.0`, when we hybridized the extension. The plugin code is using the `api.js` module from `wp-calypso`, and that handles URL structures differently.
This is the minimal change, I have prepared a more comprehenxsive fix that cleans up some code, but I figured I should leave that for the release after we unfreeze the code.
To test:
* Go to `Settings -> Permalinks` and select the option `Plain`.
* Try to purchase or reprint a label. It should work.

Fixes the URL to print a label when the "Permalink" setting is off

---

classes/class-wc-connect-help-view.php

Fixes #462 
Adds a "Refresh" link next to the service data status:
Clicking on it should attempt to fetch the schemas. Any errors should appear in the debug log (if enabled)

Added a control to refresh service schemas

---

classes/class-wc-connect-service-settings-store.php
classes/class-wc-connect-shipping-label.php

https://github.com/Automattic/wp-calypso/pull/20510 and server's 1011 remove the phone field requirement.
This means that the frontend needs a way to detect whether an address has been filled in by the merchant and normalized without checking the phone field. The "filled in" part is easy - just check each required field (done in Calypso). The destination already has a flag that determines if the address has been normalized. This adds a similar flag for the origin address.
To test:
* checkout https://github.com/Automattic/wp-calypso/pull/20510
* in this branch of WCS ensure that you `npm link` to the Calypso branch
* checkout server PR 1011
* delete `wc_connect_origin_address` to simulate unnormalized origin address
* verify that the normalization is started for the origin address when the …

Returning an origin normalized flag to avoid using the phone field

---

classes/class-wc-connect-stripe.php

Reverts https://github.com/Automattic/woocommerce-services/pull/1199
No change to headers in Stripe Connect accounts' requests is necessary at this point. (Discussion in p7bbVw-1Rh-p2.)

Restores user-agent header in connected accounts' Stripe requests

---

classes/class-wc-connect-shipping-label.php

Fixes #959 and allows label printing from Puerto Rico.
To test:
* Set your store's country to Puerto Rico
* Verify that label metabox shows on an order
* Set your store's currency to BTC
* Verify that label metabox does not show on an order (that doesn't already have labels printed)

Labels: check USD and allow all supported countries (PR)

---

woocommerce-services.php

See the new headers explained here: https://woocommerce.wordpress.com/2017/08/28/new-version-check-in-woocommerce-3-2/
WooCommerce `3.3` isn't out yet, but I've been using WooCommerce `master` since a few months ago and I haven't noticed any breakage. Should we declare support for `3.3`, or do you guys think we should wait until `3.3` is closer to be released?

Added headers to indicate support for WooCommerce up to 3.3

---

classes/class-wc-connect-compatibility-wc26.php
classes/class-wc-connect-compatibility-wc30.php
classes/class-wc-connect-compatibility.php
classes/class-wc-connect-shipping-method.php

Fixes https://wordpress.org/support/topic/bug-variations-arent-put-into-packages/
The problem visualized:
To test:
* Add at least one simple product to cart
* Add at least one variable product to cart (choose a variation if there is a parent)
* Checkout
* Verify that the "Packaging" section of the order details contains all product names

Fix variation names in "Packaging" line item

---

classes/class-wc-connect-nux.php

Fixes #1282 
To test:
* create a multisite
* add a new site with a new user as admin
* as a superadmin install and activate WooCommerce, Jetpack and WCS (do not connect Jetpack)
* view the site as admin and verify that the NUX banner is visible and can be connected
* the rest of the plugin should work for the admin

Improved the logic for NUX banners on multisites with Jetpack installed

---

classes/class-wc-connect-jetpack.php
classes/class-wc-connect-service-settings-store.php
classes/class-wc-rest-connect-account-settings-controller.php

Adds the email receipts option to the settings endpoint.
See https://github.com/Automattic/wp-calypso/pull/21726 for test steps

Added an email receipts setting option

---

webpack.config.js

Changes the webpack config to modify the image URLs in CSS to point at wordpress.com instead of importing whole base64 or SVG strings.
To test:
* check that the images render correctly on the payments methods page
* verify that other areas of the plugin look ok (payment methods is the only area that uses images)

Referencing CSS images from wordpress.com

---

assets/stylesheets/_colors.scss
npm-shrinkwrap.json
package.json
webpack.config.js

Sets the Calypso dependency to the commit https://github.com/Automattic/wp-calypso/commit/3c8a7c8b5b31a652bb7c531954cb566a47c01d89 (latest at the time of this PR) which should fix the tests/builds randomly failing after `npm install`
Also fixes the image imports broken by the recent changes in Calypso.
It should also fix the tests failing in #1292

Set the latest Calypso rev as the dependency, fixed image imports

---

classes/class-wc-connect-options.php
classes/class-wc-connect-settings-pages.php
classes/class-wc-rest-connect-account-settings-controller.php
client/apps/account-settings/index.js
client/apps/account-settings/view-wrapper.js
client/apps/shipping-label/view-wrapper.js

Implements "Solution 1" referred to in https://github.com/Automattic/woocommerce-services/issues/1115#issuecomment-325632978.
If (and only if) the label settings screen was arrived at from an order screen (i.e. an edit post screen), and settings are saved with a payment method selected, a "Back to order" link appears in the success notification (which also persists in this case, instead of disappearing after 5 seconds).
Can change "Back to order" text if there are better ideas — "return" instead of "back"? to "order page"? or "Order ##"?

Add redirect link from label settings screen back to order

---

assets/stylesheets/_colors.scss

Cleanup after #1294 - removes the leftover variables from `_colors.scss` and simplifies the Calypso import.

Cleaned up the CSS color imports

---

classes/class-wc-connect-service-settings-store.php

Fixes the Hydra-related issue in p8yzl4-1fK-p2
An argument can be made to remove the migration script completely, and the only other place where `get_enabled_services_by_ids()` is used is already making a check for an empty array, but I think it's a good practice to do that check inside this function to avoid this kind of errors if someone decides to use it somewhere else.

Fixed broken DB migration script

---

classes/class-wc-connect-taxjar-integration.php

Fixes #1307.
Tax calculation was being kicked off even when core WC taxes were disabled, and on every admin page load. This was a side effect of having items in cart as an admin user, and by Jetpack's JITM request.
To test:
* Ensure that debug logging is enabled
* Ensure that you have items in a cart
* With tax calc **on** + automated taxes on - verify that no tax requests are logged while navigating the admin
* With tax calc **off** + automated taxes on - verify that no tax requests are logged while navigating the admin
(cc: @allendav)

Fix waay too many automated tax requests

---

classes/class-wc-connect-stripe.php

Fixes #1289 
To test:
* Install on a WordPress.com Automated Transfer (Store) site with the WooCommerce Stripe Gateway plugin also installed and active
* Use Stripe Connect to connect to a Stripe account (can use Calypso for this)
* Use Stripe Connect to deauthorize / disconnect that account
* Navigate to /wp-admin/admin.php?page=wc-settings&tab=checkout&section=stripe, and verify the keys (for production) have been cleared.

Stripe Connect: Clear keys on stripe deauthorization

---

classes/class-wc-connect-help-view.php
classes/class-wc-connect-logger.php
classes/class-wc-connect-options.php
classes/class-wc-connect-payment-methods-store.php
classes/class-wc-connect-service-schemas-store.php
classes/class-wc-connect-service-settings-store.php
classes/class-wc-connect-shipping-method.php
classes/class-wc-connect-taxjar-integration.php
classes/class-wc-connect-tracks.php
classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-address-normalization-controller.php
classes/class-wc-rest-connect-self-help-controller.php
classes/class-wc-rest-connect-services-controller.php
classes/class-wc-rest-connect-shipping-label-controller.php
classes/class-wc-rest-connect-shipping-label-preview-controller.php
classes/class-wc-rest-connect-shipping-label-print-controller.php
classes/class-wc-rest-connect-shipping-label-refund-controller.php
classes/class-wc-rest-connect-shipping-label-status-controller.php
classes/class-wc-rest-connect-shipping-rates-controller.php
classes/class-wc-rest-connect-stripe-account-controller.php
classes/class-wc-rest-connect-stripe-deauthorize-controller.php
classes/class-wc-rest-connect-stripe-oauth-connect-controller.php
classes/class-wc-rest-connect-stripe-oauth-init-controller.php
tests/php/test_class-wc-connect-shipping-method.php
tests/php/test_woocommerce-connect-client.php
tests/php/test_woocommerce-connect-tracks.php
woocommerce-services.php

Addresses #1163.
Optional PR: https://github.com/Automattic/woocommerce-services/pull/1304 - feature separated logging.
This PR seeks to do the following:
* Separate the notion of "logging" and "debugging" based on front-end visibility
* Output USPS-extension-style debug messages in cart/checkout to help merchants troubleshoot their shipping setup
**Note: this can only output rates that are returned by the server - no packaging info will be displayed if no rates are found.**
Messages that can be displayed:
* Request error
* Response is missing `rates` property
* Received rate: <info>
* Skipping rate calculation - missing country
* Skipping rate calculation - invalid postcode
* Skipping rate calculation - invalid/unsupported state
* No rates found, adding fallback
_Note: if the fallback …

Output shipping debug messages on the Cart and Checkout pages.

---

assets/stylesheets/style.scss
client/calypso-stubs/components/data/query-stored-cards/index.js
client/calypso-stubs/extensions/woocommerce/woocommerce-services/views/label-settings/add-credit-card-modal.js
client/calypso-stubs/state/stored-cards/selectors.js
npm-shrinkwrap.json
package.json

Needs https://github.com/Automattic/wp-calypso/pull/22802 to be shipped first
Added styling to hide the modal button and show the external link button. Added stubs for the modal and query component, as well as Calypso-specific card selectors.
TODO:

Updated the Calypso depency

---

classes/class-wc-connect-extension-compatibility.php
classes/class-wc-connect-service-settings-store.php
client/apps/shipping-label/index.js
client/apps/shipping-label/redux-middleware.js
client/main.js
woocommerce-services.php

Fixes #1156 
Automatically adds the tracking number when a new label is purchased and checks for WooCommerce Shipment Tracking existence when sending the "order complete" email. If WCST is going to append its data to the email, WCS will not do that.
Will need PR 87 to be shipped on the `woocommerce-shipment-tracking` repo to be fully functional, but will work without it. The PR allows us to refresh the tracking data without reloading the page.
I also wanted to lay some ground work for future integration with other official WooCommerce extensions:
* added a static `WC_Connect_Extension_Compatibility` class which should contain the PHP integration code
* added per-JS-app Redux middleware. It allows to listen for actions and extend them beyond just modifying the state, which could give us …

Added integration with WooCommerce Shipment Tracking

---

.travis.yml
tests/bin/install-wc-tests.sh
tests/php/test_class-wc-connect-api-client.php

Closes #780
The new build matrix includes a variety of these versions:
WordPress:
- 4.4 (earliest supported by WooCommerce 2.6)
- 4.5
- 4.6
- 4.7
- 4.8
- `latest` (4.9 at the moment of writing this)
WooCommerce:
- 2.6.14 (earliest supported by WCS for now)
- 3.0.9
- 3.1.3
- 3.2.6
- 3.3.3 (latest)
PHP:
- 5.2 (earliest we support)
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
- 7.1
- 7.2 (latest)
I added a sensible matrix so we don't hog TravisCI resources for no reason. I made sure that these situations are covered:
- Earliest PHP version with latest WC and WP versions.
- Earliest PHP, WC and WP versions.
- Latest PHP versions with earliest WC and WP versions.
- Latest PHP, WC and WP versions.
- Earliest WC version with latest WP version.
- Earliest WP version with latest WC version.
If you ask me, that's …

Updated the versions matrix to test our code in CI

---

classes/class-wc-connect-taxjar-integration.php

"Fixes" https://wordpress.org/support/topic/php-fatal-error-site-very-slow-when-activated-with-taxjar/
It won't fix the problem, but at least the merchant will get a real error message instead of a full crash.
The problem is that, before, `smartcalcs_request` could either:
* Return a response object (associative array).
* Return a `WP_Error`.
* Return nothing (`NULL`).
The function that calls `smartcalcs_request` would only check that `isset($response)`, so if the response is a `WP_Error` it would be treated as a normal response and the whole thing would crash when accessed like an associative array.
The solution is to make sure that `smartcalcs_request` returns either a regular response, or nothing (`NULL`). I added some error logging so errors will be written in the WCS logger even if …

Fix crash when there's an error requesting taxes from the WCS proxy.

---

classes/class-wc-connect-paypal-ec.php

Fixes #1336 
To test:
* have the PPEC installed and activated
* make one of the dependencies to break (use WooCommerce<2.5 or disable/remove the `curl` library in PHP). Or open `plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-plugin.php` and modify it to throw an exception around line 155
* load any admin page
* the page should load

Fixed the page crash when PPEC has not initialized successfully

---

classes/class-wc-rest-connect-address-normalization-controller.php

In the event of address normalization validation errors, passes specific address field validation errors back to the client. ~(Depends on server branch `add/address-normalization-field-errors`.)~
Also, changes this response from an error to a success response (to match the WCS server response): the data only gets passed back to the WP.com client in the event of a successful request.

 Forward specific address normalization errors, as success response

---

assets/stylesheets/style.scss
client/apps/shipping-label/style.scss
client/components/error-notice/index.js
client/components/error-notice/style.scss

Before | After
-- | --
https://github.com/Automattic/woocommerce-services/commit/c0d0d78a0f1947371fa5f443e702069530e16549: Removes custom styling for `ErrorNotice` component, which is only used in one place and looks the same without it except with icon showing: <img width="740" alt="screen shot 2018-03-19 at 6 23 48 pm" src="https://user-images.githubusercontent.com/1867547/37627079-20ff5814-2ba9-11e8-971a-aefac8122546.png">
---
Before | After
-- | --
https://github.com/Automattic/woocommerce-services/commit/311f9f0ae09effb7068abf678c3c55f0f7b071ab: Reverts https://github.com/Automattic/woocommerce-services/commit/171ffa0ef22dbb41ac96d1505beccb78cc4cf0cd, which was introduced to fix icon alignment in header [[#](https://github.com/Automattic/woocommerce-services/pull/1216#issuecomment-346 …

Fix various styling inconsistencies

---

classes/class-wc-connect-taxjar-integration.php

Fixes #1296
Fixes #1297
TaxJar shows all the options when enabled, but reverts them on save anyway. I decided to hide the options since they are always ignored when calculating the taxes.

Hide the tax settings and show a notice when automated taxes are enabled

---

client/api/request.js
client/apps/shipping-label/index.js
client/apps/shipping-label/view-wrapper.js
client/calypso-stubs/config.js
client/calypso-stubs/extensions/woocommerce/state/sites/http-request.js
client/lib/local-api-middleware.js
client/main.js
npm-shrinkwrap.json
package.json
tasks/i18njson.js
tasks/release.js

This PR seeks to add the functionality from this Calypso PR: https://github.com/Automattic/wp-calypso/pull/21229.
It adds the WooCommerce and WPCOM data-layer middleware to facilitate using the `woocommerce` state tree.
A Calypso stub and redux middleware were added to redirect Jetpack proxy requests to the local WC REST API and to modify the response for the WooCommerce data-layer middleware. _(`meta.dataLayer.data` vs `meta.dataLayer.body`)_
The stub+middleware combo will allow the use of any WooCommerce data-layer middleware that doesn't rely on https://github.com/woocommerce/wc-api-dev - e.g. can be requested over `/wc/v2`.
Visual changes in this PR:

Add customer selected shipping method to rates step.

---

classes/class-wc-connect-compatibility-wc26.php
classes/class-wc-connect-compatibility-wc30.php
classes/class-wc-connect-compatibility.php
classes/class-wc-connect-label-reports.php
classes/class-wc-connect-service-settings-store.php
woocommerce-services.php

Fixes #1277
Fixes #1327
Adds a simple reports page listing all labels successfully purchased during a selected time period:
The page can be accessed under `WooCommerce > Reports > Labels`
* Doesn't list labels with errors
* Labels are listed by package, so if two labels are purchased with one request, it will result in two rows
* Only lists time, price, order ID and service. Do we need to display any other data?

Added labels reports section

---

assets/stylesheets/style.scss
classes/class-wc-connect-payment-methods-store.php
classes/class-wc-rest-connect-account-settings-controller.php

Returns the following message if payment methods could not be fetched when requesting label settings:
This is to notify the merchant if their payment methods were not updated in the current page load, as implemented in https://github.com/Automattic/wp-calypso/pull/23307.
To test, make WCS unreachable by setting `WOOCOMMERCE_CONNECT_SERVER_URL` to a URL in which there is no WCS server, and load the label settings page.

Include warning message in response upon failure to retrieve payment methods

---

client/apps/shipping-label/index.js
client/main.js

I managed to fix this without touching `wp-calypso`.
**The bug:** In the `self-help` page, you can't interact with the debugging toggles.
**The cause:** We're using Calypso's `extensions-middleware` to load some `woocommerce`-related data-layer handlers. That middleware maintains a global state, so when it's called 2 times with different Redux stores, the first one will be overwritten. That means that the second Redux store (in this case, the `print-test-label` section) will receive all the Redux actions, including the ones that don't correspond with that "app".
**The solution:** Avoid `extensions-middleware`. Its only purpose is to allow extensions (which in Calypso are different chunks loaded on-demand) to register handlers **after** the Redux store is configured. We don't need that, …

Remove extensionsMiddleware, use the plain wpcomApiMiddleware instead

---

classes/class-wc-connect-logger.php

Restores the original behavior of the logger's `error` method, which logs the message whether "debug" logging is enabled or not. This fixes a broken UX when an error isn't logged but the admin notice directing the merchant to view the error still appears.
Background:
- https://github.com/Automattic/woocommerce-services/pull/803 added a bit of indirection to `log` calls, in which most uses of the `log` method were called via a `debug` method, but an `error` method was used in the shipping rate case, to show a "An error has occurred" notice and log the message regardless of whether "Debug Logging" is enabled.
- https://github.com/Automattic/woocommerce-services/pull/1303 switched `debug` calls back to `log` (as part of introducing a new, separate `debug` feature) which is used by `error`, …

Restore error logging whether ordinary logging is enabled or not

---

classes/class-wc-connect-taxjar-integration.php

Fixes #1362 
To test:
* enable taxes, but ensure automated taxes are disabled
* attempt to save any WooCommerce core settings on any page other than taxes
* the settings should save and no PHP warning seen

Fix `Undefined index: wc_connect_taxes_enabled` notice

---

classes/class-wc-connect-functions.php
classes/class-wc-connect-shipping-method.php
classes/class-wc-connect-taxjar-integration.php
woocommerce-services.php

Fixes #1360 
* Copied the solution from #1308 to skip the requests when not on the checkout page or the request is a Jetpack request
* ~~added rates response memory caching - requests can attempt to calculate rates more than once and our code would send the rates request every time for this~~
To test:
* enable debug mode in `WooCommerce > Settings > Shipping > Shipping Options` to ensure that rates are not cached
* WP Admin requests and non-checkout AJAX requests should not generate a rate request - this can be checked either by monitoring the server console output or placing a debug breakpoint in `class-wc-connect-shipping-method.php`
* checkout rates should display and update when cart contents/address are updated
* ~~only one rates request should be sent per WP request - added a debug …

Fix too many rate requests

---

npm-shrinkwrap.json
package.json
webpack.config.js

Some of the Calypso's components rely on PropTypes in their code (for example the clipboard button).
`transform-react-remove-prop-types` Babel plugin removes the PropTypes when `npm run dist` is executed, which might lead to unexpected side effects that can only be observed in the compiled JS.
To test:
* run `npm run dist`
* ensure the plugin is using the compiled JS (comment out the line `define( 'WOOCOMMERCE_CONNECT_DEV_SERVER_URL', 'http://localhost:8085/' );` in the dev plugin)
* verify that the plugin status page loads
* other areas of the plugin should work as well

Removed transform-react-remove-prop-types plugin

---

classes/class-wc-connect-shipping-method.php

Separated out of #1361
Adds request scope caching of the rates returned by the server. WC core implements effective caching when the shipping debug mode is disabled, but enabling it results in at least 4 requests sent to the server. This change will limit it to 2.
To test:
* enable debug mode in `WooCommerce > Settings > Shipping > Shipping Options`
* navigate to checkout
* you should see less rate requests processed by the server with this change (this can be observed by monitoring the server's console output)
* There's a new debug message for when a rates response is retrieved from cache

Added rate request caching

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-error-notice.php
classes/class-wc-connect-logger.php

Addresses https://github.com/Automattic/woocommerce-services/issues/1376#issuecomment-382153745 by enhancing the admin notice — in the case of a shipping rate missing weight error — with a description and link to the relevant product:
Questions:
- Should this code live somewhere other than `WC_Connect_Error_Notice`?
- Should clicking the link dismiss the notice?
- Are there other errors that should get a similar treatment?

Surface missing weight error directly in admin notice

---

client/apps/settings/components/settings-form/settings-item.js
client/apps/shipping-label/view-wrapper.js

Adjusts links to label settings, which moved to a new section in https://github.com/Automattic/woocommerce-services/pull/1328 causing the "Manage Cards" link to lead to an empty WooCommerce Settings screen.

Adapt order page link to label settings' new section slug

---

assets/stylesheets/style.scss
client/lib/pdf-label-utils/index.js
npm-shrinkwrap.json
package.json

Update wp-calypso dependency to 32d5bb0ee809c38883bbccd1a6e62fba5ee35f9a.
Includes:
* https://github.com/Automattic/wp-calypso/pull/22766
* https://github.com/Automattic/wp-calypso/pull/22499
* https://github.com/Automattic/wp-calypso/pull/23151
* https://github.com/Automattic/wp-calypso/pull/23307
* https://github.com/Automattic/wp-calypso/pull/23322
* https://github.com/Automattic/wp-calypso/pull/23378
* https://github.com/Automattic/wp-calypso/pull/23412
* https://github.com/Automattic/wp-calypso/pull/23512
* https://github.com/Automattic/wp-calypso/pull/23816
* https://github.com/Automattic/wp-calypso/pull/23834

Update Calypso Dependency

---

classes/class-wc-connect-shipping-method.php

Fixes https://wordpress.org/support/topic/php-error-undefined-variable-package_measurements/
To test:
* remove all packages from the packaging manager to make sure the items ship individually
* on the checkout page open the dev tools and monitor the network tab
* edit the address to force the rates update
* AJAX request `?wc-ajax=update_order_review` should return a correct result and the updated rates should appear in the checkout

Fix Undefined variable: package_measurements error

---

classes/class-wc-connect-shipping-method.php

Fixes a PHP error that appears when the server cannot be reached.
To reproduce:
* Make sure the client cannot reach the server (for example stop the server if using a local env)
* Try to request rates
* Warnings will appear
To test:
* Repeat the reproduce steps
* No PHP warnings should appear
This might also require a point release since it breaks the fallback rate functionality :/

Fix "Undefined variable: service_settings" error

---

classes/class-wc-connect-error-notice.php

Fixes crash scenario (introduced by https://github.com/Automattic/woocommerce-services/pull/1380) when product featured in missing weight admin notice is deleted. To reproduce (from @v18):
1. get rates for a product without ~dimensions~ weight
2. delete product
3. in `master`, see fatal on any admin screen. In this branch, admin notice should just disappear

Admin breaking when product with missing weight is deleted

---

classes/class-wc-connect-privacy.php
woocommerce-services.php

Fixes #1383 
To test:
* Either use the latest [WordPress Core SVN trunk](https://develop.svn.wordpress.org/trunk/) or latest [master WordPress Core from GitHub](https://github.com/WordPress/WordPress)
* Use the latest [WooCommerce code](https://github.com/woocommerce/woocommerce)
* In wp-admin under `Tools > Privacy` you should be able to designate and edit a privacy page
* When editing the privacy page, click "check out our guide" (in notice)
* the following snippet should appear among the others:

Add privacy policy message

---

classes/class-wc-connect-privacy.php
woocommerce-services.php

Fixes #1384 
Adds the label tracking numbers to the personal data exports:
To test:
* Either use the latest [WordPress Core SVN trunk](https://develop.svn.wordpress.org/trunk/) or latest [master WordPress Core from GitHub](https://github.com/WordPress/WordPress)
* Use the latest [WooCommerce code](https://github.com/woocommerce/woocommerce)
* Under `Tools > Export personal data` you should be able to initiate the personal data export for a given email address
* Export the data for orders that have labels with tracking numbers purchased
* The data should include the tracking number

Added personal data export functionality

---

classes/class-wc-connect-api-client.php
classes/class-wc-connect-privacy.php
woocommerce-services.php

Erases personal data (tracking numbers) from the client database and calls the server to erase the same data.
Note: the affected labels will currently disappear from the order page. A separate Calypso PR will follow which will render the anonymized labels in the log, but not show the reprint link.
To test:
* Make sure you're using WordPress 4.9.6+
* Use the latest [WooCommerce code](https://github.com/woocommerce/woocommerce)
* Use the server PR - 1089-gh-woocommerce-connect-server
* Set WooCommerce to erase the order data by navigating to `WooCommerce > Settings > Accounts & Privacy` and enabling the `Remove personal data from orders` checkbox
* Place an order with an email address
* Purchase a label for that order 
* Navigate to `Tools > Erase Personal Data` and erase the data using the …

Add personal data erasure

---

classes/class-wc-connect-help-view.php

Fixes #1405 
To test:
* either delete the WCS logs (by default they are located in `wp-content/uploads/wc-logs`) or change `$line_count` to 0 in `class-wc-connect-help-view.php`
* open the status page
* the log components should read `Log is empty` and no warnings should be shown

Fix the PHP warning on the status page when logs are empty

---

classes/class-wc-connect-privacy.php

Adds the following warning to the erasure page:
To test:
* use WordPress 4.9.6 or later
* use WooCommerce `master` branch
* enable order data erasure under `WooCommerce > Settings > Accounts & Privacy`
* navigate to `Tools > Export personal data`
* the notice should be visible
* the notice should not be visible when order data erasure is disabled

Added a warning about erased labels to the erasure page

---

classes/class-wc-connect-error-notice.php

Fixes https://github.com/Automattic/woocommerce-services/issues/1424 by getting the parent ID in the event the object returned by `wc_get_product` is a variation.
To test:
- Create a variation with no weight
- Add it to cart and calculate shipping for a zone with live rates configured
- Find notice on any admin page
- The link should take you to the variable product page

Fix 'missing weight' admin notice's product link URL for variations

---

classes/class-wc-connect-service-settings-store.php
classes/class-wc-rest-connect-services-controller.php

There's more context in https://github.com/Automattic/wp-calypso/pull/25101
We had an error in which service schema validation would fail in the server if the adjustment fields were touched in any way. The error has been fixed (something something `coerceValues`), but I dug deeper on "Why doesn't this fail in Calypso"?
In Calypso, a validation failure in the plugin side will happily show a "success" notice, but the shipping method won't be updated at all. That's because the Calypso HTTP layer logic checks for non-200 HTTP responses to trigger the error notice, and the plugin responds with a `HTTP 200` response with `{ success: false }` in the body.
This PR changes the plugin logic so it responds with a real HTTP error. All our other REST endpoints already return a `WP_Error` on failure, …

Respond with real HTTP errors when the shipping settings can't be validated

---

classes/class-wc-connect-taxjar-integration.php

I've updated our TaxJar integration to their latest version (currently `1.7.0`). For that, I checked which was the last version we updated the plugin with (`9d8e725`), I opened [this GitHub view](https://github.com/taxjar/taxjar-woocommerce-plugin/compare/9d8e725...master), collapsed every file except `class-wc-taxjar-integration.php`, and copied along. We were more than 3 months behind them, diong it PR by PR would have been much more tedious.
Noteworthy:
- Their `smartcalcs_cache_request` function doesn't use that weird TLS transient system anymore. Now it can be directly copied.
- There's a new filter function: `override_woocommerce_tax_rates`. I just copied it over.
- The `calculate_totals` and `calculate_backend_totals` have been refactored into smaller functions. Those huge …

Updated TaxJar integration

---

classes/class-wc-connect-nux.php
woocommerce-services.php

Fixes #1334.
Don’t show the shipping method NUX pointer if shipping was opted into in the core Setup Wizard.
To test:
* Set up a new WooCommerce store using the OBW
* Opt in to either domestic or international live rates
* Connect Jetpack
* Verify that the "add a WCS method" pointer *does not* show on the Shipping settings page

Don't show "add method to zone" pointer if shipping was opted into

---

woocommerce-services.php

Fixes #966 
This PR saves the default settings of a shipping method when it's added to a zone, using the `wc_connect_shipping_zone_method_added` hook.
Note that the settings for FedEx are not yet complete, so they'll cause an error.
This also works on Calypso because a zone shipping method is created, and then it's updated with the valous provided by the user, so there's no possibility of a race condition (can see some of the code in [`getSaveZoneActionListSteps`](https://github.com/Automattic/wp-calypso/blob/39a6bcd9cac5aa2e9d8b7b875cc999e52a4126b7/client/extensions/woocommerce/state/data-layer/ui/shipping-zones/index.js#L370)).
**Question for design:**
Should we save the default settings without prompting the user to review them?
1. start with no zones, and no shipping methods
2. see …

Save defaults when adding new WCS shipping method

---

woocommerce-services.php

Fixes #1273.
Refresh service schemas when the following options are updated: store post code, currency, weight unit, and dimension unit.
**To Test:**
- Load this branch
- Enable logging
- Make sure your frequent fetch flag is NOT enabled
- Change any one of the mentioned settings via `wp-admin`
- Observe that a fetch_service_schemas_from_connect_server event is logged in the logs
- Change any one of the mentioned settings via the REST API
- Observe that a fetch_service_schemas_from_connect_server event is logged in the logs

Refresh service schemas when specific WooCommerce settings are updated

---

npm-shrinkwrap.json
package.json

Updates Calypso dependency to include:
https://github.com/Automattic/wp-calypso/pull/25628
https://github.com/Automattic/wp-calypso/pull/25307

Update Calypso to cc49f0a

---

classes/class-wc-connect-taxjar-integration.php

The TaxJar folks haven't made a release after `1.7.0`, but there are still several bug fixes that we don't have. These are all of them: https://github.com/taxjar/taxjar-woocommerce-plugin/compare/1.7.0...master
- https://github.com/taxjar/taxjar-woocommerce-plugin/commit/b877838317d9a8ee112d6ff570d12c7d265cd70f was already applied
- https://github.com/taxjar/taxjar-woocommerce-plugin/commit/f41f124065806a5273184d28e16aaf37213d5ab3 is for the Nexus, doesn't apply in our integration
- https://github.com/taxjar/taxjar-woocommerce-plugin/commit/7a743ac94d78562ddc29c15dce7a6a2e75ab30b5 and https://github.com/taxjar/taxjar-woocommerce-plugin/commit/96b5d57fb807e2529b50994adc1a5fe251dbdbe3 change the same function, updated in https://github.com/Automattic/woocommerce-services/commit/fc70ed891606a …

Update TaxJar to the latest version

---

client/apps/settings/view-wrapper.js

If there are invalid fields when you open the USPS/Canada settings form, but you haven't interacted with those fields, then they won't show any error until you click "Save changes". Clicking that button will trigger a full validation and show an error notice if it fails (the logic of that is in `wp-calypso`, including the error notice). Since all that logic is in `wp-calypso`, the `<ViewWrapper>` component's state wasn't being updated, so it would keep showing the `busy` animation forever.
To reproduce:
* Get to the service settings page having some fields be incorrect. The easiest way is to change the Store base address to have an invalid ZIP code, and then add a new shipping method (it will take that bogus ZIP code as default).
* Interact with any other field (such as the title, or …

Fixes the "Save changes" button on USPS/Canada settings staying in "busy" state after failing validation

---

classes/class-wc-connect-shipping-method.php

A few versions ago we added an "envelope" emoji or "package" emoji to each package name in each shipping rate metadata.
These emojis are displayed in the Order page (as part of the "Packaging" metadata string), and in the debug notices.
Since that metadata is serialized into JSON and stored in the database (and in the session), this caused trouble on certain MySQL configurations.
According to [this Reddit thread](https://www.reddit.com/r/PHP/comments/3fvi0u/emojis_are_breaking_our_json_decodes_help/), if the database charset is `utf8`, storing emojis in it would break. It needs to be `utf8mb4` instead. My local WordPress install (and the majority of people's) use `utfmb4`, since it's the default setting for `DB_CHARSET` in the most recent versions of WordPress. But the site that was …

Remove emojis so they don't break the checkout when saving metadata into the database

---

client/calypso-stubs/extensions/woocommerce/state/sites/http-request.js

This notice:
Didn't work in WooCommerce `2.6`. The reason is that, for requests that use the Calypso data layer, we were stubbing it to always use the `/wc/v2` namespace (only present in 3.0 and up). For now, the only endpoint being used is the `order` endpoint, and it's just used to display that "Your customer selected..." notice in the Label Purchase flow.
The `order` endpoint is also present in `/wc/v1` and it has all the information the plugin needs, so there's no harm in changing it.
To test:
* Downgrade to WooCommerce 2.6.x
* Go purchase a label
* In the `Rates` step, you should see the notice indicating which rate the customer chose
I know we officially only support `WooCommerce 3.0` and up, but we (@jeffstieler and I) agreed that a sensible approach would be to make a release …

Fix the "Your customer selected Express Mail" notice for WooCommerce 2.6

---

classes/class-wc-connect-paypal-ec.php
readme.txt

To align with https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/pull/441, changes all instances of name except those close to the API layer (as the API is unchanged).
Only merchant-facing change is in this text:

Rename 'PayPal Express Checkout' to 'PayPal Checkout'

---

classes/class-wc-connect-shipping-label.php
classes/wc-api-dev/class-wc-rest-dev-data-continents-controller.php
classes/wc-api-dev/class-wc-rest-dev-data-controller.php
client/apps/shipping-label/index.js
client/calypso-stubs/extensions/woocommerce/state/sites/http-request.js
woocommerce-services.php

See https://github.com/Automattic/wp-calypso/pull/25723 for the Calypso part of this PR.
This PR removes the `countriesData` property that was returned in the `labels` payload. Instead, now the countries/states data is fetched from the `wc/v3/data/continents` REST endpoint. Since a site using `woocommerce-services` from WP-Admin may not have the `wc/v3/*` endpoints (right now they're only available through the `wc-api-dev` plugin), the entire endpoint is copied in the plugin, unchanged.
To test:
* Disable or uninstall the `wc-api-dev` plugin.
* Update your `wp-calypso` dependency to the branch `update/store-labels-use-continents-endpoint`. `npm link ../wp-calypso` should work now that we're using `npm 6`.
* Go to an order.
* Open the `Purchase Label` modal.
* See that all the "USPS" …

Use the wc/v3/data/continents endpoint

---

client/apps/shipping-label/redux-middleware.js

The nux pointer would remain open if the user clicks on the "print label" button without dismissing it. This PR addresses that.
To test:
* If not on a fresh install:
* modify `is_new_labels_user()` in `class-wc-connect-nux.php` to always return `true` 
* remove `wc_services_labels_metabox` from the `dismissed_wp_pointers` row in `wp_usermeta` table
* the pointer should appear
* Without dismissing the label pointer, open the label print modal
* The pointer should be dismissed in the background and shouldn't reappear after a page refresh

Dismiss the label NUX pointer when the label modal is opened

---

client/admin-pointers.js

Fixes #1089 
To test:
* If not on a fresh install:
* modify `is_new_labels_user()` in `class-wc-connect-nux.php` to always return `true` 
* remove `wc_services_labels_metabox` from the `dismissed_wp_pointers` row in `wp_usermeta` table
* the pointer should appear
* Dismiss the pointer and purchase a label
* Without refreshing the page click on the new label's ellipsis menu
* The menu should appear and shouldn't be obscured by the label metabox

Reset pointer target's z-index on dismissal to fix the ellipsis menu

---

client/apps/shipping-label/redux-middleware.js

Fixes a console error appearing in the console when opening the label modal after the pointers have been dismissed and the page has been refreshed.
There are two kinds of errors:
`Uncaught TypeError: (0 , _jquery2.default)(...).pointer is not a function`
`Uncaught Error: cannot call methods on pointer prior to initialization; attempted to call method 'close'`
To test:
* open a label modal
* verify that there are no errors being logged in the JS console

Fix jQuery pointer errors when opening the label modal

---

classes/class-wc-connect-taxjar-integration.php

Fixes #1427 
To test:
* Enable automated taxes
* Make sure the "An error occurred in WooCommerce Services" notice is closed in wp-admin
* On checkout, enter a mismatching zip/state combination
* A notice should appear on the checkout page (see below) and proceeding with the checkout should not be possible
* No notice should appear in wp-admin and no error should be logged in the tax logs on the status page

Do not log invalid tax to_zip errors and show them to the customer

---

npm-shrinkwrap.json
package.json
readme.txt
woocommerce-services.php

These are the PRs that made it into this release:
* https://github.com/Automattic/woocommerce-services/pull/1502 Trivial `readme.txt` copy change
* https://github.com/Automattic/wp-calypso/pull/27201 Allows returning `First Class - Envelope` rates iff the package is an envelope
* https://github.com/Automattic/wp-calypso/pull/26895 Clear the rates step when changing `weight` or `signature` fields on the `Packages` step
* https://github.com/Automattic/wp-calypso/pull/27079 Fixes `tracks` events for international labels purchases

Cut Release 1.16.1, update the wp-calypso dependency

---

classes/class-wc-connect-api-client.php

Requires server support (in staging, not yet in production).
If the Stripe account being connected via OAuth is not yet activated with complete account details, Stripe presents a form as part of the flow [[screenshot](https://cloudup.com/cKL_B_-m3eM)].
This change passes info to include in the OAuth URL for prefilling the Stripe activation form.

Pass Stripe account details for prefilling activation form

---

assets/stylesheets/style.scss
npm-shrinkwrap.json
package.json

This was annoying me because I couldn't use a recent `master` version of `wp-calypso` linked to `woocommerce-services`.
They refactored a bit the SCSS files so now we need to import also the `shared/extends-forms` file. See this commit in `wp-calypso` for more context: https://github.com/Automattic/wp-calypso/commit/3d61007729e10d24022f5665474dc8c2d821f4cb
To test, just check that `npm start` works without errors.

Update wp-calypso dependency, fixed SCSS conflicts

---

client/apps/plugin-status/index.js
client/apps/print-test-label/index.js
client/main.js
npm-shrinkwrap.json
package.json

I've simplified the code around React hot-loading. By "simplified", I mean that I've removed it entirely. I don't think we've ever got hot module reloading working.
I've also removed `redbox-react` because:
* I don't recall seeing it working since a long time ago (maybe because I've done most of my dev work directly in Calypso).
* When something is obviously not working in development, we all know to open the browser console. We don't need the entire screen flashing blood-red and slapping us in the face with a full-screen error. I don't feel strongly about this, so if anyone finds it useful I'll revert this part of the PR.

Clean-up dev tools and logic that has never quite worked

---

classes/class-wc-connect-nux.php

To test:
* Remove `dismissed_wp_pointers` user meta
* Visit Shipping Zones page
* Verify that no WP Pointer appears telling you to add a WCS shipping method to a zone

Remove “add method to zone” NUX pointer.

---

webpack.config.js

With the recent changes to webpack, lodash started setting `window._` and overwriting the Underscore variable that is expected by JavaScript files from WP core and other plugins. This causes things to break in wp-admin. 
The issue that was reported the most was missing shipping methods UI when both WCS and Stripe extensions are activated.
The fix is to not import the modules as AMD - see [here](https://github.com/lodash/lodash/issues/1798) and [here](https://github.com/webpack/webpack/issues/3017#issuecomment-285954512).
We don't use AMD - Webpack compiles all scripts into one file and nothing is loaded asynchronously.

Fix lodash exporting _ as a global variable

---

classes/class-wc-connect-api-client.php

Fixes #1529 
To test:
* The easiest way to simulate Jetpack token problems is to return new `WP_Error` in `class-wc-connect-api-client.php` around line `538`. You can also delete `jetpack_private_options` from `wp_options`, but that might have unintended side effects.
* Enable automated taxes and navigate to the cart page
* The page should load properly

Fix crash when making proxy requests with broken Jetpack token

---

classes/class-wc-connect-help-view.php
client/apps/plugin-status/services.js

When live rates are disabled for the site, the status page will still show the Services section with a link to the shipping settings:
This PR removes the section unless the site is grandfathered.
Test steps:
* Confirm that the status page renders the section when the site is not grandfathered
* In the server database mark your site as not grandfathered
* Confirm that the section is not rendered

Remove shipping service status for non-grandfathered sites

---

classes/class-wc-connect-stripe.php

See server PR 1165 for extra detail
Currently, if the site is not using SSL in the admin url the plugin will try to connect to the server to generate the OAuth url and fail every time.
This prevents the site from attempting to connect in the first place, reducing the traffic and increasing performance.

Prevent Stripe from attempting to connect if the site is not using ssl

---

assets/stylesheets/style.scss

Adding an additional selector in order to restore the default Calypso behavior.
__Broken state:__
__Proper state:__

Removing the background of borderless buttons in hover state

---

npm-shrinkwrap.json
package.json

See: https://github.com/Automattic/wp-calypso/pull/28829

Update calypso dependency to catch the update to `npm-run-all`.

---

classes/class-wc-connect-stripe.php
client/apps/stripe-connect-account/view-wrapper.js

Fixes https://github.com/Automattic/woocommerce-services/issues/1526
(Note: previously considered in scope for https://github.com/Automattic/woocommerce-services/pull/1513 but was likely a poor match for the issue's priority. This PR serves as a stop-gap ahead of that one.)
For the case when there is no connected Stripe account (see https://github.com/Automattic/woocommerce-services/pull/1497), this change removes the "No account connected via WooCommerce Services." info notice and replaces it with a line of text directing the merchant down the screen to manually set up keys:
> Stripe account keys may be configured below.
`master` | this PR
-- | --
I was tempted to keep the "No account connected via WooCommerce Services." message as a parenthetical, but I suppose it would still result in …

Replace alarming Stripe settings notice with helpful text

---

woocommerce-services.php

As @adelineyaw explained in #1544, WooCommerce Services overwrites the shipping phone even if it is already created by another plugin.
The addition of the phone field and the reasons for it may be found here: https://github.com/Automattic/woocommerce-services/pull/693
In this PR I am checking whether a `shipping_phone` field already exists and if it does, I am using the values from it, while enforcing `tel` as field, autocompletion and validation type.
1. Install WCS and the "Checkout Fields Editor" extension.
2. Add/enable a `phone` field in the shipping section.
3. Test the checkout page and monitor whether changes like label, required and etc. are appearing properly.
Fixes #1544

Changing the shipping_phone field to avoid conflicts

---

assets/stylesheets/style.scss

Imports `shared/color-schemes` from Calypso (previously removed in https://github.com/Automattic/woocommerce-services/commit/609e04da9692ae79936cb6bde11b250fa5428267#diff-b39e66f308ad4a3f411482e021b2ea49L3), to restore the proper button colors with latest Calypso:
Tested by `npm link`ing wp-calypso `master`.
@DanReyLop (or anyone else) let me know if there's a better way to fix this.

Fix missing button colors with latest Calypso

---

npm-shrinkwrap.json
package.json

The new `refspec` is https://github.com/Automattic/wp-calypso/commit/2e31916ffdf44cdb1340ed1bf5a60e09a74ee887 which was the latest stable deployed commit a couple of hours ago.
I did some basic local tests already, but we will thoroughly test before the release anyway.

Updating the Calypso refspec to include all merged PRs for 1.18.0

---

assets/stylesheets/_components.scss
assets/stylesheets/style.scss
webpack.config.js

This PR seeks to fix style conflicts when running within a "Calypsoified" `/wp-admin`. See: p58i-7nL-p2 (`#comment-40377`)
To test:
* `npm run dist`
* Clear local style cache
* Verify that all WCS screens and components have the correct styling (be sure to test hover, click, tooltips, etc)

Add specificity to root selector to avoid conflicts in Calypsoified wp-admin.

---

assets/stylesheets/_components.scss
classes/class-wc-connect-stripe.php
classes/class-wc-rest-connect-stripe-oauth-init-controller.php
client/apps/stripe-connect-account/style.scss
client/apps/stripe-connect-account/view-wrapper.js

Fixes https://github.com/Automattic/woocommerce-services/issues/1500
_Edit:_ <s>Fixes https://github.com/Automattic/woocommerce-services/issues/1526</s> (already fixed by https://github.com/Automattic/woocommerce-services/pull/1547)
Closes the loop for the "Connected Stripe account" section of the Stripe settings (added by WooCommerce Services) by adding an entry point for the merchant to connect their account into the Stripe settings, when no account is connected – replacing the "No account connected via WooCommerce Services" notice:
(The only existing ways to enter the OAuth flow and connect an account are a) via Calypso and b) via the wp-admin NUX banner that shows up after completing the OBW when a Stripe account already exists at the provided email.)
To test:
- With WooCommerce …

Add Stripe OAuth connect action into settings

---

client/apps/stripe-connect-account/style.scss
client/apps/stripe-connect-account/view-wrapper.js

Fixes #1558 
Attempts to generate OAuth url only once and then shows the error if it failed:
To test:
* On a site that's using HTTP navigate to the stripe settings page with dev tools open
* Verify that only one `oauth/init` request is sent and then the error appears
* Either upload the plugin to a site using HTTPS (such as wpcom) or modify `class-wc-rest-connect-stripe-oauth-init-controller.php` to always return some url
* Verify that the connection prompt appears as expected

Prevent multiple stripe oauth init requests when the site is not on ssl

---

client/apps/plugin-status/style.scss
npm-shrinkwrap.json
package.json
webpack.config.js

Fixes #1571 
A month ago, Calypso renamed its `checkmark.svg` file: https://github.com/Automattic/wp-calypso/pull/29590/files
Using Webpack, we're transforming all the CSS `url('something')` declarations into `url('https://wordpress.com/something')`. So, then Calypso removed the old `checkmark.svg` file from their deployments, all the checkmarks in our plugin stopped showing.
As a temporary fix, I've updated the `wp-calypso` dependency so our CSS files have the new `checkmark` SVG file reference.
Since we hadn't updated Calypso since a while, I had also to remove some non-semamtic color names that no longer exist (`$alert-yellow`, I changed the other `$alert-*` colors since I was at it), and added the [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties) plugin …

Update wp-calypso dependency, added PostCSS plugin to pre-compute CSS variables

---

classes/class-wc-connect-settings-pages.php

As of https://github.com/woocommerce/woocommerce/pull/21719 (slated for WC 3.6), "Shipping options" appear for unknown section slugs unless the settings are explicitly filtered.
As a result, they are showing up at the bottom of the WooCommerce Services settings screen – which performs an action to output a container but doesn't touch the default output:
This change simply filters those settings out, causing nothing to render below the React container.

Hide WC shipping options on WCS settings screen

---

classes/class-wc-connect-taxjar-integration.php

When investigating #1355 I noticed that during one of the tax code migrations we missed [one line](https://github.com/taxjar/taxjar-woocommerce-plugin/blob/898ffba09f4ac5422333d8914b9be3412bc6b3b0/includes/class-wc-taxjar-integration.php#L424).
This, in turn, [made one of the other fixes not work and fail silently](https://github.com/taxjar/taxjar-woocommerce-plugin/blob/898ffba09f4ac5422333d8914b9be3412bc6b3b0/includes/class-wc-taxjar-integration.php#L806).

Add missing return to calculate_tax method

---

assets/stylesheets/style.scss

Avoids slight misalignment in WooCommerce » Settings » Shipping » WooCommerce Services screen:
Before | After
-- | --
The issue was due to a `float` style being set in wp-admin [[#](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/css/forms.css#L124)], and the fix is to override it.
This change causes inconsistency in vertical alignment between checked and unchecked states in the Add a package » Service package view – this will be fixed in https://github.com/Automattic/woocommerce-services/pull/1581.

Fix checkmark alignment in settings by overriding wp-admin style

---

npm-shrinkwrap.json
package.json

Due to the introduction of `file:` dependencies to wp-calypso in https://github.com/Automattic/wp-calypso/commit/b4baa445637cafeda20e5e9cd1ab2e6daa744125, the dependency tracks a dedicated branch (`feature/woocommerce-services-dependency`) off of that commit's parent, rather than a snapshot of the master branch. For now, we will `cherry-pick` desired commits from `master` to this branch.
Note: I considered specifying the branch itself rather than a particular commit, as I figured we will essentially have full control over that branch, but in fact we will still benefit from a review process for introducing Calypso changes to the plugin build.
These commits have been cherry-picked to that branch, and included in this update:
- https://github.com/Automattic/wp-calypso/commit/fd7cbfda31d50410a …

Update wp-calypso dependency and regenerate shrinkwrap

---

package.json
readme.txt
woocommerce-services.php

Update `package.json`, `woocommerce-services.php`, and `readme.txt` with the new version number, tested up to version numbers, and the changelog.

Release version 1.19.0

---

webpack.config.js

After the `webpack-dev-server` dependency was updated in #1568 the dev console started being flooded with "Invalid host/origin header" error message:
I fixed it by modifying the config as suggested in this [SO answer](https://stackoverflow.com/questions/43619644/i-am-getting-an-invalid-host-header-message-when-running-my-react-app-in-a-we). There are some security concerns mentioned there, but they don't apply to us, since we're running the dev server only when developing and always ship the compiled bundle.

Fix the "Invalid host/origin header" when running the webpack dev server

---

classes/class-wc-connect-stripe.php
client/apps/stripe-connect-account/view-wrapper.js

Fixes https://github.com/Automattic/woocommerce-services/issues/1559, related to p7bbVw-31G-p2
- Change the title of the setting from `Stripe Account (connected to WooCommerce Services)` to `Connect via WooCommerce Services` if an account is not connected at all, or if it has not been connected through WCS.
- Change the text when an account has not been connected through WCS to `You’ve got WooCommerce Services installed. If you’d like, we can automatically copy keys from your Stripe account for you. Click here to connect your Stripe account using WooCommerce Services.`
- Install WCS on a fresh instance (or a disconnected one) and check if the strings, mentioned above, are displayed.
- On a connected website, make sure that the setting name is not `Connect via WooCommerce Services`.

Improved wording for the Stripe Connect UI when disconnected

---

classes/class-wc-connect-options.php
classes/class-wc-connect-stripe.php

Fixes #1605 
Improves detection of when the site is connected to stripe via oauth. Also handles the scenario where someone manually edits the API keys, i.e. stops displaying the account as connected.
To test:
* Checkout `master` and connect the account via the wizard (`/wp-admin/admin.php?page=wc-setup&step=payment`) or oauth if you have https available
* The Stripe settings page should show the account info and "connected to WooCommerce Services" header
* Checkout this branch and refresh the Stripe settings page
* The account info and the right header should still be there
* Deauthorize the account
* The account info should be gone and the header should prompt to connect
* Connect the account (either via wizard or oauth, see step 1)
* Manually edit one of the API keys and save
* The …

Stripe - Store the account keys to determine the connection status

---

classes/class-wc-connect-api-client.php
woocommerce-services.php

Fixes server's issue 1268
Serverside PR will need to be shipped first in order not to break the request validation with the new taxes_enabled field
To test:
* Checkout PR 1270 on the server
* Set your base state to CA or TX
* Confirm the notice appears as expected

Add ability to render server notices in the admin panel

---

woocommerce-services.php

Fixes #1592 
This is a simple fix for the issue - the underlying issue of communicating in the wizard that Jetpack is required to provision the Stripe account still remains and will require design input.
To test:
* On a fresh install, open the WooCommerce wizard
* Opt-in to have a Stripe account created
* Do NOT connect Jetpack and skip the step instead
* Finish the wizard
* On the Stripe settings page enter keys of an existing account (either live or test) and save
* Connect Jetpack now
* Stripe keys should remain the same (you can test by running `jQuery('#woocommerce_stripe_test_publishable_key').val()` in dev console or similar)

Fix overwriting manually entered Stripe account info

---

client/apps/shipping-label/view-wrapper.js

The button type was updated to primary, changing its colour, and the text was updated to `Create shipping label`. The translations were updated, since some text was changed.
Here's how I updated the translation files:
`npm run i18n`
`npm run i18njson`
Is that enough/correct? If so, I'll add it to the documentation
Before:
After:
Todo:
cc @aleftick

Update shipping label button to primary

---

classes/class-wc-connect-stripe.php

Fixes #1614 
To test, WP_DEBUG true and then, while not connected ala WooCommerce Services, enter Stripe keys manually on the Stripe settings page and then save those settings. Look in the PHP error log (and JavaScript console) for the updated error message.

Tweak stripe key error message slightly

---

npm-shrinkwrap.json
package.json
readme.txt
woocommerce-services.php

✅Updated `package.json`, `woocommerce-services.php`, and `readme.txt`
✅Create a changelog section in `readme.txt`
This PR includes changes from #1594 and #1615 for testing purposes since it's ready to be merged, and just needs to be tested.
To test please use the staging server instead of production using
`define( 'WOOCOMMERCE_CONNECT_SERVER_URL', 'https://api-staging.woocommerce.com/' );`
This is because this change is required in order for requests not to break:
https://github.com/Automattic/woocommerce-connect-server/commit/a529d68d1293a57291c74c44058e89b8578d5783
Settings requests now send a new parameter due to this commit:
https://github.com/Automattic/woocommerce-services/pull/1608/files#diff-57dabbbbd8e057f1082af23aa58d3f5aR535
1. ~Merge #1594~ Done
2. ~Merge #1615~ Done
3. Merge …

Release v1.20

---

classes/class-wc-connect-service-settings-store.php
classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-shipping-label-controller.php

Required for https://github.com/Automattic/wp-calypso/issues/30170
If a payment method isn't passed with the initial label purchase request, or the user _lacks permissions to manipulate it_, fall back on existing behavior of using stored default. Otherwise, use the provided payment method (passed as `payment_method_id` param) for the payment, and store it as a future default (see https://github.com/Automattic/wp-calypso/pull/22890#issuecomment-379033700).
(Besides this logic itself, the code change involves moving `can_user_manage_payment_methods` from  the settings API endpoint controller to the settings store.)
Can test by setting `formData.payment_method_id` prior to [this call](https://github.com/Automattic/wp-calypso/blob/8ad80271e0e97f627d1fafb99c74dc28ef823143/client/extensions/wooc …

Accept payment method via label purchase endpoint

---

classes/class-wc-connect-payment-methods-store.php

Context: the first available credit card was automatically selected...
- ...if there wasn't a selected card that was still available, as of https://github.com/Automattic/woocommerce-services/pull/488
- ...only if a previously selected card is no longer available, as of https://github.com/Automattic/woocommerce-services/pull/1076
This PR reverts the primary change in https://github.com/Automattic/woocommerce-services/pull/1076 – again automatically selecting a card so there are never available cards with none selected – as it is unnecessary for fixing the main issue in https://github.com/Automattic/woocommerce-services/issues/1073. _Edit:_ **now only does so there's just one card available.**
(I see now that @v18 was mentioned in that issue as the source for "we need the user to confirm …

Automatically select credit card if just one is available

---

.travis.yml
readme.txt

#1634 introduces namespaces, which are required by Jetpack 7.5
We need to require at least PHP 5.3 if we want to integrate with the latest Jetpack functionalities and make sure this plugin doesn't break. This PR adds this requirement and removes PHP 5.2 from Travis config.

Add PHP 5.3 requirement

---

classes/class-wc-connect-settings-pages.php

Fixes action priority so that the filter emptying the WC settings is added in time.
Not sure what's changed, but the `woocommerce_settings_shipping` actions had the same priority so it wasn't guaranteed that the `woocommerce_get_settings_shipping` filter (from https://github.com/Automattic/woocommerce-services/pull/1577) would be added in time – and it wasn't, for me:

Hide WC shipping options when showing WCS settings (again)

---

.travis.yml
npm-shrinkwrap.json
package.json
readme.txt
woocommerce-services.php

Closes #1632 
Also fixes our Travis CI setup so tests pass :P 
To test
- install and activate WooCommerce 3.7 RC1 or higher
- `rm -rf node_modules`
- `git submodule update --init`
- `npm install`
- `npm run dist`
- `npm test`
- `npm run release` to create the plugin zip
- install and activate this plugin from that zip
- connect jetpack if needed
- install and activate the staging plugin and ensure you can buy a test label OR...
- ensure you can buy an actual label and then refund yourself

1.21.1: Update for WooCommerce 3.7

---

webpack.config.js

After we moved the code from wp-calpyso/client/extensions to client/extensions, webpack was still using wp-calpyso/client/extensions to load some code because the path had not yet been updated. This PR updates the path so code changes in our repo actually have an effect.

Use extensions from local repo instead of calypso so we can make changes

---

webpack.config.js

Fixes #1665 
Testing:
1. Open page with WCS JS code.
2. Start woocommerce-services-plugins, using dev setup ( `npm run start` )
3. Make changes to the code
4. Observe changes.

Fix CORS policy for devServer.

---

client/extensions/woocommerce/woocommerce-services/state/packages/reducer.js

There's no need to reset the list of predefined packages when the modal
is dismissed, since it's repopulated whenever the modal is open.
Thanks to @bor0 for pointing out the root cause!

Fix a glitch when closing the "Add Package" popover

---

classes/class-wc-connect-nux.php

After moving the *Purchase label* button to the new position at the top the Nux notice is a little misaligned this will reposition it under the button. 
Before 
After

Align Nux notice with new button position

---

client/api/url.js
client/extensions/woocommerce/woocommerce-services/api/url.js

Fixes #1722 
Most of the urls defined in `client/api/url.js` were overloaded by the ones in `client/extensions/woocommerce/woocommerce-services/api/url.js`, which are the ones actually being used by the app.
To test it, just open every JS App in the extension and ensure all api calls are performed correctly.

Removes duplicated url constants

---

client/extensions/woocommerce/woocommerce-services/views/packages/package-dialog.js

Fixes #1735 
Service package selection changes were not being saved on the order page. 
This change triggers the save action after clicking `Add packages`:

Add save action for service packages

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/price-summary.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/shipping-summary.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/sidebar.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/style.scss

Fixes #1737.
Adds shipping summary:

Initial implementation of ShippingSummary

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js

Tweak conditional to select empty box also in the case where `userMeta.last_box_id` is set but to a non-existent box.
Fixes #1759.

Tweak conditional to select empty box properly

---

client/apps/shipping-label/view-wrapper-label.js
client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js
client/extensions/woocommerce/woocommerce-services/state/packages/reducer.js
client/extensions/woocommerce/woocommerce-services/state/packages/test/reducer.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/actions.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/reducer.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js
client/extensions/woocommerce/woocommerce-services/views/packages/package-dialog.js

Fixes #1748.
It is important to re-test these:
#1740 (button is blank during loading on order screen) cc @roykho 
#1669 (you're able to save of Package Dialog) cc myself
#1721 (I adjusted `getRatesErrors` to use new data structure, make sure it doesn't break anything) cc @c-shultz 
For the other fixes this PR is just adjusting the tests to correctly match the data structure.

Fix tests by updating some, and adjusting code for others

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js

When `normalizeAddress` and its API is not called to normalize the address, the `normalize` property would be `null`. In the case when we modify an address and click "Use address as entered", our reducer will try to use this `null` `normalized` property which cause the error for #1744. 
Only use the `normalized` prop when it is not falsy, otherwise, fallback to `values`
Closes #1744

Fall back to values if normalized is null

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/index.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/list.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/list.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss

Closes #1743 
Brings back original package selection design:
Adds section headers to rates lists for separate packages:

Fix multi-package support

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/style.scss

Add margin top to match figma design.
I am guessing it requires a new line thus i am using 24px. 24 pixel is the line height in the figma design link https://www.figma.com/file/jo5qL6bf67c5Z7DyxUpMgf/WCS-Middle-ground?node-id=69%3A0. Please let me know otherwise.
Currently:
After fixed:
Closes #1769

Add margin top to total to match figma design

---

client/admin-pointers.js

Admin tooltips were being called to early in the loading process of the admin page. This was causing some tooltips to be displaced if the page hadn't fully loaded and the elements the tooltips are attached to change their position once the page is fully loaded.
Closes #1760

Fixes loading of admin tooltips.

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/shipping-rate.js

Fixes #1771 
Allows 'free' signature confirmation for USPS Express service. All other signature rates that are the same as non-signature rates are assumed to be invalid rate options. I believe this logic should handle all the cases we're concerned with.
/cc @budzanowski

Whitelist free signature confirmation for Express service.

---

client/apps/shipping-label/view-wrapper-label.js

Don't do assumptions about what is in the events logs. Extract purchase and refund events and then do a diff and see if we have non-refunded ( active labels )

Calculate number of non refunded labels and not just labels purchase events.

---

classes/class-wc-connect-payment-methods-store.php

Use property_exists() as we are dealing with an object and array_key_exists is deprecated in PHP 7.4
Fixes this error found in the logs:
```
PHP message: PHP Deprecated:  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in wordpress-5.3/wp-content/plugins/woocommerce-services-release/classes/class-wc-connect-payment-methods-store.php on line 110
```

Fix notice in php 7.4

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/price-summary.js

Use proper package name in price summary.

---

tasks/i18n.js

Generates the .pot file using the already linked calypso-i18n cli libraries.
Closes #1785.

Adds .pot generation to tasks/i81n.js

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/index.js

Fixes #1823.
An additional change was made around rates selection step expand/collapse logic. If there was only one rate and it was preselected the rates step was collapsing and thus hiding the signature select dropdown. I think ( this is a design decision ) that keeping the step always open makes sense as the merchant knows more clearly what was automatically selected.

Preselect rate when there is only one rate available.

---

assets/stylesheets/style.scss
client/apps/shipping-label/style.scss

Also make style better when located on the sidebar.
Closes #1830
Shipping label box can now be dragged back to the sidebar if so desired. Display in sidebar should be same as on small screen.

Fix metabox when it's in the sidebar.

---

tasks/i18n.js
webpack.config.js
woocommerce-services.php

Closes #1856
Renames all files in dist/ to something like woocommerce-services-1.22.2.js.
This is my preferred solution to the caching problem we have with over optimizations done by some plugins. It'll be fine so long as we keep the version in packages.json up-to-date.
Test. Run plugin in dev mode make sure basic functions work.
run `npm run release`
Ensure plugin in release/woocomerce-services.zip can be installed and activated and basic functions work. Be sure to turn off dev constants like `WOOCOMMERCE_CONNECT_DEV_SERVER_URL`

Use version number to generate asset filename

---

classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-shipping-label-controller.php

Don't save and don't provide "individual" as last box id.
I think that this actually fixes:
Fixes: https://github.com/Automattic/woocommerce-services/issues/1864
This solves this screen:
It happens when user has sent a package as individually packaged. Later moved to another order. that has different items.

Fix last box id for individually packed items.

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/sidebar.js

This fixes: #1877 
The paper selector is no longer there when the payment method is not selected.

Hide paper selection until valid payment method is selected.

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js

Whenever payment fails, add a link to credit cards settings to the payment failure notice.
Fixes: #1874

Add link to CC settings on purchase error.

---

client/apps/shipping-label/view-wrapper-label.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/index.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/purchase-button.js

closes #1883
translate allow for 2 parameters to hold the plural case and allow for proper translations to be made.
See https://github.com/Automattic/wp-calypso/tree/master/packages/i18n-calypso#pluralization

Use plurals properly

---

classes/class-wc-connect-service-settings-store.php

closes #1862
To test: 
add a ' to your Site Title in WP -> Settings -> General.
Delete any saved origin address in the option `woocommerce_connect_origin_address` 
Create a new label.
&#039; should not appear on the label.

decode html entities to avoid &#039; from appearing on the label

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/move-item.js

Remove "Remove from package" dropdown in order page.
This PR revert part of https://github.com/Automattic/woocommerce-services/pull/1813/files
1. Create an order with multiple items
2. Proceed to checkout 
3. Open order page
4. Confirm there is no "Remove from package" option anymore.
Closes #1876

Remove "Remove from Package" option in order page

---

classes/class-wc-connect-taxjar-integration.php

When country is UK, the shipping address allow county to be a text field. This text field does not respect a "state code" format (ie. 2 letters). This creates a problem with WooCommerce core's tax code. While the core team is working on the issue, we are going to patch this by disabling county in the tax field for automated tax. County is optional and this change will not break tax rate.
County is optional field for UK. https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order
By removing the county field, WooCommerce core will insert this entry as `*` which can match any county.
1. Set store address to an UK address, https://localhost/wp-admin/admin.php?page=wc-settings&tab=general. We can use the ones from the issue, (e.g. 63 Elford Crescent, Plympton, Plymouth, …

Ignore county when country is UK for automated tax

---

classes/class-wc-connect-jetpack.php

have to use \Automattic\Jetpack\Status::is_staging_site() when it exists
Test on Jetpack 7 and Jetpack 8.1+. No deprecation notices should show.

Jetpack::is_staging_site() is deprectated in Jetpack 8.1

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js

Applying the first solution suggested in the issue https://github.com/Automattic/woocommerce-services/issues/1900. 
Since the request hardly completes in 1 second, the polling for the first couple of seconds aren't necessarily. Instead, delay the first call by a factor of 2 and then continue to poll per second. 
**Impact:**
Minimum label purchase time will change from `1` second to `2` seconds. This may delay some purchasing. Based on some data on the server side, the request seems to take between 1 to 2 seconds. 
Closes #1900

Delay the initial label status call by 1 seconds

---

.eslintrc.js

closes #1937
I believe the changes were needed so e2e would pass but they overrode some parts of ./wp-calypso/.eslintrc. 
This just appends the required keys.

Fix build errors

---

client/main.js

Place redux stores in a global called wcsAppStores so the store can be interacted with by external dependencies.
This will allow us to open the shipping label modal by dispatching an action as was done in this PoC: https://gist.github.com/c-shultz/f15f124c45afdc4201ba033fef9c35ee#file-wcs-autoload-php-L94

Expose wcs redux stores 

---

changelog.txt

The changelog had a typo. Jetpack was spelled as Jatpack and it was brought up by a user on the forums. :)

Modify changelog typo [Jatpack to Jetpack]

---

classes/class-wc-connect-taxjar-integration.php

closes #1954
Test:
Set country to United Kingdom
Install WC 4.0
Ensure WooCommerce->Settings->Taxes has the Automated taxes option and that it works.

Fix automated taxes for GB with WC 4.0

---

classes/class-wc-connect-jetpack.php

Introduced in https://github.com/Automattic/woocommerce-services/pull/1931 and just noticed on an unrelated build error.

Change construct which does not work in PHP 5.3

---

assets/stylesheets/style.scss
npm-shrinkwrap.json
package.json

closes #1951 
different version of wordpress/components in wcs and wc-admin cause conflicts with the tooltips. Fixing this by updating to the same version. Calypso checkboxes looked funny so hid the wordpress/component part.

Fix hidden tooltips when wc-admin is installed 

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/sidebar.js

Remove duplicated propType to resolve ` error  Duplicate key 'updatePaperSize'  no-dupe-keys` error when running `npm run start`
Close https://github.com/Automattic/woocommerce-services/issues/1967

Remove duplicated propType

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/reducer.js

Closes #1950
Allow modal to close if "Create shipping label" goes through the "print" button flow.
In our reducer, `isSubmitting` is set to true when we are purchasing or processing refund. `isSubmitting` is set to `false` once these are done. We also set `isSubmitting` to false in `WOOCOMMERCE_SERVICES_SHIPPING_LABEL_EXIT_PRINTING_FLOW`. 
But when we have this "Print" button step in between printing and exiting, the `isSubmitting` is still set to true, causing the modal to not being able to close. Fix this by setting `isSubmitting: false`.

Change isSubmitting state to false once printing button is shown

---

client/apps/shipping-label/view-wrapper-label.js
client/extensions/woocommerce/woocommerce-services/lib/initialize-labels-state/index.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js

Closes #1948.
When the order should be marked as completed when a shipping label is bought, this PR updates the order detail section and the order notes, to reflect the changes performed by the label purchase action.

Update order detail page if order is fulfilled

---

client/extensions/woocommerce/state/sites/orders/notes/reducer.js

After purchasing a label this error will show:
Uncaught (in promise) TypeError: Invalid attempt to spread non-iterable instance
If the notify customer option is checked.
Problem is `state[ orderId ]` can be undefined which would not work with the spread operator `...`

Fix  Invalid attempt to spread non-iterable instance warning

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-item.js

I refactor the destructor of this.props to get all the vars without using the label object. I missed a spot.
Refund button works now.

Fix Refund option

---

client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js
client/extensions/woocommerce/state/sites/orders/activity-log/test/selectors.js

Fixes #1984 
To test:
- Create new order (order cannot have any existing labels)
- Purchase label and print
- Close shipping modal
- Check Shipment Tracking metabox
Confirm that no invalid date notes appear. Should look like:

Hide customer note from shipment tracking metabox.

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/shipping-rate.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/test/shipping-rate.js

Closes https://github.com/Automattic/woocommerce-services/issues/1993
The data received for `delivery_date` is in the format of string. Updated type and updated test.
To test, open up console. Make sure label purchase process does not have this error anymore.

Update delivery_type to string since the API returns string

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss

Fixes #1989
Removes the fixed height for service options and replaces it with padding to improve desktop view and make the mobile view more usable.
Desktop view:
Mobile view:
The mobile view is not perfect but it's much more usable.

Improve padding between service choices

---

client/apps/shipping-label/view-wrapper-label.js
client/extensions/woocommerce/state/sites/orders/actions.js
client/extensions/woocommerce/state/sites/orders/notes/actions.js
client/extensions/woocommerce/state/sites/orders/test/actions.js
client/extensions/woocommerce/state/sites/orders/utils.js
client/extensions/woocommerce/woocommerce-services/lib/initialize-labels-state/index.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js

Closes #1987
Test:
Change order status to 'failed'
Purchase a new label.
Order status should not be changed to 'completed'
Also notes should be updated without a refresh.

Fix order status changing after purchasing label

---

classes/class-wc-connect-account-settings.php
classes/class-wc-connect-continents.php
classes/class-wc-connect-jetpack.php
classes/class-wc-connect-package-settings.php
classes/class-wc-connect-shipping-label.php
classes/class-wc-rest-connect-account-settings-controller.php
classes/class-wc-rest-connect-packages-controller.php
classes/wc-api-dev/class-wc-rest-dev-data-continents-controller.php
client/apps/shipping-label/index.js
client/extensions/woocommerce/woocommerce-services/lib/initialize-labels-state/index.js
tests/php/test_class-wc-connect-shipping-label.php
woocommerce-services.php

Removes the preloading step in the create shipping label component and provides it with all the that it needs from the PHP side.

Remove spinner from create shipping label button

---

classes/class-wc-connect-taxjar-integration.php

We changed the name of javascript files to contain the version and this broke this js file which is loaded on the new order page.

Fix 404 of taxjar.js on new order page

---

tests/e2e-tests/fixtures/account_settings.js
tests/e2e-tests/specs/admin/shipping-settings.test.js
tests/e2e-tests/utils/index.js

Closes https://github.com/Automattic/woocommerce-services/issues/1916
Not to cover everything using E2E tests but to cover critical user flows that would affect WCS experience inside the settings page.
- Toggling, save change
- Changing paper size, save change
- Email Receipts, check box should display recipient name and email based on their `account/settings` info,  `Email the label purchase receipts to harris (harris) at harris@localhost.com save changes`
- Add a new card
- Remove card when there is 1 card
- 0 card
- Add new custom package
- Add new service package
- Edit package
- Delete package

Add e2e test for toggling shipping label

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/test/selectors.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/price-summary.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/style.scss

closes #2037
Adds a notice in sidebar that UPS account will be charged. Also adds carrier name next too each item in the price summary. 
Extracts Carrier name from title which includes both the carrier and service separated by a dash. I considered passing the carrier name in a field by itself but this would require changes to the connect server and changing the API versioning so it seemed better just to parse the existing title field.

Add carrier name to price summary and UPS carrier charge notice

---

classes/class-wc-connect-taxjar-integration.php

closes #2019
Looks like ![image](https://user-images.githubusercontent.com/1534605/82251676-de81e980-990a-11ea-8ecf-7e0fe7285c6b.png)
There may be an issue with adding links in the tooltips as it's impossible for me to hover over the tooltip and click on the link. I the problem may be limited to me and my browser/OS combination so I'd like to know if others can click on the link.

Show which nexus automatted taxes will work with and link to doc

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js
woocommerce-services.php

Closes https://github.com/Automattic/woocommerce-services/issues/2045
Update our code to retrieve `shipment_id` using WCS server API v3. In v3, the `shipment_id` no longer comes from `form.rates.available[ pckgId ][ rateType ]` but `rate` object itself. 
- This requires WCS server API v3 to be in place. If not, we can't release this.
1. Pull this branch
2. checkout an item 
3. Purchase a label
4. Rates should continue to show

Use shipment_id from rate object instead

---

changelog.txt
classes/class-wc-connect-taxjar-integration.php

Fixes #2060 
How to test:
The issue was a little challenging to get to reproduce because I had a customer address with a zip code already set. You'll want to make sure you can reproduce #2060 without this branch before testing it.
1. Use PHP 7.4 (a new Jurassic Ninja site defaults to this)
1. Enable automated taxes
1. Add a taxable product to cart
1. Go to checkout with no zip code set in address
1. Make sure no notices appear

Fix PHP 7.4 notice for taxes at checkout.

---

client/extensions/woocommerce/woocommerce-services/components/carrier-icon/style.scss
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss

This is a style sheet-only fix to improve readability of the service listings in the shipping label modal, mainly tweaking the margins within the flex container. These changes will be especially noticable at smaller screen sizes. 
- Made the carrier logos consistent in size (they were decreasing in size with each row)
- Adjusted margins in the flex container for better readability (added some white space between the divs)
- Right aligned the detail text for time frame so it doesn't run into the services detail text
I tweaked a few things to get everything looking right so please have a look and let me know if this all makes sense!

Improve service listing readability

---

classes/class-wc-connect-taxjar-integration.php
client/new-order-taxjar.js
webpack.config.js

Closes #2072
How to test
1. Load an order page
2. Make sure there is no missing taxjar.js error
3. Make sure we can still do manual refund on order per https://github.com/Automattic/woocommerce-services/pull/2047.
4. `develop` should now contain changes from https://github.com/Automattic/woocommerce-services/pull/2047.

Re-apply revert from PR-2047

---

classes/class-wc-connect-settings-pages.php
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/index.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/index.js

Does not render the carriers card in WooCommerce Services settings
when there are no additional carriers enabled for that site.
Closes #2078 
1. To test this issue, this WooCommerce Connect Server PR's branch is needed: https://github.com/Automattic/woocommerce-connect-server/pull/1426
2. Enable UPS for the site under test.
3. The carriers card in WooCommerce Services settings at the bottom should be visible.
4. Disable UPS for the site under test.
5. The carriers card should be hidden now.

Hide the carrier cards when no carriers enabled

---

npm-shrinkwrap.json
package.json

`@wordpress/components` `v8.5.0` was missing the dependency
`@wordpress/element` `v2.10.0`
----
Closes #2071

Fix build warning due to missing package

---

client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/settings.js

Adds date placeholder in ups date field in carrier settings, which was lost in a merge commit.

Add placeholder for the invoice date field in carrier settings form

---

client/extensions/woocommerce/woocommerce-services/components/carrier-icon/index.js
client/extensions/woocommerce/woocommerce-services/components/carrier-icon/style.scss

Fixes #2087 
Fixes UPS logo dimensions on rates:
And settings:

CSS tweaks to fix UPS logo dimensions.

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-select.js

Closes #2104
To test
1. You can setup WCS to have empty packages in your list. Or you can modify [this line](https://github.com/Automattic/woocommerce-services/blob/develop/client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-select.js#L110) to `{ true || 0 === totalPackagesCount ? (` so that the `div` is forced to show.
2. Make sure no errors in console.

Replace string 20 to number 18 to match gridicons requirements

---

woocommerce-services.php

Closes #2090 
1. Create an order
2. Click "notify customer" to complete order
3. Go to mailcatcher to see the email
4. Verify the tracking link opens to a UPS tracking window.

Add missing UPS tracking link to email

---

package.json
tasks/i18n-download.js
tasks/i18n.js

Closes https://github.com/Automattic/woocommerce-services/issues/1973
Fix eslint errors so that pipeline can pass. Also added missing packages for tasks.

Fix eslint errors and install missing packages

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/dialog-styles.scss

Changing the "Disconnect Carrier" modal layout to fix the mobile behavior
Fixes https://github.com/Automattic/woocommerce-services/issues/2112 (ticket also references grid layout - done separately in https://github.com/Automattic/woocommerce-services/issues/2122)
- Ensure you already connected "UPS"
- Go to **Settings > WooCommerce Services**
- Click  "Disconnect" on "UPS"
- Go to mobile viewport
- Modal layout behavior is fixed:
- Text is wrapping
- Title is centered

fix: carrier disconnect modal layout

---

classes/class-wc-rest-connect-shipping-label-controller.php

Fixes #2102 by including a new array to the GET shipping labels API. This array includes `product_ids` associated with a shipping label. 
- Create a shipping label for an order with single or multiple SIMPLE products.
- Verify that the GET shipping labels API returns the `product_ids` that are associated with the shipping label in the `product_ids` array.
- Create a shipping label for an order with single or multiple VARIABLE products.
- Verify that the GET shipping labels API returns the `variable_ids` that are associated with the shipping label in the `product_ids` array.
- Smoke testing the API to ensure that existing functionality is not broken :) 
Note: I didn't find any unit tests to test this specific scenario but it's possible I missed something! Do let me know if I need to add …

Added array to get shipping labels API to include product ids associated with a shipping label

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/style.scss

Changing the table layout on the **Settings > WooCommerce Services** page
Fixes https://github.com/Automattic/woocommerce-services/issues/2112 (ticket also references modal layout - done separately in https://github.com/Automattic/woocommerce-services/issues/2121)
- Ensure you already connected "UPS"
- Go to **Settings > WooCommerce Services**
- Go to mobile viewport
- Layout behavior is fixed

fix: services management table layout

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js

Changing the message on the created note when an order is shipped with multiple carriers.
This new messaging simplifies the logic a bit.
I didn't find existing unit tests for this logic in the codebase 👀 
Fixes https://github.com/Automattic/woocommerce-services/issues/2113
- Create order with multiple items and packages
- Mark order as "Completed"
- Create the labels
- Choose USPS for one package and UPS for another
- Print label with this checked:

refactor: multi-carrier label orders note

---

changelog.txt
classes/class-wc-connect-taxjar-integration.php
client/extensions/woocommerce/components/address-view/index.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/settings.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/address-step/fields.js

Bringing more consistency on the "ZIP code"/"Postal Code" messaging
Fixes https://github.com/Automattic/woocommerce-services/issues/2091
Carrier connection:
Address selection (destination/source):

chore: ZIP/postcode/postal code messaging consistency

---

assets/stylesheets/style.scss
changelog.txt

**Description**
Removes the padding from the notices bar so that there is no gap between the icon and the border.
**Issue**
Fixes number 1 in #1971.
**Testing**
You should be able to test this fix on any of the notice bars in the WCS area. The linked issue called out the notice bar after purchasing a label in particular.
1. With WC store and WCS set up to print shipping labels, go to an order that is shippable.
2. Click on the Create shipping label button.
3. Provide any necessary information for addresses, packages, and shipping rates to get the Buy shipping label button active.
4. Click on the Buy shipping label button.
5. Once the request is processed, there should now be a notification (success or fail) with the icon flush against the notification border.
This notice bar appears in …

Remove padding from the notices bar

---

assets/stylesheets/style.scss
changelog.txt

**Description**
Changes the color of the is-busy state on the primary buttons to use the appropriate brand color.
**Issue**
Fixes number 3 in #1971.
**Testing**
You should be able to test this fix on any of the primary buttons in the WCS area. The issue called out the button on the Buy Shipping Label button in particular as this button will have typically have the is-busy state the longest.
1. With WC store and WCS set up to print shipping labels, go to an order that is shippable.
2. Click on the Create shipping label button.
3. Provide any necessary information for addresses, packages, and shipping rates to get the Buy shipping label button active.
4. Click on the Buy shipping label button and while the purchase is processed, the button should have the pink colors with animated slashes …

Fix button is-busy color to use pink

---

.travis.yml
changelog.txt
classes/class-wc-connect-order-presenter.php
classes/class-wc-connect-shipping-label.php
tests/php/bootstrap.php
tests/php/test_class-wc-connect-order-presenter.php
woocommerce-services.php

Closes https://github.com/Automattic/woocommerce-services/issues/2116
WCS 1.24.0 [initializes order](https://github.com/Automattic/woocommerce-services/blob/d7f915ed13cb53dea0118325da0d912e93b8d501/classes/class-wc-connect-shipping-label.php#L420) as the initial states of the react app. 
Currently, `$order->get_data()` returns a PHP object of the order. This object is not suitable to output as `json_encode()`, some of its protected fields are not generated, resulting a `{}` at the end. 
We should transform this order object to something that can be represented as a JSON object. This can be done similar to [Woo core's API](https://github.com/woocommerce/woocommerce/blob/cbfe4bd59587aadb4b6c6e95a5787bebe3925310/includes/legacy/api/v3/class-wc-api-orders.php#L142-L320). 
1. Go to an order …

Transform order object to a presentable API object

---

client/admin-pointers.js
client/apps/shipping-label/index.js

Looks like there's an unsafe access to `packagesSettings.formSchema.custom.items`.
In fact, it can happen that the `custom` property is `null`, causing JS to break.
I think it would be nice if [client/admin-pointers.js](https://github.com/Automattic/woocommerce-services/blob/develop/client/admin-pointers.js) was _Reactified_ , so that it could be tied to the React lifecycle, maybe?
It happens to be `null` on a new installation, in this scenario:
- `packageSettings` is generated: https://github.com/Automattic/woocommerce-services/blob/develop/classes/class-wc-connect-shipping-label.php#L422
- `packageSettings.custom` is generated: https://github.com/Automattic/woocommerce-services/blob/develop/classes/class-wc-connect-package-settings.php#L29
- `packageSettings.custom` is `null` at …

fix(ShippingLabel): unsafe access to formSchema.custom

---

changelog.txt
package.json
readme.txt
woocommerce-services.php

- Added new changelog version
- Fixed line from https://github.com/Automattic/woocommerce-services/pull/2135 to appear in the correct version

chore: merge `master` into `develop`

---

changelog.txt
classes/class-wc-connect-shipping-label.php

Introduces a `wc_connect_meta_box_payload` filter that can be used to modify the order data used for label printing.
Restores compatibility with Product Bundles and Composite Products. See https://github.com/Automattic/woocommerce-services/issues/2133

Add 'wc_connect_meta_box_payload' filter

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/state/carrier-accounts/actions.js

**Description**
The error message presented when connecting a UPS account fails was too generic. This error message has been updated to give the user more direction on how to address the problem.
> There was an error connecting to your UPS account. Please check that all of the information entered matches your UPS account and try to connect again.
**How to Test**
1. Start with a WCS site with UPS enabled, but not connected.
2. Go to the WCS Settings page and click Connect for UPS.
3. Enter the relevant information, but with a bad phone number (5555555555, 10-digits).
4. Click Connect and confirm the above error message is displayed.
**Fixes**
Closes #2149

Update error message for connecting carrier error

---

classes/class-wc-connect-settings-pages.php

----
Closes #2050
To test it, just go to the UPS settings form screen. The breadcrumbs should be there:
`/wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings`

Displays breadcrumbs in carrier settings form

---

changelog.txt
client/extensions/woocommerce/state/sites/shipping-methods/selectors.js
client/extensions/woocommerce/state/ui/shipping/zones/methods/reducer.js
client/extensions/woocommerce/woocommerce-services/components/carrier-icon/index.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/tracking-link.js
woocommerce-services.php

**Summary**
The logo, tracking links, and service names were using different IDs for DHL Express, this PR updates them all to be using the new ID of `dhlexpress`.
**How to Test**
1. Set up WC with WCS site.
2. Enable DHL Express for the site by setting the can_use_dhlexpress flag.
3. Place a non-domestic order on the site.
4. Go to create the shipping label for the order.
5. Confirm that the DHL logo is displayed in the Label Rates.
6. Purchase label and confirm that a tracking link is provided.
**Fixes**
Fixes #2173

Update DHL Express names

---

client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss

Closes https://github.com/Automattic/woocommerce-services/issues/2170
Vertical align carrier logo in rate step.
1. If you don't have DHL rates, then go to https://github.com/Automattic/woocommerce-services/blob/develop/client/extensions/woocommerce/woocommerce-services/components/carrier-icon/index.js#L18 and change `uspsLogo` to `dhlExpressLogo` to test.
2. Go through label purchasing, and you should see the label vertically aligned now.
3. Make sure UPS/USPS/DHL all show up properly.

Align carrier logo vertically in flex box

---

client/apps/shipping-label/index.js
client/apps/shipping-label/view-wrapper-label.js
client/main.js
webpack.config.js

Closes https://github.com/Automattic/woocommerce-services/issues/2141
Updated chunks from `[name]` to `[chunkhash]` to address reduce filename size and to remove `~` in chunk filenames. I removed `id`, `name` form the `chunkFileName` since we don't really need that anymore. I kept `chunkhash` for cache busting purposes. I also added `chunkFileName` to the `MiniCssExtractPlugin` so that the chunks are now named with `chunkhash`, and placed properly in the `chunks` folder.
Before:
After:
1. Pull this branch and run `npm run start`.
2. Open webpack dev server http://localhost:8085/chunks/ and you should see a bunch of `<hash>.css` and `<hash>.min.js`
3. Go to WooCommerce > Orders, and you should still be able to create a label.
4. You can also open up network tab and see all the chunks show …

Change webpack chunks from [name] to [chunkhash]

---

woocommerce-services.php

Closes https://github.com/Automattic/woocommerce-services/issues/2165
Remove the `'updates'` dependency since WP has it inside script-loader by default. 
The select-all feature checkbox stopped working when WCS's `wc_connect_banner` has a `updates.min.js` dependency in it. When we add `'updates'` as dependency in `wp_register_script()`, it seems like it moved `<script src='https://localhost/wp-admin/js/updates.min.js?ver=5.5.1' id='updates-js'></script>` to the `<head>`. When this happens, for some reason, the [event handler](https://github.com/WordPress/WordPress/blob/master/wp-admin/js/common.js#L1170 ) from WP's `common.js` is removed, as shown in [here](https://github.com/Automattic/woocommerce-services/issues/2165#issuecomment-690726954). By removing `'updates'` dependency, the …

Remove wp-admin dependency from banner

---

changelog.txt

Adding some missing changelog entries to prep for 1.24.3: https://github.com/Automattic/woocommerce-services/pull/2181

Update changelog entries

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/settings.js

**Summary**
When connecting a UPS account through WooCommerce Services, the browser would prompt the user with the "Leave site? Changes you made may not be saved." dialog. This is browser behavior that is bound to the `window.onbeforeunload` event when it thinks there were changes to a form that weren't saved. In this case the submission is done through AJAX and the form on the page isn't being used for submission so the browser thought there were unsaved changes. This fix unbinds the `window.onbeforeunload` event right before redirecting on a successful submission.
**How to Test**
1. Start with WC and WCS set up for the site.
2. Enable UPS for the site.
3. From the WooCommerce > Settings > Shipping > WooCommerce Services click Connect next to the UPS Account in the Carrier Account table. …

Fix UPS connect redirect prompt

---

changelog.txt
classes/class-wc-connect-shipping-method.php

PHP8: The glue must be the first parameter to implode().
Detected via PHPCompatibility:
```
FILE: ...oocommerce-services/classes/class-wc-connect-shipping-method.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
614 | ERROR | Passing the $glue and $pieces parameters in reverse
|       | order to implode has been deprecated since PHP 7.4 and
|       | is removed since PHP 8.0; $glue should be the first
|       | parameter and $pieces the second
|       | (PHPCompatibility.ParameterValues.RemovedImplodeFlexibleParamOrder.Removed)
----------------------------------------------------------------------
```

PHP8: The glue must be the first parameter to implode().

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/index.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/purchase-section/test/index.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/index.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/list.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/shipping-rate.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/sidebar.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/test/sidebar.js

**Summary**
Since UPS labels are charged to the user's connected UPS account there is no need for them to have a payment method on file with WCS to purchase a UPS label. This update adds the `carrierId` to the selected rate data so that it can be checked if a label purchase is allowed with no payment method. Currently the only `carrierId` that does not require a payment method is UPS. 
**How to Test**
1. With WC and WCS set up on a site and UPS enabled.
2. Connect a UPS account.
3. Remove any payment method attached to the account.
4. Go to print a shipping label for an order that would provide UPS rates.
5. Select a USPS rate and see that the sidebar prompts to add a credit card.
6. Select a UPS rate and see that the label size dropdown and buy label button are present.
7. Click Buy …

Allow UPS Label Purchase with no payment method

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/shipping-rate.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/test/shipping-rate.js

Closes https://github.com/Automattic/woocommerce-services/issues/2193
Render `Insurance ($100)...` if `insurance` is a number. Render `Insurance (<some-text>)...` if `insurance` is a string.
1. Pull this branch
2. Create a label
3. The insurance amount should continue to show if and only if the amount is > 0.

Use string validation for insurance

---

changelog.txt
classes/class-wc-connect-nux.php
classes/class-wc-connect-shipping-label.php

Adjustments on the admin "pointers"/"popovers" displayed on the orders page.
Closes https://github.com/Automattic/woocommerce-services/issues/2196
In order to see the "new user" pointer with adjusted messaging:
- PLEASE MAKE SURE IT IS A BRAND NEW SITE - there should be no previously created labels/no pointers displayed
- Create a new order
- Destination can be domestic or international
- See pointer in order management view
- Feel free to change the DHL flag(s), to ensure that the messaging is adjusted
In order to see the "print dhl labels now!" pointer:
- PLEASE MAKE SURE IT IS AN EXISTING SITE - labels should have been created and the updated version of the plugin should not have run
- Go to an existing order
- Make sure order destination is international (not domestic)
- Make sure …

feat: adjusted messaging on label pointers

---

client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js

After a shipping label is purchased, if it needs a customs form to be printed, this patch creates an info
note for the user, and opens the customs form in a new browser tab.
1. Patch WooCommerce Connect Server to make it always include a commercial invoice:
``` javascript
1 file changed, 2 insertions(+), 1 deletion(-)
lib/shipping/easypost-client/index.js | 3 ++-
modified   lib/shipping/easypost-client/index.js
@@ -352,7 +352,8 @@ const buyShipment = ( shipment, rateToBuy ) => {
const extractCommercialInvoiceFromShipment = ( shipment ) => {
if ( shipment.forms ) {
for ( const form of shipment.forms ) {
-			if ( FORM_TYPE_COMMERCIAL_INVOICE === form.form_type && ! form.submitted_electronically ) {
+			// if ( FORM_TYPE_COMMERCIAL_INVOICE === form.form_type && ! …
```

Open customs forms in new browser tabs

---

changelog.txt
woocommerce-services.php

The email notification to customers with the shipment tracking information was displaying DHLEXPRESS as one word instead of DHL EXPRESS. This was due to the fact that the carrier name was generated by making the carrier ID uppercase, but the `dhlexpress` carrier ID is all one word for other compatibility reasons. I chose to do a lookup for the service `carrier_name` instead of hardcoding the name to limit the number of places we'd have the carrier name hardcoded. This comes with a slight performance hit, but allows for much easier updates/additions to carrier names.
Fixes #2218 
1. Start with a WC and WCS site set up with DHL Express enabled.
2. Place an order that DHL Express would be able to fulfill (international).
3. Go to the order and purchase the shipping label. Be sure to check …

Lookup carrier name for email tracking URL

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/state/shipping-label/selectors.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-refund-modal.js

Adjusting the refund copy for DHL Express labels.
Closes https://github.com/Automattic/woocommerce-services/issues/2217
- Purchase a DHL Express label
- Request refund
- Refund days should be 31
---
- Purchase another label (e.g.: USPS)
- Request refund
- Refund days should be 14

feat(DHL): adjust refund days copy

---

changelog.txt
classes/class-wc-rest-connect-shipping-label-controller.php
client/extensions/woocommerce/state/sites/orders/activity-log/selectors.js
client/extensions/woocommerce/state/sites/orders/activity-log/test/selectors.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-item.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/test/label-item.js

USPS letters are not eligible for refunds as they are untracked.
This PR disables the `Request a Refund` button for USPS labels when the package has the value `is_letter = true` and shows a tooltip message `USPS letters are not eligible for refund`.
This PR adds `is_letter` to label metadata when a label is purchased. Labels purchased before this PR will not have that information and thus the button will not be disabled. As labels are only refundable for a certain amount of time, overtime the difference will disappear.
closes #2120 
1. With WooCommerce Shipping and Tax ready to purchase labels, place an order on your store.
2. Edit the order, click on Purchase a Label, verify the addresses and select a package that is a USPS envelope.
3. Select one of USPS services and finish purchasing …

Disable refund button for USPS letters.

---

composer.json
lint-staged.config.js
package.json
phpcs.xml.dist

Add phpcs with WooCommerce-Core rules to pre-commit hook. This only runs [WooCommerce-Core ](https://github.com/woocommerce/woocommerce-sniffs) on committed changes, not on all files. THis is similar to [how WooCommerce Admin is setup]( https://github.com/woocommerce/woocommerce-admin/blob/37f92a5cf142a8bd2b055e16b451307b2a2dd095/lint-staged.config.js#L8).
**Updated - Oct 16, 2020**
I [removed](https://github.com/Automattic/woocommerce-services/pull/2212/commits/c402222c1a5ccca3465fa3b0073a21859ee2fbf8) `phpcs` from pre-commit hooks. There were too many linting errors and it will slow down development. I have removed this for now until we addressed most of the linting errors. To run `phpcs`, you will have to do this manually with `composer run phpcs`.
Closes …

Add phpcs with WooCommerce-Core rules to pre-commit hook

---

changelog.txt
classes/class-wc-connect-jetpack.php

This PR uses the method [is_offline_mode](https://github.com/Automattic/jetpack/blob/d6dfd9c34b18c5e378b9ed2a2674bc2212b289df/vendor/automattic/jetpack-status/src/class-status.php#L37) instead of the deprecated (since Jetpack 8.0) [is_development_mode](https://github.com/Automattic/jetpack/blob/e940e90c3f26a6f24f8e7fccd72a1dd6360be2b5/class.jetpack.php#L1676).
Note: [There was no deprecation notice](https://github.com/Automattic/jetpack/blob/e940e90c3f26a6f24f8e7fccd72a1dd6360be2b5/class.jetpack.php#L1669).
closes: #2202 
Turn on Jetpack Offline mode [with any of these methods](https://jetpack.com/support/development-mode/).
On your site, go to WP-Admin > WooCommerce > Settings > Shipping > WooCommerce Shipping
Verify that you get the following message:
If Jetpack was connected, the …

Use is_offline_mode instead of deprecated is_development_mode.

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/lib/utils/pdf-support.js

On some iPad devices, `navigator.userAgent` stopped including `iPad` in the string. This causes our logic to fallback on using `print()`, resurfacing [this problem](https://github.com/Automattic/woocommerce-services/issues/1166). 
Closes https://github.com/Automattic/woocommerce-services/issues/1166
1. Use an iPad with Safari. Use the iPad (7th generation) if possible. 
1a. Alternatively, use browserstack and choose these iPad:
2. Go to your store and click re-print label in the "Shipment Tracking" block
3. The label should open in a new tab instead of closing the modal itself.

Fallback to open PDF in new tab if Safari does not print natively

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/state/carrier-accounts/selectors.js

Provide some client-validation for the postal code field on the UPS signup form.
Closes #2180 
GIF of it working in action:
Verify also that it disables the Connect button when the ZIP/Postal code is incorrectly formatted(not a 5 digit number):
Not yet - but a full e2e test will be a great idea when we know how this form will look in its final form(it may be abstracted to allow for additional carriers).

Add ZIP code validation to UPS signup form.

---

composer.json
lint-staged.config.js
phpunit.xml.dist
tests/php/bootstrap.php
tests/php/test-class-wc-connect-api-client.php

Add composer to run existing test suites inside WooCommerce Services. Update `phpunit.xml.dist` to use `legacy` WooCommerce Core test utils. 
There is 1 failed test if we run against the latest WooCommerce Core. This will be fixed in another issue https://github.com/Automattic/woocommerce-services/issues/1631, where we will update our Travis pipeline to include a pipeline test to run against latest woo core.
Closes https://github.com/Automattic/woocommerce-services/issues/2211
Do you already have WordPress PHPUnit database/test setup? If so, skip to step 7.
1. Install `composer` if you don't have it already. Install it [globally](https://getcomposer.org/doc/00-intro.md#globally) so you can use it in any repo.
2. Run `composer install`
3. Make sure you have `wp-cli` installed. If not, …

Add composer command to run phpunit on WCS

---

changelog.txt
woocommerce-services.php

Our extension supports a minimum version of PHP 5.3; in versions of PHP less than 5.5 the function `getenv` only supports a single parameter: there is one instance of `getenv` with two parameters in our extension and this will cause a warning. 
`Warning: getenv() expects exactly 1 parameter, 2 given in woocommerce-services/woocommerce-services.php on line 55`
This fix removes that second parameter!
Closes #2025 
As of WordPress 5.2, WordPress requires PHP 5.6 or greater, so you will need a version older than this to see this warning.
As of WooCommerce 3.8, WooCommerce also requires PHP 5.6 or greater, so you will need to use an older version of this extension.
As of Jetpack 8.4, Jetpack requires WordPress 5.3 or greater, so you will need to use an older version of this extension too.
If …

Remove second parameter from getenv for php5.3 compatability

---

changelog.txt
classes/class-wc-connect-api-client.php
classes/class-wc-rest-connect-shipping-carrier-types-controller.php
tests/php/classes/test-class-wc-rest-connect-shipping-carrier-types-controller.php
woocommerce-services.php

This address the first bullet in https://github.com/Automattic/woocommerce-services/issues/2234. 
> Creating an endpoint in the plugin that can be used by the React front-end to get the fields from the Connect Server
https://github.com/Automattic/woocommerce-services/issues/2234
_If you can't make a request directly to your own localhost WC API. Refer to the "Steps to test with manual WooCommerce API Client"._
1. Assumes `shipping/carrier-types` end point is available from the server. You can use this [PR](https://github.com/Automattic/woocommerce-connect-server/pull/1597) if needed.
2. Make a GET request to your localhost's WooCommerce Services API `https://localhost/wp-json/wc/v1/connect/shipping/carrier-types` 
3. You should see a a similar response back after applying `json_decode()`: …

Create a new end point for carrier-types

---

changelog.txt
classes/class-wc-connect-api-client.php
classes/class-wc-rest-connect-shipping-carrier-types-controller.php
composer.json
phpunit.xml.dist
readme.txt
tests/php/bootstrap.php
tests/php/classes/test-class-wc-rest-connect-shipping-carrier-types-controller.php
tests/php/test-class-wc-connect-api-client.php
woocommerce-services.php

#2216 Add composer command to run PHPUnit
#2229 Fallback to open PDF in new tab if Safari does not print natively
#2230 Add ZIP code validation to UPS Sign up form
#2239 Create new endpoint for carrier types
#2241 Remove second parameter from getenv
This release branch is branched from latest `develop` 
- Test label purchase flow
- Test Store on WP.com
- Test ZIP code validation
- Test printing labels on iOS with Safari
- Test composer PHPUnit command
- Test in PHP 5.3 looking for getenv warnings
* Tweak - Add ZIP code validation to UPS(beta) signup form.
* Fix       - Issue with printing labels in some iOS devices through Safari.
* Fix       - Prevents warning when using PHP 5.5 or lesser
* Add     - Add new API end point to retrieve carrier registration requirements.
* …

Release 1.25.2

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/packages/input-filters.js
client/extensions/woocommerce/woocommerce-services/views/packages/package-dialog.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js

When adding a new package, the inputs for package dimensions will not allow you to start entering a number beginning with zero (e.g. decimals beginning with "0."). This is because there are `onChange` validation hooks on the inputs that clear out the field if the current value is non-positive (0 or negative). In addition, when submitting the form, the three dimension values are validated together as a string (`"{length} x {width} x {height}"`) against the regex `^(\\d+|(?:\\d*\\.\\d+)) x (\\d+|(?:\\d*\\.\\d+)) x (\\d+|(?:\\d*\\.\\d+))$`. This regex will match any non-negative values _including_ zero, so the validation relies on the hooks on the input field to prevent zero from being entered.
My solution is to loosen the validation in the `onChange` hooks, preventing negative values, but …

Allows package dimension input to begin with zero, still validates positive values

---

changelog.txt
classes/class-wc-connect-settings-pages.php
client/apps/shipping-settings/view-wrapper.js
client/extensions/woocommerce/woocommerce-services/api/url.js
client/extensions/woocommerce/woocommerce-services/state/carrier-accounts/actions.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/dynamic-settings-form.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/dynamic-settings.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/dynamic-settings-form.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/dynamic-settings.js

This PR address bullet 2 on https://github.com/Automattic/woocommerce-services/issues/2234
> Building a registration form that is dynamically built based on the list of fields for each carrier (the UPS account registration form at /wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings&carrier=UPS should be used as a design reference)
- No form validation on this page. Every carrier will be different and we are not supplied with their individual validation rules.
- Carrier description is in `Lorem ipsum` placeholder text.
Closes https://github.com/Automattic/woocommerce-services/issues/2234
1. Pull this branch, go to https://localhost/wp-admin/admin.php?page=wc-settings&tab=shipping&section=woocommerce-services-settings&carrier=DhlExpressAccount
2. You …

Dynamically generate carrier registration forms

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/state/carrier-accounts/selectors.js

The current form field validations when a user is connecting their UPS account don't always provide enough information to inform a user on how to correct them: in a few cases, the only validation present was checking non-empty values for required fields and in others the error lacked specificity. 
This PR adds the following validations for fields in this form.
- **UPS account number**: `The UPS account number needs to be 6 digits in length`
- **Phone number**: `The phone number needs to be 10 digits in length`
- **ZIP/Postal Code** (US only): `The ZIP/Postal code needs to be 5 digits in length`
- **UPS Invoice Number**: If present, `The invoice number needs to be 9 or 13 digits in length`
- **UPS Invoice Date**: If present, `The date must be a valid date in the format YYYY-MM-DD`
Closes …

Adds more specific regex validation to UPS connect form

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-item.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/test/label-item.js

Add a 'schedule pickup' link in the order notes for DHL Express labels.
Before:
After:
They will end up here wherein they can schedule a pickup:
https://mydhl.express.dhl/us/en/home.html#/schedulePickupTab

Add link to schedule pickup for dhlexpress.

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/shipping-rate.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/test/shipping-rate.js

Ensure that the correct number of arguments are passed to the parent ShippingRates component when checking "require signature" option when requesting a shipping label.
Closes #2185 
See the screencast in the original issue:
https://github.com/Automattic/woocommerce-services/issues/2185#issue-702784563
With this branch checked out you should see the prices updating when adding a signature:

Fix signature required checkbox not updating prices for label requests.

---

changelog.txt
classes/class-wc-connect-taxjar-integration.php

If an user created product with tax inclusive, then installed WCS or enabled automated tax. The tax will be calculated twice. This problem can be reproduced with the steps [here](https://github.com/Automattic/woocommerce-services/issues/1367#issuecomment-716715892). 
Closes https://github.com/Automattic/woocommerce-services/issues/1367
1. Go to WooCommerce Tax settings `wp-admin/admin.php?page=wc-settings&tab=tax`
2. Enable automated tax and make sure there is a message explaining why product's price needs to be exclusive of tax. 
1. Do we need to go through design for the location of this message?
2. This PR only adds a message to the user but does not address the duplicate tax problem - Products created with inclusive tax remains to be double taxed. [Automated tax + exclusive tax is by …

Add message to explain exclusive tax is needed for automated tax service

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-item.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/test/label-item.js

We disabled refunds for labels where package was of type 'letter'. The scope was too broad and after investigation, refunds for USPS are not available [when there is no tracking number](https://github.com/Automattic/woocommerce-services/issues/2242#issuecomment-730781298).
This PR disables refunds for USPS when the label has no tracking id.
closes #2242 
1. With WooCommerce Services enabled, place an order for a small item that fits in a letter
2. Purchase a USPS label for First class mail
3. Check that if the label has no tracking id, the refund button is disable and there is a message: "USPS untracked labels are not eligible for refund."
4. Purchase a label for USPS First class mail express or priority
5. Check that if the label has a tracking id, the request refund button is not …

Disable USPS refunds for labels without tracking id.

---

changelog.txt
classes/class-wc-connect-api-client.php
classes/class-wc-connect-functions.php
classes/class-wc-connect-settings-pages.php
classes/class-wc-connect-taxjar-integration.php
client/apps/shipping-settings/view-wrapper.js
client/extensions/woocommerce/woocommerce-services/api/url.js
client/extensions/woocommerce/woocommerce-services/state/carrier-accounts/selectors.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/dynamic-settings-form.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/dynamic-settings.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/dynamic-settings-form.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/dynamic-settings.js
client/extensions/woocommerce/woocommerce-services/views/packages/input-filters.js
client/extensions/woocommerce/woocommerce-services/views/packages/package-dialog.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-item.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-info.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/shipping-rate.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/test/shipping-rate.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/test/label-item.js
readme.txt

#2245 Add WC Helper connection information to requests
#2238 Allows package dimension input to begin with zero
#2243 Add dynamic carrier account registration form
#2244 Adds more specific validation to UPS connect form
#2261 Add link to schedule pickup for DHL Express
#2259 Fix signature required checkbox not updating prices
#2233 Add message to explain exclusive tax is needed for automated tax service
#2266 Disable USPS refunds for labels without tracking id.
This release branch is branched from latest `develop` 
- Test label purchase flow
- Test Store on WP.com
- Test all functionality with and without a connection to WooCommerce.com
- Test package dimensions starting with 0
- Test UPS connect form input validation
- Test DHL Express schedule pick up link
- Test …

Release 1.25.3

---

changelog.txt
classes/class-wc-connect-api-client.php
classes/class-wc-connect-settings-pages.php
classes/class-wc-rest-connect-subscriptions-controller.php
client/apps/shipping-settings/index.js
client/apps/shipping-settings/view-wrapper.js
client/extensions/woocommerce/woocommerce-services/api/url.js
client/extensions/woocommerce/woocommerce-services/style.scss
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/index.js
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/list-item.js
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/style.scss
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/test/index.js
tests/php/classes/test-class-wc-rest-connect-subscriptions-controller.php
woocommerce-services.php

This PR displays the subscriptions usage under wp-admin > WooCommerce > Settings > Shipping > WooCommerce Services.
It uses the subscriptions end point from the connect server.
I have also added the Rest Controller that was missing from the new end point.
The subscriptions endpoint on WCS had a `$body` parameter but there was nothing to send that was not generated by the API client. I have removed it. 
closes #2257 
To test the subscriptions usage display:
1) Use [this branch](https://github.com/Automattic/woocommerce-connect-server/tree/add/1615-subscription-usage-endpoint) on the connect servers and follow [steps 1 and 2 here](https://github.com/Automattic/woocommerce-connect-server/pull/1661) to activate the subscription for Square. ( I had to add the key on the Square plugin headers …

Show subscriptions usage in admin

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/components/carrier-icon/index.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/list-item.js

This allows DHL merchant carrier accounts to be displayed with the same DHL logo that is used by DHL Express.
Automattic/woocommerce-shipping-issues#125.
1. Pull the changes from Automattic/woocommerce-connect-server#1666 and follow the steps to enable DHL Express, DHL eCommerce, DHL eCommerce Asia, and DHL eCommerce International.
2. Visit **WooCommerce > Settings > Shipping > WooCommerceShipping**. You should now see the new DHL carrier accounts appear in the list of available Carrier Accounts, all using the same DHL logo as DHL Express.
_New DHL carrier accounts with correct logos_

Reuse DHL logos for DHL eCommerce, DHL eCommerce Asia, and DHL eCommerce International

---

changelog.txt
classes/class-wc-connect-api-client.php

Subscription flags should be able to enable carriers in carrier account list. The items in the carrier account list will depend on current subscriptions, so the request to populate this list need to include WCCOM connection info in order to get subscription status on request.
Currently, this WCCOM connection info is only sent in the body of `POST` requests. This PR adds this information to the header of all requests to the Connect Server, so that all request types will be able to send this information and have the Connect Server check existing subscription flags for a user's site. 
Our other options to resolve this would be to change the `GET /shipping/carriers` and `GET /shipping/carrier-types` requests to `POST` requests or to include the extra parameters as query parameters. Changing …

Send WCCOM connection info in request header

---

changelog.txt
classes/class-wc-connect-api-client.php
classes/class-wc-connect-settings-pages.php
classes/class-wc-rest-connect-subscription-activate-controller.php
classes/class-wc-rest-connect-subscriptions-controller.php
client/apps/shipping-settings/index.js
client/apps/shipping-settings/view-wrapper.js
client/extensions/woocommerce/woocommerce-services/api/url.js
client/extensions/woocommerce/woocommerce-services/components/carrier-icon/index.js
client/extensions/woocommerce/woocommerce-services/style.scss
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/list-item.js
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/index.js
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/list-item.js
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/style.scss
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/test/index.js
client/main.js
readme.txt
tests/php/classes/test-class-wc-rest-connect-subscriptions-controller.php
woocommerce-services.php

- https://github.com/Automattic/woocommerce-services/pull/2287 : Send WCCOM connection info in request header
- https://github.com/Automattic/woocommerce-services/pull/2284 : Reuse DHL logos for DHL eCommerce, DHL eCommerce Asia, and DHL eCommerce International
- https://github.com/Automattic/woocommerce-services/pull/2286 : Display inactive subscriptions with button to activate them
- https://github.com/Automattic/woocommerce-services/pull/2281 : Show subscriptions usage in admin
- https://github.com/Automattic/woocommerce-services/pull/2270 : chore(ReduxDevtools): upgrade deprecated usage
This release branch is branched from latest `develop` .
Closes https://github.com/Automattic/woocommerce-shipping-issues/issues/151
- Test label printing
- Test account connection
- …

release 1.25.5

---

changelog.txt
classes/class-wc-rest-connect-shipping-carrier-controller.php
classes/class-wc-rest-connect-shipping-carrier-delete-controller.php
client/extensions/woocommerce/woocommerce-services/components/carrier-icon/index.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/list-item.js

This allows DHL merchant carrier accounts to be displayed with the same DHL logo that is used by DHL Express.
Automattic/woocommerce-shipping-issues#125.
1. Pull the changes from Automattic/woocommerce-connect-server#1674 and follow the steps to enable DHL Express, DHL eCommerce Solutions, and DHL eCommerce Asia.
2. Visit **WooCommerce > Settings > Shipping > WooCommerceShipping**. You should now see the new DHL carrier accounts appear in the list of available Carrier Accounts, all using the same DHL logo as DHL Express.
_New DHL carrier accounts with correct logos_

Removes DHL eCommerce International, replaces DHL eCommerce with DHL eCommerce Solutions (logos)

---

changelog.txt
classes/class-wc-connect-shipping-method.php

Changing from `wp_cache_get` to `get_transient`, so that the API response is set with transients (rather than WP cache).
If a store does not have the WP cache configured, they would not benefit from the caching of the API response.
By using the transients, we're leveraging `wp_options` instead, which is always configured.
I ensured that the transient key length is short enough ([must be 172 character or shorter](https://developer.wordpress.org/reference/functions/set_transient/#parameters)).
I also added 2 new debug messages, to help with the debugging:
- "Cache contains rates response"
- "Cache does not rates response"
I am aware that I am using the word "cache", but I didn't think that the word "transient" would be useful, in this case. After all, we're using the `transient`s as a …

refactor: live rates response caching

---

changelog.txt
classes/class-wc-connect-shipping-method.php
classes/class-wc-rest-connect-shipping-carrier-controller.php
classes/class-wc-rest-connect-shipping-carrier-delete-controller.php
client/extensions/woocommerce/woocommerce-services/components/carrier-icon/index.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/list-item.js
npm-shrinkwrap.json
package.json
readme.txt
woocommerce-services.php

- https://github.com/Automattic/woocommerce-services/pull/2293 : Refreshes shipping methods after registering or removing carrier accounts
- https://github.com/Automattic/woocommerce-services/pull/2301 : Changed rates response caching method from cache to transient
- https://github.com/Automattic/woocommerce-services/pull/2308 : chore: update WC version
This release branch is branched from latest `develop` .
- Test against WC 5.0 beta (use the [WC beta tester plugin](https://wordpress.org/plugins/woocommerce-beta-tester/) for an easy switch)
- Test account connection
* Fix 	- Refreshes shipping methods after registering or removing carrier accounts.
* Tweak	- Changed rates response caching method from cache to transient.
Built from this branch using `php woorelease.phar …

release 1.25.6

---

changelog.txt
classes/class-wc-connect-taxjar-integration.php

As described in #1576 there was a situation where if the tax calculation failed while loading the checkout page, the checkout page would not display. This error primarily came up as an address, particularly zip code error. The only way to fix it previously was to modify the address some other way as you could no longer do it from the checkout page. There was a lot of digging on this issue to find the best approach and @Ferdev pinpointed an approach of not calculating tax on the checkout page load. I then picked up the issue and modified it slightly so that it may still calculate the tax on page load, but if it fails it doesn't add an error notice, which was breaking the checkout page and instead fail silently to give the user a chance to fix the error.
The taxes are actually calculated in …

Remove error notices from checkout page load

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/list-item.js

Link to connect a carrier account will break if WP is installed in a subdirectory.
closes #2298 
Install WordPress into a subdirectory.
Try to connect a carrier account.
Should not 404.

Use relative path so links work on subdirectory installs

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/list-item.js
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/style.scss

When the rate call usage is over limit, highlight the text in red and increase the font weight. Display a tooltip with the following message:
> Your store is over the limit for rate calls this month and your account will be charged for overages. To prevent future overage charges you can upgrade your plan.
Some things that I would like to point out in case they require further adjustment:
* The implemented view is not pixel-perfect but rather an approximation of the mockup.
* I have used the `--color-red-400` color rather than e.g. one of the `--color-error-*` colors.
* I have set the tooltip width to `200px` to be more like the design mockup as by default it is displayed as a single line.
Relevant CSS:
```css
.components-popover__content {
white-space: normal;
width: 200px;
}
```
* The …

Highlight rate call usage in red and display tooltip when over limit

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss

There was [a change introduced in `@wordpress/base-styles` to support high contrast mode on Windows](https://github.com/WordPress/gutenberg/pull/23706/files) that the styles in WCS&T are not compatible with.
How to reproduce:
1. Clone both the WooCommerce and WooCommerce Admin repos.
1. Compile WooCommerce:
* `git checkout 4.8.0 && npm install && composer install && npm run build`
1. Compile WooCommerce Admin using the commit where `@wordpress/base-styles` was upgraded:
* `git checkout c27e266051d4fc72b1e7fb87b2c4ac365d629cef && composer install && npm install && npm run build`
1. Copy the compiled problematic WC Admin stylesheet to WC:
* `cp woocommerce-admin/dist/app/style.css woocommerce/packages/woocommerce-admin/dist/app/style.css`
1. The radio button is off-center.
1. Compile WC …

Fix radio button dot alignment in "Create shipping label"

---

changelog.txt
classes/class-wc-connect-taxjar-integration.php
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/list-item.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/list-item.js
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/style.scss
readme.txt

- https://github.com/Automattic/woocommerce-services/pull/2303 : Fix radio button dot alignment in "Create shipping label"
- https://github.com/Automattic/woocommerce-services/pull/2314 : Highlight rate call usage in red and display tooltip when over limit
- https://github.com/Automattic/woocommerce-services/pull/2315 : Use relative path so links work on subdirectory installs
- https://github.com/Automattic/woocommerce-services/pull/2310 : Remove error notices from checkout page load
This release branch is branched from latest `develop` .
- Test against WC 5.0 beta (use the [WC beta tester plugin](https://wordpress.org/plugins/woocommerce-beta-tester/) for an easy switch)
- Test UI when creating shipping labels on different browsers
- Test TaxJar integration with …

release 1.25.7

---

.travis.yml

E2E tests are currently failing. This PR adds support for the `DONT_SKIP_E2E_TESTS` environment variable that, unless present, disables the `E2E tests` Travis job by default.
Once E2E tests are fixed, the condition can be removed from `.travis.yml`.
Fixes #2305.
**Before:** E2E tests fail on all PRs. Example: #2303.
**After:** E2E tests are not executed unless the `env(DONT_SKIP_E2E_TESTS)` variable is present either in `.travis.yml` or the repository settings. See the [Environment Variables chapter of the Travis documentation](https://docs.travis-ci.com/user/environment-variables/) for more information.

Disable E2E tests unless env(DONT_SKIP_E2E_TESTS) is present

---

client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/list-item.js
client/extensions/woocommerce/woocommerce-services/views/subscriptions-usage/test/index.js

Updated to use new format for usage events from connect server.
See connect server PR https://github.com/Automattic/woocommerce-connect-server/pull/1721 
for testing details.
https://github.com/Automattic/woocommerce-connect-server/issues/1695

Support new data format from connect server for multiple usage tracking events

---

client/components/forms/form-fieldset/index.js
client/components/forms/form-fieldset/style.scss

Replace the Calypso `FormFieldset` component with an internal `FormFieldset` component. There was not a comparable WordPress component to replace with and the component itself is very simple so it was easy to move over to our internal components. This component is simply a wrapper `fieldset` HTML tag for form fields and is primarily used by other components (TextField, NumberField, WeightField, etc). 
I placed the replacement component within the top level `client/components` directory based on some recent discussions on how best to organize our internal components. I kept the naming the same to simplify the code changes required. Due to having the same name, the Webpack config `resolve.modules` array order is hitting this new internal component rather than the Calypso component.
Related …

Replace Calypso Fieldset with internal Fieldset

---

client/components/toggle/index.js
client/extensions/woocommerce/woocommerce-services/views/label-settings/index.js
client/extensions/woocommerce/woocommerce-services/views/label-settings/style.scss

Replace the Calypso `FormToggle` component with the [Wordpress `FormToggle` Component](https://developer.wordpress.org/block-editor/components/form-toggle/). The props all matched up well so it required minimal changes. There were some styles for all `input[type='checkbox']` that were overriding the component's styles. I just copied the necessary styles over to get the higher specificity and it all looked good.
I didn't replicate the exact look of the previous toggle component, instead opting for a more simplified experience using the Wordpress component look and feel instead.
Related to #2333
The form toggle component was used on two screens:
1. WooCommerce Shipping Settings, the top Shipping Labels card.
2. WooCommerce Shipping Status, the Debug toggles.

Replace Calypso FormToggle with WP component

---

classes/class-wc-connect-help-view.php
classes/class-wc-rest-connect-service-data-refresh-controller.php
tests/php/test_class-wc-connect-shipping-method.php
woocommerce-services.php

Remove the extra brackets on the `require_once` line for `classes/class-wc-rest-connect-service-data-refresh-controller.php`. Also ran `vendor/bin/phpcbf classes/* tests/php/ woocommerce-services.php` for phpcs linting so that [this PR](https://github.com/Automattic/woocommerce-services/pull/2322)'s effort is kept.
Closes https://github.com/Automattic/woocommerce-services/issues/2349
1. First commit is to remove the bracket
2. Second commit is `vendor/bin/phpcbf classes/* tests/php/ woocommerce-services.php`
3. Run PHPUnit and tests should pass.

Remove extra brackets in develop

---

assets/stylesheets/_colors.scss
client/extensions/woocommerce/woocommerce-services/components/text-field/index.js
client/extensions/woocommerce/woocommerce-services/components/text-field/style.scss
client/extensions/woocommerce/woocommerce-services/style.scss
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/dynamic-settings-form.test.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/ups-settings-form.test.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/ups-settings-form.js
client/extensions/woocommerce/woocommerce-services/views/label-settings/index.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/customs-step/style.scss

As part of the goal to remove Calypso dependencies, this PR replaces the Calypso `FormTextInput` component in our `TextField` component with the WordPress `TextControl` component. There are still other uses of the `FormTextInput` component in other places that will be replaced in a separate PR to keep each PR more manageable and keep this one focused on the `TextField`. 
There were several differences between the components that required reworking a few areas of functionality. The two biggest differences were:
- The `TextControl` component comes with a built in label. This allowed us to remove the `FieldLabel` component from the `TextField`. It also required some additional styles to make sure the label display is carried over successfully.
- The `TextControl` component [does NOT provide …

Replace FormTextInput in TextField component

---

bin/wc-phpcbf
changelog.txt
lint-staged.config.js

Add phpcbf in our pre-commit hooks so that it automatically cleans up PHP linting errors based on our phpcs rules.
Closes https://github.com/Automattic/woocommerce-services/issues/2352
1. checkout this branch
2. run `composer install`
3. Make a change on `woocommerce-services.php` line 45, from 
`define( 'WOOCOMMERCE_CONNECT_MINIMUM_JETPACK_VERSION', '7.5' ); `
to 
`define('WOOCOMMERCE_CONNECT_MINIMUM_JETPACK_VERSION','8.5');`
4. `git add woocommerce-services.php` and `git commit`
5. You should see the linting run through and the style is fixed
6. Exit commit window with `:q!`

Add phpcbf to our pre-commit hooks using lint-staged

---

client/components/forms/form-label/index.js
client/components/forms/form-label/style.scss
client/components/toggle/index.js

Replace the Calypso `FieldLabel` component with an internal `FieldLabel` component. There was not a comparable WordPress component to replace with and the component itself is very simple so it was easy to move over to our internal components. In WordPress components, the field label is often included with the field component, so there may be a few more of these labels removed going forward.
I placed the replacement component within the top level `client/components` directory based on some recent discussions on how best to organize our internal components. I kept the naming the same to simplify the code changes required. Due to having the same name, the Webpack config resolve.modules array order is hitting this new internal component rather than the Calypso component.
Related to #2333 …

Replace Calypso FieldLabel with internal FieldLabel

---

assets/stylesheets/_components.scss
assets/stylesheets/style.scss
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/address-step/style.scss
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/address-step/unverified.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/customs-step/item-row-header.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/customs-step/package-row.js

Replace Calypso External-link component with WordPress External-link component.
Part of #2333
The following links have been replaced:
Purchasing labels, verification address links:
|<img width="551" alt="AddressVerificationLinks" src="https://user-images.githubusercontent.com/8002881/110496498-243ab900-80bb-11eb-942a-0c8bbc1fc815.png">|
|-|
Purchasing labels, customs form, more info links:
|<img width="1085" alt="CustomsFormLinks" src="https://user-images.githubusercontent.com/8002881/110496662-551aee00-80bb-11eb-8f2b-6d0409a8d6be.png">|
|-|

Replace Calypso External-link component with WordPress component

---

classes/class-wc-connect-functions.php

The `wc/store/checkout` was blocked inside the shipping calculation. This PR unblocks it and allows the functions to fetch rates correctly. When the endpoint was blocked the rates were not registered and the cart shipping totals calculation was selecting the default shipping method.
Found during 1.25.9 testing call.
From the testing post:
```
When using the following setup:
Cart page housing either the [woocommerce_cart] shortcode or Cart block,
Checkout page using the Checkout block.
Site has WCS&T enabled.
When picking one shipping option with a live rate on the Cart page, and then picking another shipping option with a live rate in the Checkout block, the order will have no shipping costs associated with it.
In addition to that, when I set up the following shipping methods:
Local …
```

Detect checkout block REST API call correctly.

---

changelog.txt
classes/class-wc-connect-jetpack.php
classes/class-wc-connect-nux.php

Instead of using the deprecated `JETPACK_MASTER_USER` constant, the Jetpack class now uses proper method from the Jetpack manager to get the status of the connection
Closes https://github.com/Automattic/woocommerce-shipping-issues/issues/185
1. Create a new test site with latest WooCommerce.
2. Install latest Jetpack version v9.6.
3. Install this plugin and connect the site to Jetpack. The connection should be made without incidents.

Replaces deprecated Jetpack constant JETPACK_MASTER_USER

---

.github/workflows/php_tests.yml

Support latest woocommerce 5.1.0 in our CI pipeline.
N/A
Make sure pipeline passes.

Bump testing matrix to support latest woocommerce 5.1.0

---

changelog.txt
classes/class-wc-connect-settings-pages.php
client/apps/shipping-settings/index.js
client/apps/shipping-settings/view-wrapper.js
client/extensions/woocommerce/woocommerce-services/style.scss
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/index.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/list-item.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/index.js
client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/carriers-list.js
client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/index.js
client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/style.scss
client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/test/live-rates-carriers-list.test.js
woocommerce-services.php

Adding a "Live rates at checkout" section on the settings page.
Some details are on the ticket.
Checked with UX - a few things that are ok for this first phase:
- the tooltip’s width cannot be modified and I also cannot add artificial line breaks - everything needs to go into one line: https://d.pr/i/I29c68
- I tried to keep the alignment of the columns consistent - but on small screens it becomes evident that we’re trying to squeeze a lot of content on a small column: https://d.pr/i/LwYhQB
- on even smaller screens the whole app is a bit messed up
Closes https://github.com/Automattic/woocommerce-shipping-issues/issues/188
When testing against production (when testing against local/staging you might need to remove `DhlExpressAccount` from the `enabled_carrier_accounts` setting on the …

feat: add live rates carriers list section

---

changelog.txt
classes/class-wc-connect-note-dhl-live-rates-available.php
woocommerce-services.php

This PR adds an inbox notification about DHL live rates for customers that can have DHL live rates.
( = when they have get_service_schema_by_id( 'dhlexpress' ); )
The note is only displayed once, goes away when they dismiss it or action it (Click on 'Go to Shipping Zones')
The note is deleted from the DB when the plugin is uninstalled.
Closes: https://github.com/Automattic/woocommerce-shipping-issues/issues/189
1. With WooCommerce and WooCommerce Shipping and Tax active
2. Test on a store without DHL Express live rates available. Check there is no notice.
3. Activate the flag for the store. Refresh the status on the plugin Status page.
4. Check there is a notice like this:
6. Dismiss the notice. Activate-deactivate the plugin, check the notice is not displayed again.
Note: If you want to …

Add DHL Live rates inbox notification

---

classes/class-wc-connect-note-dhl-live-rates-available.php

Change condition to display DHL notice, same as [on the live rates card](https://github.com/Automattic/woocommerce-services/blob/378862c4df16230c89ae2cbbe9ad7423cd667da0/client/extensions/woocommerce/woocommerce-services/views/live-rates-carriers-list/carriers-list.js#L72).
1. Activate the plugin on a new JN site
2. Check the notice is not displayed
3. Activate the flag for DHL live rates
4. Check the notice is displayed

Fix condition to display DHL live rates notice.

---

assets/stylesheets/_components.scss
client/apps/print-test-label/view.js
client/components/forms/form-select/index.js
client/components/forms/form-select/styles.scss
client/extensions/woocommerce/woocommerce-services/components/dropdown/index.js
client/extensions/woocommerce/woocommerce-services/views/label-settings/label-settings.js
client/extensions/woocommerce/woocommerce-services/views/packages/edit-package.js
client/extensions/woocommerce/woocommerce-services/views/service-settings/shipping-services/entry.js
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-select.js
tests/client/jest.config.js
webpack.config.js

Replacing the `form-select` component from Calypso.
I copied the styles and the body from Calypso, making it a functional component.
Unfortunately, the `@wordpress/components` component doesn't allow `optgroup` children.
I have a PR open for that: https://github.com/WordPress/gutenberg/pull/29540
Moreover, the Calypso styles are targeting _all_ `select` elements, causing some visual artifacts when using the `SelectControl` from `@wordpress/components`: https://d.pr/i/iYhj0G
In the meantime, the team agreed to just copy the styles/component to get rid of the Calypso submodule.
Original: https://github.com/Automattic/wp-calypso/blob/df4ddfdc94438b6d31b686d6415e08a567570944/client/components/forms/form-select/index.jsx
You might think the Calypso styles are all in here: …

refactor: calypso form-select

---

client/components/forms/form-label/index.js

Status page (and a few others?) is broken.
Fixing.
Cannot set both `dangerouslySetInnerHTML` and `children`.
Related to https://github.com/Automattic/woocommerce-services/issues/2333

fix: broken status page

---

classes/class-wc-connect-settings-pages.php

The notice was caused by no array key existence check which is now performed by `empty()`. Also, an invalid key was used.
Replace `array_values()` with `current()` since only the first value is used.
It seems this issue was [caused by this change.](https://github.com/Automattic/woocommerce-services/pull/2375/files#diff-45ab2d6757efe6316bd243c6eb0cf9194e30ddd4c01b98de3ed0e4a9b0aec1a9)
For context on how this looked previously, [this is the PR where the `$carrier_information` variable was introduced](https://github.com/Automattic/woocommerce-services/pull/2265/files#diff-45ab2d6757efe6316bd243c6eb0cf9194e30ddd4c01b98de3ed0e4a9b0aec1a9).
Fixes #2381.
Because of this bug, the following breadcrumbs were not displayed. They should be visible with the changes in this PR.

Fix PHP notice on carrier registration page

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/rates-step/style.scss

Due to [a change introduced in Gutenberg](https://github.com/WordPress/gutenberg/pull/27377), WCS&T radio button dot is now offset by several px. This commit introduces a `transform: none` CSS rule reverting this behavior.
Fixes #2380, #2321.

Unset translate() transform on radio buttons in label purchase modal

---

.github/workflows/php_tests.yml
bin/wc-latest-version.php

Automatically find the last 3 minor woocommerce versions to run our Github action matrix tests. This PR is inspired by https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#example-returning-a-json-object. 
- Create another job to find the last 3 WC minor version numbers
- Added a php script to output the version numbers out to stdout, ie. `[4.9.2, 5.0.1, 5.1.0]`. 
Closes: https://github.com/Automattic/woocommerce-services/issues/2364
1. Scroll to the bottom of the PR, check the actions ran and they passed
2. Click on the "Checks" tab for this PR, make sure it now has a job to find WooCommerce latest 3 minor versions, and it spawns a few other jobs to run the tests on. On the left side, you should see it testing the new WooCommerce 5.1
We want to …

Use a script to find latest 3 minor versions for WooCommerce for test

---

changelog.txt
classes/class-wc-connect-api-client-live.php
classes/class-wc-connect-options.php
classes/class-wc-connect-service-schemas-store.php
woocommerce-services.php

closes https://github.com/Automattic/woocommerce-shipping-issues/issues/192
Many extra requests are being sent to the connect server with changes in 1.25.9. Most of these are from stores which are not authenticated. This happens because a store with an invalid blog token we keep trying to fetch services even though it fails each time.
https://github.com/Automattic/woocommerce-shipping-issues/issues/192
Ensure your site is connected to production connect server. 
Change your blog token to an invalid one. This code should do it
```php
add_action( 'jetpack_loaded', function () {
Jetpack_Options::update_option( 'blog_token', 'PjbxIr&GJJ8MzH^Vfan4gjXoqciy8g*Y.3Ww95YzGFyW(aY*g!C&VszYI0q^K7SG6' );
} );
```
If you using master you will see a 401 request on each page load to `/services` with this …

Do not retry fetching services on auth failure

---

readme.txt

- https://github.com/Automattic/woocommerce-services/pull/2379 :  Use a script to find latest 3 minor versions for WooCommerce for test.
- https://github.com/Automattic/woocommerce-services/pull/2334 :  Add an endpoint for shipping label creation eligibility for Woo mobile.
- https://github.com/Automattic/woocommerce-services/pull/2394 :  Do not retry fetching services on auth failure.
- https://github.com/Automattic/woocommerce-services/pull/2391 :  Fix Shipping validation notice shown when no address entered.
This release branch is branched from latest `master`.
- Test label purchase.
- Test settings screen.
- Test status screen.
- Test living rates (USPS/DHL).
- Test account registration.
* Add   - Add an endpoint for shipping label creation eligibility and share code for store …

release: 1.25.10

---

changelog.txt
classes/class-wc-rest-connect-shipping-label-status-controller.php
client/extensions/woocommerce/woocommerce-services/api/url.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/actions.js
client/extensions/woocommerce/woocommerce-services/state/shipping-label/reducer.js

The purchase label endpoint is asynchronous (the sync behavior is [discouraged](https://href.li/?1227-gh-Automattic/woocommerce-connect-server), and the web client uses the status endpoint for each created label individually after the purchase.
With the mobile apps consuming the API, there are some new constraints regarding the network availability, and the round-trip delays, so this PR is updating the `label status` endpoint to accept multiple label_ids at the same time, and updates the web client to use it instead, and following the list of changes:
1. Update the endpoint to accept multiple ids: 6bd250a
2. Update the labels polling after a purchase to use the new endpoint: 3c3ae4f.
3. Update the logic of fetching labels to use the new endpoint: 369e0b8
Relevant discussion: p91TBi-4K3-p2 …

Update the shipping label status API to fetch multiple ones

---

changelog.txt
client/apps/plugin-status/indicator.js
client/apps/plugin-status/state/actions.js
client/apps/plugin-status/style.scss
client/apps/plugin-status/woocommerce-services-indicator.js

I thought it would be nice to display a spinner icon on the status page when the data is refreshing in the background. Otherwise there's no feedback of the action that the user has taken.
- Go to the status page
- Click refresh
- During the refresh, a spinner icon is displayed

feat: spinner icon on service data fetch

---

changelog.txt
classes/class-wc-connect-shipping-label.php

We had received a report of a syntax error for some PHP 7 syntax (return type and string parameter type in functions). To meet the requirement of PHP 5.6 compatibility, I removed this additional syntax. To confirm there were not additional issues, I ran the [PHPCompatibility tool](https://github.com/PHPCompatibility/PHPCompatibility) to look for further issues and address them all at once.
Fixes #2401 
1. Set up a site using PHP 5.6 and older version of WC (I used 4.1 to test: https://wordpress.org/plugins/woocommerce/advanced/)
2. Find a shippable order ID.
3. Make a GET request to your store API endpoint: connect/label/<order_id>/creation_eligibility
4. Confirm syntax error.
5. Update to this branch and request again.
6. Confirm no syntax error.

Fix PHP 5 compatibility issues

---

changelog.txt
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/test/ups-settings-form.test.js
client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/ups-settings-form.js

I noticed that if the merchant tries to connect their UPS account (with the invoice information) and the submission doesn't go well, the button remains deactivated until all the fields are re-edited.
Fixing.
- Go register a UPS account
- Enter some jibberish (without checking the "I have been issued an invoice from UPS within the past 90 days" checkbox)
- Submission should fail
- Check the checkbox
- Enter additional jibberish
- Submit again
- Submission should fail, but the "connect" button should be clickable
- On the `develop` branch, the "Connect" button didn't become clickable until both "UPS invoice number" and "UPS invoice date" were edited

fix: UPS registration form submission on invalid data

---

classes/class-wc-connect-taxjar-integration.php

The `$wc_cart_object->remove_taxes();` branch is never going to be reached.
First of all, `wc_cart_object` is not a variable in the scope, so the whole application would break.
Second of all, it will never be reached because of the early return on this line: https://github.com/Automattic/woocommerce-services/blob/develop/classes/class-wc-connect-taxjar-integration.php#L870
I didn't add a changelog entry because this little change isn't worth it.

chore(TaxJar): remove branching on tax calculation

---

changelog.txt
classes/class-wc-connect-taxjar-integration.php

Renames the "Tax name" column, so that people can more easily identify the tax rates by the counties for reports.
This change is only valid for the US (I didn't want to break it for other countries). Although I feel like it might be useful to extend this format for all countries 🤷 
Fix: https://github.com/Automattic/woocommerce-services/issues/2226
- I recommend deleting all your existing tax rates before this - or maybe only keep the ones you want to see changing
- Change your store to be based in MN (just as an example for nexus)
- Place 2 orders on your store to both these addresses:
- 1000 Nicollet Mall, Minneapolis, MN 55403
- 2105 London Rd, Duluth, MN 55812
- Go to WooCommerce > Settings > Tax > Standard rates, you should see updated values: https://d.pr/i/aSdMzN
- Go to Analytics …

refactor: rename tax name for US
